import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, extname } from 'path'

const ASSET_DIRS = ['heroes', 'units', 'items', 'abilities', 'upgrades']
const ASSETS_ROOT = 'assets'
const OUT_DIR = 'web/src/client/standalone'
const OUT_FILE = join(OUT_DIR, 'iconMap.ts')

mkdirSync(OUT_DIR, { recursive: true })

const entries: string[] = []

for (const dir of ASSET_DIRS) {
  const dirPath = join(ASSETS_ROOT, dir)
  let files: string[]
  try {
    files = readdirSync(dirPath).filter((f) => extname(f) === '.webp')
  } catch {
    continue
  }
  for (const file of files) {
    const key = `/${dir}/${file}`
    const data = readFileSync(join(dirPath, file))
    const b64 = data.toString('base64')
    entries.push(`  '${key}': 'data:image/webp;base64,${b64}'`)
  }
}

const content =
  `// Generated by scripts/build-standalone.ts — do not edit\n` +
  `export const ICON_MAP: Record<string, string> = {\n` +
  entries.join(',\n') +
  `,\n}\n`

writeFileSync(OUT_FILE, content)
console.log(`Wrote ${entries.length} icons to ${OUT_FILE}`)
