import type { HeroEntry } from './balance.js'

// Cumulative XP required to reach each hero level (index = level - 1).
export const HERO_XP_THRESHOLDS = [0, 200, 500, 900, 1400, 2000, 2700, 3500, 4400, 5400]

// Playable heroes — one record per fourcc id.
export const HERO_DATA: Record<string, HeroEntry> = {
  Hamg: {
    name: 'Archmage',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Intelligence',
      str: 14,
      strGain: 2,
      agi: 17,
      agiGain: 1,
      int: 19,
      intGain: 3.2,
      armor: 0,
      damageMin: 21,
      damageMax: 27,
      attackRange: '600',
    },
    effect:
      'Hailing from the magical kingdom of Dalaran, the Archmagi represent the pinnacle of magical power.',
    abilities: ['AHbz', 'AHab', 'AHmt', 'AHwe'],
  },
  Hmkg: {
    name: 'Mountain King',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Strength',
      str: 24,
      strGain: 3,
      agi: 11,
      agiGain: 1.5,
      int: 15,
      intGain: 1.5,
      armor: 1,
      damageMin: 26,
      damageMax: 36,
      attackRange: 'Melee',
    },
    effect:
      "The Mountain Kings, or 'Thanes' as they are known in Khaz Modan, are the mightiest Dwarven warriors under the mountain.",
    abilities: ['AHav', 'AHbh', 'AHtb', 'AHtc'],
  },
  Hpal: {
    name: 'Paladin',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Strength',
      str: 22,
      strGain: 2.7,
      agi: 13,
      agiGain: 1.5,
      int: 17,
      intGain: 1.8,
      armor: 2,
      damageMin: 24,
      damageMax: 34,
      attackRange: 'Melee',
    },
    effect:
      'Although the Paladins were once loved and revered throughout the lands of Lordaeron, they have since fallen on hard times.',
    abilities: ['AHad', 'AHds', 'AHhb', 'AHre'],
  },
  Hblm: {
    name: 'Blood Mage',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Intelligence',
      str: 18,
      strGain: 2,
      agi: 14,
      agiGain: 1,
      int: 19,
      intGain: 3,
      damageMin: 21,
      damageMax: 27,
      attackRange: '600',
    },
    effect:
      "Many of the stoic high elves, reeling from the loss of their ancient homeland, Quel'Thalas, have given in to their hatred and despair and embraced the dark side of their magical natures.",
    abilities: ['AHbn', 'AHfs', 'AHpx', 'AHdr'],
  },
  Obla: {
    name: 'Blademaster',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Agility',
      str: 18,
      strGain: 2,
      agi: 22,
      agiGain: 1.75,
      int: 16,
      intGain: 2.25,
      armor: 0,
      damageMin: 24,
      damageMax: 46,
      attackRange: 'Melee',
    },
    effect:
      'Though their numbers are few, the seasoned Blademasters represent an elite fighting force within the Horde.',
    abilities: ['AOww', 'AOcr', 'AOmi', 'AOwk'],
  },
  Ofar: {
    name: 'Far Seer',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Intelligence',
      str: 15,
      strGain: 2,
      agi: 18,
      agiGain: 1,
      int: 19,
      intGain: 3,
      armor: 0,
      damageMin: 21,
      damageMax: 27,
      attackRange: '600',
    },
    effect: 'Far Seers are ancient Orcs who represent the pinnacle of Shamanistic power.',
    abilities: ['AOcl', 'AOeq', 'AOfs', 'AOsf'],
  },
  Oshd: {
    name: 'Shadow Hunter',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Agility',
      str: 15,
      strGain: 2,
      agi: 20,
      agiGain: 1.5,
      int: 17,
      intGain: 2.5,
      armor: 0,
      damageMin: 22,
      damageMax: 28,
      attackRange: '600',
    },
    effect: 'A cunning Hero, adept at healing magics and voodoo curses.',
    abilities: ['AOvd', 'AOhw', 'AOhx', 'AOsw'],
  },
  Otch: {
    name: 'Tauren Chieftain',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Strength',
      str: 25,
      strGain: 3.2,
      agi: 10,
      agiGain: 1.5,
      int: 15,
      intGain: 1.3,
      armor: 1,
      damageMin: 27,
      damageMax: 37,
      attackRange: 'Melee',
    },
    effect:
      'These elder Tauren warriors lead their Tribes in daily life as well as in battle. Ceremoniously decked with the ancient totems of their Tribes, Chiefs uphold the honor and simplicity of Tauren culture.',
    abilities: ['AOae', 'AOre', 'AOsh', 'AOws'],
  },
  Udea: {
    name: 'Death Knight',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Strength',
      str: 23,
      strGain: 2.7,
      agi: 12,
      agiGain: 1.5,
      int: 17,
      intGain: 1.8,
      armor: 1,
      damageMin: 25,
      damageMax: 35,
      attackRange: 'Melee',
    },
    effect: 'Death Knights were once virtuous defenders of Humanity.',
    abilities: ['AUan', 'AUdc', 'AUdp', 'AUau'],
  },
  Udre: {
    name: 'Dreadlord',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Strength',
      str: 20,
      strGain: 2.5,
      agi: 16,
      agiGain: 1,
      int: 18,
      intGain: 2.5,
      armor: 0,
      damageMin: 22,
      damageMax: 32,
      attackRange: 'Melee',
    },
    effect:
      "Dread Lords are incredibly powerful demons who wield the powers of darkness and mental domination. These cunning, malefic beings once served as the demon Kil'jaeden's most trusted lieutenants.",
    abilities: ['AUcs', 'AUin', 'AUsl', 'AUav'],
  },
  Ulic: {
    name: 'Lich',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Intelligence',
      str: 15,
      strGain: 2,
      agi: 14,
      agiGain: 1,
      int: 20,
      intGain: 3.4,
      armor: 0,
      damageMin: 22,
      damageMax: 28,
      attackRange: '600',
    },
    effect:
      "During his mortal life as the Warchief of the Orcish Horde of Draenor; Ner'zhul commanded a number of Orcish Warlocks and Shamans.",
    abilities: ['AUfn', 'AUfu', 'AUdr', 'AUdd'],
  },
  Ucrl: {
    name: 'Crypt Lord',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Strength',
      str: 26,
      strGain: 3.2,
      agi: 14,
      agiGain: 1.2,
      int: 14,
      intGain: 1.6,
      armor: 0,
      damageMin: 28,
      damageMax: 34,
      attackRange: 'Melee',
    },
    effect:
      'These ancient, evil behemoths were once the mighty kings of the subterranean spider kingdom of Azjol-Nerub.',
    abilities: ['AUim', 'AUts', 'AUcb', 'AUls'],
  },
  Edem: {
    name: 'Demon Hunter',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Agility',
      str: 19,
      strGain: 2.4,
      agi: 21,
      agiGain: 1.5,
      int: 16,
      intGain: 2.1,
      armor: 0,
      damageMin: 23,
      damageMax: 45,
      attackRange: 'Melee',
    },
    effect:
      'Demon Hunters are dark, shadowy warriors who are shunned by the greater Night Elf society. They made a pact, long ago, to fight against the forces of chaos using its own terrible powers against it.',
    abilities: ['AEmb', 'AEim', 'AEev', 'AEme'],
  },
  Ekee: {
    name: 'Keeper of the Grove',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Intelligence',
      str: 16,
      strGain: 2,
      agi: 15,
      agiGain: 1.5,
      int: 18,
      intGain: 2.7,
      armor: 0,
      damageMin: 20,
      damageMax: 26,
      attackRange: '600',
    },
    effect:
      'The enchanted Keepers are the favored sons of the demigod Cenarius. Like their lesser Dryad sisters, the Keepers appear to be half Night Elf, half stag.',
    abilities: ['AEer', 'AEfn', 'AEah', 'AEtq'],
  },
  Emoo: {
    name: 'Priestess of the Moon',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Agility',
      str: 18,
      strGain: 1.9,
      agi: 19,
      agiGain: 1.5,
      int: 15,
      intGain: 2.6,
      armor: 0,
      damageMin: 21,
      damageMax: 31,
      attackRange: '600',
    },
    effect:
      "The fearless leaders of the Sentinel army, the Priestesses of the Moon epitomize the power and grace of their race's ancient Moon Goddess, Elune.",
    abilities: ['AEst', 'AEar', 'AEsf'],
  },
  Ewar: {
    name: 'Warden',
    supply: 5,
    gold: 400,
    lumber: 100,
    stats: {
      primaryAttribute: 'Agility',
      str: 18,
      strGain: 2.4,
      agi: 20,
      agiGain: 1.6,
      int: 16,
      intGain: 2,
      armor: 0,
      damageMin: 22,
      damageMax: 42,
      attackRange: 'Melee',
    },
    effect:
      "The mysterious wardens serve as the night elves' special police force in Kalimdor. Set apart from the militant Sentinels, wardens are usually employed as jailors, assassins, and bounty hunters.",
    abilities: ['AEbl', 'AEfk', 'AEsh', 'AEsv'],
  },
  Nalc: {
    name: 'Alchemist',
    supply: 5,
    gold: 425,
    lumber: 135,
    stats: {
      primaryAttribute: 'Strength',
      str: 25,
      strGain: 3.3,
      agi: 10,
      agiGain: 1,
      int: 18,
      intGain: 2,
      armor: 0,
      damageMin: 28,
      damageMax: 55,
      attackRange: 'Melee / 500 (Air)',
    },
    effect:
      'In this unconventional pairing, a fanatical Goblin master rides on the back of his Ogre slave.',
    abilities: ['ANhs', 'ANab', 'ANcr', 'ANtm'],
  },
  Nbst: {
    name: 'Beastmaster',
    supply: 5,
    gold: 425,
    lumber: 135,
    stats: {
      primaryAttribute: 'Strength',
      str: 24,
      strGain: 2.9,
      agi: 14,
      agiGain: 1.3,
      int: 15,
      intGain: 1.8,
      armor: 0,
      damageMin: 26,
      damageMax: 36,
      attackRange: 'Melee',
    },
    effect:
      'A warrior Hero, able to call forth the creatures of the forest to serve him. These lone wandering forest dwellers come from all backgrounds and cultures, seeking the essence of combat through the mimicry of wild beasts.',
    abilities: ['ANsg', 'ANsq', 'ANsw', 'ANst'],
  },
  Nbrn: {
    name: 'Dark Ranger',
    supply: 5,
    gold: 425,
    lumber: 135,
    stats: {
      primaryAttribute: 'Agility',
      str: 18,
      strGain: 1.9,
      agi: 21,
      agiGain: 1.5,
      int: 15,
      intGain: 2.6,
      armor: 0,
      damageMin: 23,
      damageMax: 33,
      attackRange: '600',
    },
    effect:
      "A cunning Hero, adept at manipulating opponents. Forcibly raised from the dead, the former Rangers of Quel'Thalas enjoy nothing more than sowing dissension and hatred within the enemy ranks. Attacks land and air units.",
    abilities: ['ANdr', 'ANsi', 'ANba', 'ANch'],
  },
  Nfir: {
    name: 'Fire Lord',
    supply: 5,
    gold: 425,
    lumber: 135,
    stats: {
      primaryAttribute: 'Agility',
      str: 15,
      strGain: 2,
      agi: 20,
      agiGain: 1.6,
      int: 18,
      intGain: 2.5,
      armor: 0,
      damageMin: 22,
      damageMax: 28,
      attackRange: '550',
    },
    effect:
      'Long ago, when the world was in a state of constant turmoil, the Elementals (Earth, Wind, Fire and Water) faithfully served their Old-God masters.',
    abilities: ['ANia', 'ANso', 'ANlm', 'ANvc'],
  },
  Nngs: {
    name: 'Naga Sea Witch',
    supply: 5,
    gold: 425,
    lumber: 135,
    stats: {
      primaryAttribute: 'Intelligence',
      str: 15,
      strGain: 2,
      agi: 16,
      agiGain: 1,
      int: 22,
      intGain: 3,
      armor: 0,
      damageMin: 24,
      damageMax: 34,
      attackRange: '600',
    },
    effect:
      'A mystical Hero, adept at ranged combat. These scaly denizens of the ocean have often been associated with the coming of prodigious storms, but few have actually seen them rise from the sea and lived to tell the tale.',
    abilities: ['ANms', 'ANfa', 'ANfl', 'ANto'],
  },
  Npbm: {
    name: 'Pandaren Brewmaster',
    supply: 5,
    gold: 425,
    lumber: 135,
    stats: {
      primaryAttribute: 'Strength',
      str: 23,
      strGain: 3,
      agi: 14,
      agiGain: 1.5,
      int: 16,
      intGain: 1.5,
      armor: 1,
      damageMin: 25,
      damageMax: 35,
      attackRange: 'Melee',
    },
    effect:
      'Hailing from the secretive Pandaren Empire, the mighty brewmasters travel the world in search of exotic ales and the finest brewed spirits.',
    abilities: ['ANbf', 'ANdb', 'ANdh', 'ANef'],
  },
  Nplh: {
    name: 'Pit Lord',
    supply: 5,
    gold: 425,
    lumber: 135,
    stats: {
      primaryAttribute: 'Strength',
      str: 28,
      strGain: 3.2,
      agi: 16,
      agiGain: 1.3,
      int: 14,
      intGain: 1.5,
      armor: 0,
      damageMin: 30,
      damageMax: 40,
      attackRange: 'Melee',
    },
    effect:
      'A warrior hero, exceptional at weakening enemies and melee combat. These massive Demons take sadistic pleasure from instilling crazed terror, and then slaughtering their enemies. Attacks land units.',
    abilities: ['ANrf', 'ANca', 'ANht', 'ANdo'],
  },
  Ntin: {
    name: 'Tinker',
    supply: 5,
    gold: 425,
    lumber: 135,
    stats: {
      primaryAttribute: 'Intelligence',
      str: 22,
      strGain: 2.4,
      agi: 15,
      agiGain: 1,
      int: 20,
      intGain: 2.6,
      armor: 1,
      damageMin: 22,
      damageMax: 28,
      attackRange: 'Melee',
    },
    effect:
      "Goblins are known for their mechanical expertise and clever, though sometimes peculiar, inventions, and the Tinker is certainly no exception. With his Claw-Pack/Hammer-Tank combo, the Tinker's ingenuity is undeniable.",
    abilities: ['ANeg', 'ANcs', 'ANsy', 'ANrg'],
  },
}

/** Fourcc ids of all playable heroes — the keys of HERO_DATA. */
export const HERO_OBSERVER_IDS = new Set(Object.keys(HERO_DATA))
