export const UNIT_NAMES: Record<string, string> = {
  // Heroes
  Hamg: 'Archmage',
  Hmkg: 'Mountain King',
  Hpal: 'Paladin',
  Hblm: 'Blood Mage',
  Obla: 'Blademaster',
  Ofar: 'Far Seer',
  Oshd: 'Shadow Hunter',
  Otch: 'Tauren Chieftain',
  Udea: 'Death Knight',
  Udre: 'Dreadlord',
  Ulic: 'Lich',
  Ucrl: 'Crypt Lord',
  Edem: 'Demon Hunter',
  Ekee: 'Keeper of the Grove',
  Emoo: 'Priestess of the Moon',
  Ewar: 'Warden',
  Nalc: 'Alchemist',
  Nbst: 'Beastmaster',
  Nbrn: 'Dark Ranger',
  Nfir: 'Fire Lord',
  Nngs: 'Naga Sea Witch',
  Npbm: 'Pandaren Brewmaster',
  Nplh: 'Pit Lord',
  Ntin: 'Tinker',
  // Human
  hpea: 'Peasant',
  hmil: 'Militia',
  hfoo: 'Footman',
  hrif: 'Rifleman',
  hkni: 'Knight',
  hmpr: 'Priest',
  hsor: 'Sorceress',
  hspt: 'Spellbreaker',
  hgyr: 'Flying Machine',
  hmtm: 'Mortar Team',
  hmtt: 'Siege Engine',
  hgry: 'Gryphon Rider',
  hdhw: 'Dragonhawk Rider',
  hwel: 'Water Elemental',
  opeo: 'Peon',
  ogru: 'Grunt',
  ohun: 'Troll Headhunter',
  otbk: 'Troll Berserker',
  oshm: 'Shaman',
  odoc: 'Troll Witch Doctor',
  orai: 'Raider',
  ospw: 'Spirit Walker',
  osw1: 'Spirit Wolf',
  otbr: 'Troll Batrider',
  ocat: 'Demolisher',
  okod: 'Kodo Beast',
  owyv: 'Wind Rider',
  otau: 'Tauren',
  uaco: 'Acolyte',
  ushd: 'Shade',
  ugho: 'Ghoul',
  ugar: 'Gargoyle',
  uban: 'Banshee',
  unec: 'Necromancer',
  ucry: 'Crypt Fiend',
  uobs: 'Obsidian Statue',
  uabo: 'Abomination',
  umtw: 'Meat Wagon',
  ubsp: 'Destroyer',
  ufro: 'Frost Wyrm',
  uske: 'Skeleton Warrior',
  uskw: 'Skeleton Warrior',
  uskm: 'Skeletal Mage',
  ucrb: 'Carrion Beetle',
  ewsp: 'Wisp',
  earc: 'Archer',
  edot: 'Druid of the Talon',
  ehip: 'Hippogryph',
  efdr: 'Faerie Dragon',
  esen: 'Huntress',
  edry: 'Dryad',
  ebal: 'Glaive Thrower',
  edoc: 'Druid of the Claw',
  ehir: 'Hippogryph Rider',
  echm: 'Chimaera',
  emtg: 'Mountain Giant',
  ensw: 'Sentry Ward',
  etrt: 'Treant',
  eaow: 'Ancient of War',
  eaol: 'Ancient of Lore',
  eawn: 'Ancient of Wind',
  etol: 'Tree of Life',
  etoa: 'Tree of Ages',
  etoe: 'Tree of Eternity',
  emwl: 'Moon Well',
  ehhl: "Hunter's Hall",
  eale: 'Altar of Elders',
  eawo: 'Ancient of Wonders',
  ngir: 'Goblin Shredder',
  ngsp: 'Goblin Sapper',
  nzep: 'Goblin Zeppelin',
  nass: 'Assassin',
  nfgb: 'Bloodfiend',
  nbdw: 'Blue Dragonspawn Warrior',
  nskf: 'Burning Archer',
  ncea: 'Centaur Archer',
  ncen: 'Centaur Outrunner',
  ndtb: 'Dark Troll Berserker',
  ndtp: 'Dark Troll Shadow Priest',
  ndrm: 'Draenei Disciple',
  nftb: 'Forest Troll Berserker',
  nfsh: 'Forest Troll High Priest',
  nfsp: 'Forest Troll Shadow Priest',
  nrvs: 'Frost Revenant',
  nwlg: 'Giant Wolf',
  ngnb: 'Gnoll Brute',
  ngnw: 'Gnoll Warden',
  nhrw: 'Harpy Windwitch',
  nits: 'Ice Troll Berserker',
  nitp: 'Ice Troll Priest',
  nkog: 'Kobold Geomancer',
  nkol: 'Kobold Taskmaster',
  nkot: 'Kobold Tunneler',
  nmbg: "Mur'gul Blood-Gill",
  nmsn: "Mur'gul Snarecaster",
  ngrk: 'Mud Golem',
  nmfs: 'Murloc Flesheater',
  nnwr: 'Nerubian Seer',
  nnwa: 'Nerubian Warrior',
  nomg: 'Ogre Magi',
  nogm: 'Ogre Mauler',
  nqbh: 'Quillboar Hunter',
  nrog: 'Rogue',
  nsts: 'Satyr Shadowdancer',
  nsog: 'Skeletal Orc Grunt',
  nsln: 'Sludge Monstrosity',
  nssp: 'Spitting Spider',
  nsrh: 'Stormreaver Hermit',
  ntkh: 'Tuskarr Healer',
  nubw: 'Unbroken Darkweaver',
  nvdw: 'Voidwalker',
  nowb: 'Wildkin',
}

export const ITEM_NAMES: Record<string, string> = {
  phea: 'Potion of Healing',
  pghe: 'Potion of Greater Healing',
  pman: 'Potion of Mana',
  pgma: 'Potion of Greater Mana',
  pres: 'Potion of Restoration',
  pinv: 'Potion of Invisibility',
  pgin: 'Potion of Greater Invisibility',
  pnvu: 'Potion of Invulnerability',
  pnvl: 'Potion of Lesser Invulnerability',
  pspd: 'Potion of Speed',
  pdiv: 'Potion of Divinity',
  pomn: 'Potion of Omniscience',
  pams: 'Anti-magic Potion',
  vamp: 'Vampiric Potion',
  hslv: 'Healing Salve',
  pclr: 'Clarity Potion',
  plcl: 'Lesser Clarity Potion',
  rej1: 'Minor Replenishment Potion',
  rej2: 'Lesser Replenishment Potion',
  rej3: 'Replenishment Potion',
  rej4: 'Greater Replenishment Potion',
  rej5: 'Lesser Scroll of Replenishment',
  rej6: 'Greater Scroll of Replenishment',
  stwp: 'Scroll of Town Portal',
  shea: 'Scroll of Healing',
  sman: 'Scroll of Mana',
  spro: 'Scroll of Protection',
  sres: 'Scroll of Restoration',
  shas: 'Scroll of Speed',
  sreg: 'Scroll of Regeneration',
  sand: 'Scroll of Animate Dead',
  srrc: 'Scroll of Resurrection',
  sror: 'Scroll of the Beast',
  scul: 'Scroll of the Unholy Legion',
  guvi: 'Glyph of Ultravision',
  gfor: 'Glyph of Fortification',
  gopr: 'Glyph of Purification',
  gomn: 'Glyph of Omniscience',
  bspd: 'Boots of Speed',
  rde0: 'Ring of Protection +1',
  rde1: 'Ring of Protection +2',
  rde2: 'Ring of Protection +3',
  rde3: 'Ring of Protection +4',
  rde4: 'Ring of Protection +5',
  rat3: 'Claws of Attack +3',
  rat6: 'Claws of Attack +6',
  rat9: 'Claws of Attack +9',
  ratc: 'Claws of Attack +12',
  ratf: 'Claws of Attack +15',
  rag1: 'Slippers of Agility +3',
  rin1: 'Mantle of Intelligence +3',
  rst1: 'Gauntlets of Ogre Strength +3',
  ckng: 'Crown of Kings +5',
  belv: "Boots of Quel'Thalas +6",
  bgst: 'Belt of Giant Strength +6',
  ciri: 'Robe of the Magi +6',
  cnob: 'Circlet of Nobility',
  rlif: 'Ring of Regeneration',
  gcel: 'Gloves of Haste',
  evtl: 'Talisman of Evasion',
  prvt: 'Periapt of Vitality',
  manh: 'Manual of Health',
  pmna: 'Pendant of Mana',
  penr: 'Pendant of Energy',
  rhth: "Khadgar's Gem of Health",
  rwiz: 'Sobi Mask',
  crys: 'Crystal Ball',
  gemt: 'Gem of True Seeing',
  clsd: 'Cloak of Shadows',
  clfm: 'Cloak of Flames',
  nspi: 'Necklace of Spell Immunity',
  hcun: 'Hood of Cunning',
  mcou: 'Medallion of Courage',
  hval: 'Helm of Valor',
  ofir: 'Orb of Fire',
  ofro: 'Orb of Frost',
  olig: 'Orb of Lightning',
  oli2: 'Orb of Lightning',
  oven: 'Orb of Venom',
  odef: 'Orb of Darkness',
  ocor: 'Orb of Corruption',
  oslo: 'Orb of Slow',
  modt: 'Mask of Death',
  amrc: 'Amulet of Recall',
  ankh: 'Ankh of Reincarnation',
  desc: "Kelen's Dagger of Escape",
  lhst: 'The Lion Horn of Stormwind',
  afac: "Alleria's Flute of Accuracy",
  ajen: 'Ancient Janggo of Endurance',
  lgdh: 'Legion Doom-Horn',
  sfog: 'Horn of the Clouds',
  ward: 'Warsong Battle Drums',
  gsou: 'Soul Gem',
  tdex: 'Tome of Agility',
  tint: 'Tome of Intelligence',
  tstr: 'Tome of Strength',
  tkno: 'Tome of Power',
  texp: 'Tome of Experience',
  tgxp: 'Tome of Greater Experience',
  tst2: 'Tome of Strength +2',
  tin2: 'Tome of Intelligence +2',
  tdx2: 'Tome of Agility +2',
  tpow: 'Tome of Knowledge',
  tret: 'Tome of Retraining',
  will: 'Wand of Illusion',
  wneg: 'Wand of Negation',
  wneu: 'Wand of Neutralization',
  wlsd: 'Wand of Lightning Shield',
  wcyc: 'Wand of the Wind',
  rnec: 'Rod of Necromancy',
  ssil: 'Staff of Silence',
  kpin: "Khadgar's Pipe of Insight",
  sneg: 'Staff of Negation',
  stel: 'Staff of Teleportation',
  spre: 'Staff of Preservation',
  ssan: 'Staff of Sanctuary',
  wswd: 'Sentry Wards',
  whwd: 'Healing Wards',
  gobm: 'Goblin Land Mines',
  tels: 'Goblin Night Scope',
  dust: 'Dust of Appearance',
}

export const UPGRADE_NAMES: Record<string, string> = {
  Rhme: 'Iron Forged Swords',
  Rhan: 'Animal War Training',
  Rhar: 'Iron Plating',
  Rhla: 'Studded Leather Armor',
  Rhlh: 'Improved Lumber Harvesting',
  Rhac: 'Improved Masonry',
  Rhde: 'Defend',
  Rhfc: 'Flak Cannons',
  Rhfl: 'Flare',
  Rhfs: 'Fragmentation Shards',
  Rhgb: 'Flying Machine Bombs',
  Rhhb: 'Storm Hammers',
  Rhpm: 'Backpack',
  Rhpt: 'Priest Adept Training',
  Rhra: 'Black Gunpowder',
  Rhri: 'Long Rifles',
  Rhrt: 'Barrage',
  Rhsb: 'Sundering Blades',
  Rhse: 'Magic Sentry',
  Rhss: 'Spell Steal',
  Rhst: 'Sorceress Adept Training',
  Rhcd: 'Cloud',
  Roar: 'Steel Armor',
  Robf: 'Burning Oil',
  Robk: 'Berserker Upgrade',
  Robs: 'Brute Strength',
  Roen: 'Ensnare',
  Rolf: 'Liquid Fire',
  Rome: 'Steel Melee Weapons',
  Ropg: 'Pillage',
  Ropm: 'Backpack',
  Rora: 'Orc Ranged Attack',
  Rorb: 'Reinforced Defenses',
  Rosp: 'Spiked Barricades',
  Rost: 'Shaman Adept Training',
  Rotr: 'Troll Regeneration',
  Rovs: 'Envenomed Spears',
  Rowd: 'Witch Doctor Adept Training',
  Rows: 'Pulverize',
  Rowt: 'Sprit Walker Adept Training',
  Ruac: 'Cannibalism',
  Ruar: 'Unholy Armor',
  Ruba: 'Banshee Adept Training',
  Rubu: 'Burrow',
  Rucr: 'Creature Carapace',
  Ruex: 'Exhume Corpses',
  Rufb: 'Freezing Breath',
  Rugf: 'Ghoul Frenzy',
  Rume: 'Unholy Strength',
  Rune: 'Necromancer Adept Training',
  Rupc: 'Disease Cloud',
  Rupm: 'Backpack',
  Rura: 'Creature Attack',
  Rusf: 'Stone Form',
  Rusm: 'Skeletal Mastery',
  Rusp: 'Destroyer Form',
  Ruwb: 'Web',
  Recb: 'Corrosive Breath',
  Redc: 'Druid of the Claw Adept Training',
  Redt: 'Druid of the Talon Adept Training',
  Reeb: 'Mark of the Claw',
  Reec: 'Mark of the Talon',
  Rehs: 'Hardened Skin',
  Reib: 'Improved Bows',
  Rema: 'Moon Armor',
  Remg: 'Upgrade Moon Glaive',
  Remk: 'Marksmanship',
  Renb: "Nature's Blessing",
  Repb: 'Vorpal Blades',
  Repm: 'Backpack',
  Rerh: 'Reinforced Hides',
  Rers: 'Resistant Skin',
  Resc: 'Sentinel',
  Resi: 'Abolish Magic',
  Resm: 'Strength of the Moon',
  Resw: 'Strength of the Wild',
  Reuv: 'Ultravision',
  Rews: 'Well Spring',
  Rwdm: 'War Drums Damage Increase',
}
