import type { UnitData } from './balance.js'

export const UNITS: Record<string, UnitData> = {
  Hamg: { name: 'HeroArchMage', supply: 5, gold: 400, lumber: 100 },
  Hblm: { name: 'HeroBloodMage', supply: 5, gold: 400, lumber: 100 },
  Hmkg: { name: 'HeroMountainKing', supply: 5, gold: 400, lumber: 100 },
  Hpal: { name: 'HeroPaladin', supply: 5, gold: 400, lumber: 100 },
  hbot: { name: 'transport ship', supply: 0, gold: 170, lumber: 50 },
  hbsh: { name: 'human battleship', supply: 0, gold: 500, lumber: 200 },
  hdes: { name: 'human frigate', supply: 0, gold: 250, lumber: 100 },
  hdhw: { name: 'blood elf dragon hawk', supply: 3, gold: 200, lumber: 30 },
  hfoo: { name: 'Footman', supply: 2, gold: 135, lumber: 0 },
  hgry: { name: 'GryphonRider', supply: 4, gold: 280, lumber: 70 },
  hgyr: { name: 'Flying Machine', supply: 1, gold: 100, lumber: 30 },
  hkni: { name: 'Knight', supply: 4, gold: 245, lumber: 60 },
  hmil: { name: 'Militia', supply: 1, gold: 75, lumber: 0 },
  hmpr: { name: 'Priest', supply: 2, gold: 135, lumber: 10 },
  hmtm: { name: 'MortarTeam', supply: 3, gold: 180, lumber: 70 },
  hmtt: { name: 'Siege Engine', supply: 4, gold: 195, lumber: 60 },
  hpea: { name: 'Peasant', supply: 1, gold: 75, lumber: 0 },
  hphx: { name: 'Phoenix', supply: 0, gold: 0, lumber: 0 },
  hpxe: { name: 'Phoenix Egg', supply: 0, gold: 0, lumber: 0 },
  hrif: { name: 'Rifleman', supply: 3, gold: 205, lumber: 30 },
  hrtt: { name: 'siege engine upgraded', supply: 4, gold: 195, lumber: 60 },
  hsor: { name: 'Sorceress', supply: 2, gold: 155, lumber: 20 },
  hspt: { name: 'Blood Elf Spell Breaker', supply: 3, gold: 215, lumber: 30 },
  hwat: { name: 'WaterElemental', supply: 0, gold: 0, lumber: 0 },
  hwt2: { name: 'WaterElemental level 2', supply: 0, gold: 0, lumber: 0 },
  hwt3: { name: 'WaterElemental level 3', supply: 0, gold: 0, lumber: 0 },
  nlv1: { name: 'LavaSpawn', supply: 0, gold: 0, lumber: 0 },
  nlv2: { name: 'LavaSpawn2', supply: 0, gold: 0, lumber: 0 },
  nlv3: { name: 'LavaSpawn3', supply: 0, gold: 0, lumber: 0 },
  halt: { name: 'AltarofKings', supply: 0, gold: 180, lumber: 50 },
  harm: { name: 'Workshop', supply: 0, gold: 140, lumber: 140 },
  hars: { name: 'ArcaneSanctum', supply: 0, gold: 150, lumber: 140 },
  hatw: { name: 'Arcane Tower', supply: 0, gold: 100, lumber: 70 },
  hbar: { name: 'HumanBarracks', supply: 0, gold: 160, lumber: 60 },
  hbla: { name: 'Blacksmith', supply: 0, gold: 140, lumber: 40 },
  hcas: { name: 'Castle', supply: 0, gold: 1025, lumber: 625 },
  hctw: { name: 'CannonTower', supply: 0, gold: 150, lumber: 120 },
  hgra: { name: 'GryphonAviary', supply: 0, gold: 140, lumber: 150 },
  hgtw: { name: 'GuardTower', supply: 0, gold: 100, lumber: 70 },
  hhou: { name: 'Farm', supply: 0, gold: 80, lumber: 20 },
  hkee: { name: 'Keep', supply: 0, gold: 705, lumber: 415 },
  hlum: { name: 'LumberMill', supply: 0, gold: 120, lumber: 0 },
  hshy: { name: 'human shipyard', supply: 0, gold: 50, lumber: 0 },
  htow: { name: 'TownHall', supply: 0, gold: 385, lumber: 205 },
  hvlt: { name: 'Arcane Vault', supply: 0, gold: 130, lumber: 30 },
  hwtw: { name: 'Scout Tower', supply: 0, gold: 30, lumber: 20 },
  Obla: { name: 'HeroBladeMaster', supply: 5, gold: 400, lumber: 100 },
  Ofar: { name: 'HeroFarSeer', supply: 5, gold: 400, lumber: 100 },
  Oshd: { name: 'HeroShadowHunter', supply: 5, gold: 400, lumber: 100 },
  Otch: { name: 'HeroTaurenChieftain', supply: 5, gold: 400, lumber: 100 },
  ncat: { name: 'Demolisher(Draenei)', supply: 4, gold: 220, lumber: 50 },
  nsw1: { name: 'spirit beast level 1', supply: 0, gold: 0, lumber: 0 },
  nsw2: { name: 'spirit beast level 2', supply: 0, gold: 0, lumber: 0 },
  nsw3: { name: 'spirit beast level 3', supply: 0, gold: 0, lumber: 0 },
  nwad: { name: 'WatcherWard', supply: 0, gold: 0, lumber: 0 },
  obot: { name: 'orcish transport', supply: 0, gold: 170, lumber: 50 },
  ocat: { name: 'Demolisher', supply: 4, gold: 220, lumber: 50 },
  odes: { name: 'orcish destroyer', supply: 0, gold: 250, lumber: 100 },
  odoc: { name: 'WitchDoctor', supply: 2, gold: 145, lumber: 25 },
  oeye: { name: 'SentryWard', supply: 0, gold: 0, lumber: 0 },
  ogru: { name: 'Grunt', supply: 3, gold: 200, lumber: 0 },
  ohun: { name: 'HeadHunter', supply: 2, gold: 140, lumber: 20 },
  ohwd: { name: 'Healing Ward', supply: 0, gold: 0, lumber: 0 },
  okod: { name: 'KodoBeast', supply: 4, gold: 255, lumber: 60 },
  opeo: { name: 'Peon', supply: 1, gold: 75, lumber: 0 },
  orai: { name: 'Raider', supply: 3, gold: 180, lumber: 40 },
  oshm: { name: 'Shaman', supply: 2, gold: 130, lumber: 20 },
  osp1: { name: 'serpent ward 1', supply: 0, gold: 0, lumber: 0 },
  osp2: { name: 'serpent ward 2', supply: 0, gold: 0, lumber: 0 },
  osp3: { name: 'serpent ward 3', supply: 0, gold: 0, lumber: 0 },
  osp4: { name: 'serpent ward 4', supply: 0, gold: 0, lumber: 0 },
  ospm: { name: 'SpiritwalkerMorph', supply: 3, gold: 195, lumber: 35 },
  ospw: { name: 'Spiritwalker', supply: 3, gold: 195, lumber: 35 },
  osw1: { name: 'spirit wolf level 1', supply: 0, gold: 0, lumber: 0 },
  osw2: { name: 'spirit wolf level 2', supply: 0, gold: 0, lumber: 0 },
  osw3: { name: 'spirit wolf level 3', supply: 0, gold: 0, lumber: 0 },
  otau: { name: 'Tauren', supply: 5, gold: 300, lumber: 100 },
  otbk: { name: 'Berserker', supply: 2, gold: 140, lumber: 20 },
  otbr: { name: 'Troll Batrider', supply: 2, gold: 160, lumber: 40 },
  otot: { name: 'StasisTrapward', supply: 0, gold: 0, lumber: 0 },
  owyv: { name: 'Wind Rider', supply: 4, gold: 265, lumber: 40 },
  oalt: { name: 'AltarofStorms', supply: 0, gold: 180, lumber: 50 },
  obar: { name: 'Barracks', supply: 0, gold: 180, lumber: 50 },
  obea: { name: 'Beastiary', supply: 0, gold: 145, lumber: 140 },
  ofor: { name: 'Lumber Forge', supply: 0, gold: 205, lumber: 0 },
  ofrt: { name: 'Fortress', supply: 0, gold: 1025, lumber: 565 },
  ogre: { name: 'GreatHall', supply: 0, gold: 385, lumber: 185 },
  oshy: { name: 'orc shipyard', supply: 0, gold: 50, lumber: 0 },
  osld: { name: 'SpiritLodge', supply: 0, gold: 150, lumber: 135 },
  ostr: { name: 'Stronghold', supply: 0, gold: 700, lumber: 375 },
  otrb: { name: 'OrcBurrow', supply: 0, gold: 160, lumber: 40 },
  otto: { name: 'Tauren Totem', supply: 0, gold: 135, lumber: 155 },
  ovln: { name: 'Voodoo Lounge', supply: 0, gold: 130, lumber: 30 },
  owtw: { name: 'WatchTower', supply: 0, gold: 110, lumber: 80 },
  Edem: { name: 'HeroDemonHunter', supply: 5, gold: 400, lumber: 100 },
  Edmm: { name: 'HeroDemonHunterMorph', supply: 5, gold: 400, lumber: 100 },
  Ekee: { name: 'HeroKeeperoftheGrove', supply: 5, gold: 400, lumber: 100 },
  Emoo: { name: 'HeroMoonPriestess', supply: 5, gold: 400, lumber: 100 },
  Ewar: { name: 'HeroWarden', supply: 5, gold: 400, lumber: 100 },
  earc: { name: 'Archer', supply: 2, gold: 130, lumber: 10 },
  ebal: { name: 'Glaive Thrower', supply: 3, gold: 210, lumber: 65 },
  ebsh: { name: 'night elf battleship', supply: 0, gold: 500, lumber: 200 },
  echm: { name: 'Chimaera', supply: 5, gold: 330, lumber: 70 },
  edcm: { name: 'DruidoftheClawMorph', supply: 4, gold: 255, lumber: 80 },
  edes: { name: 'night elf destroyer', supply: 0, gold: 250, lumber: 100 },
  edoc: { name: 'DruidoftheClaw', supply: 4, gold: 255, lumber: 80 },
  edot: { name: 'DruidoftheTalon', supply: 2, gold: 135, lumber: 20 },
  edry: { name: 'Dryad', supply: 3, gold: 145, lumber: 60 },
  edtm: { name: 'DruidoftheTalonMorph', supply: 2, gold: 135, lumber: 20 },
  efdr: { name: 'faerie dragon', supply: 2, gold: 155, lumber: 25 },
  efon: { name: 'Treant', supply: 0, gold: 0, lumber: 0 },
  ehip: { name: 'Hippogryph', supply: 2, gold: 160, lumber: 20 },
  ehpr: { name: 'Hippogryph Rider', supply: 4, gold: 290, lumber: 30 },
  emtg: { name: 'Mountain Giant', supply: 7, gold: 350, lumber: 100 },
  esen: { name: 'Huntress', supply: 3, gold: 195, lumber: 20 },
  espv: { name: 'spirit of vengeance', supply: 0, gold: 0, lumber: 0 },
  even: { name: 'vengeance', supply: 0, gold: 0, lumber: 0 },
  ewsp: { name: 'Wisp', supply: 1, gold: 60, lumber: 0 },
  eaoe: { name: 'AncientofLore', supply: 0, gold: 155, lumber: 145 },
  eaom: { name: 'AncientofWar', supply: 0, gold: 150, lumber: 60 },
  eaow: { name: 'AncientofWind', supply: 0, gold: 150, lumber: 140 },
  eate: { name: 'AltarofElders', supply: 0, gold: 180, lumber: 50 },
  eden: { name: 'Ancient of Wonders', supply: 0, gold: 90, lumber: 30 },
  edob: { name: 'HuntersHall', supply: 0, gold: 210, lumber: 100 },
  edos: { name: 'ChimaeraRoost', supply: 0, gold: 140, lumber: 190 },
  egol: { name: 'EntangledGoldMine', supply: 0, gold: 0, lumber: 0 },
  emow: { name: 'MoonWell', supply: 0, gold: 180, lumber: 40 },
  eshy: { name: 'nightelf shipyard', supply: 0, gold: 50, lumber: 0 },
  etoa: { name: 'TreeofAges', supply: 0, gold: 660, lumber: 365 },
  etoe: { name: 'TreeofEternity', supply: 0, gold: 990, lumber: 565 },
  etol: { name: 'TreeofLife', supply: 0, gold: 340, lumber: 185 },
  etrp: { name: 'Ancient Protector', supply: 0, gold: 135, lumber: 80 },
  Ucrl: { name: 'HeroCryptLord', supply: 5, gold: 400, lumber: 100 },
  Udea: { name: 'HeroDeathKnight', supply: 5, gold: 400, lumber: 100 },
  Udre: { name: 'HeroDreadLord', supply: 5, gold: 400, lumber: 100 },
  Ulic: { name: 'HeroLich', supply: 5, gold: 400, lumber: 100 },
  uabo: { name: 'Abomination', supply: 4, gold: 240, lumber: 70 },
  uaco: { name: 'Acolyte', supply: 1, gold: 75, lumber: 0 },
  uban: { name: 'Banshee', supply: 2, gold: 155, lumber: 30 },
  ubsp: { name: 'destroyer', supply: 5, gold: 300, lumber: 85 },
  ucrm: { name: 'CryptFiendMorph', supply: 3, gold: 215, lumber: 40 },
  ucry: { name: 'CryptFiend', supply: 3, gold: 215, lumber: 40 },
  ucs1: { name: 'carrion scarab level 1', supply: 0, gold: 0, lumber: 0 },
  ucs2: { name: 'carrion scarab level 2', supply: 0, gold: 0, lumber: 0 },
  ucs3: { name: 'carrion scarab level 3', supply: 0, gold: 0, lumber: 0 },
  ucsB: { name: 'carrion scarab level 2 -burrowed', supply: 0, gold: 0, lumber: 0 },
  ucsC: { name: 'carrion scarab level 3 -burrowed', supply: 0, gold: 0, lumber: 0 },
  ufro: { name: 'FrostWyrm', supply: 7, gold: 385, lumber: 120 },
  ugar: { name: 'Gargoyle', supply: 2, gold: 175, lumber: 30 },
  ugho: { name: 'Ghoul', supply: 2, gold: 120, lumber: 0 },
  ugrm: { name: 'GargoyleMorphed', supply: 2, gold: 185, lumber: 30 },
  uloc: { name: 'locust', supply: 0, gold: 0, lumber: 0 },
  umtw: { name: 'MeatWagon', supply: 4, gold: 230, lumber: 50 },
  unec: { name: 'Necromancer', supply: 2, gold: 145, lumber: 20 },
  uobs: { name: 'Obsidian Statue', supply: 3, gold: 200, lumber: 35 },
  uplg: { name: 'PlagueWard', supply: 0, gold: 0, lumber: 0 },
  ushd: { name: 'Shade', supply: 1, gold: 0, lumber: 0 },
  uske: { name: 'SkeletonWarrior', supply: 0, gold: 0, lumber: 0 },
  uskm: { name: 'Skeletal Mage', supply: 0, gold: 0, lumber: 0 },
  uubs: { name: 'undead battleship', supply: 0, gold: 500, lumber: 200 },
  uaod: { name: 'AltarofDarkness', supply: 0, gold: 180, lumber: 50 },
  ubon: { name: 'Boneyard', supply: 0, gold: 150, lumber: 200 },
  ugol: { name: 'Haunted Mine', supply: 0, gold: 225, lumber: 210 },
  ugrv: { name: 'Graveyard', supply: 0, gold: 215, lumber: 0 },
  unp1: { name: 'Halls of the Dead', supply: 0, gold: 545, lumber: 210 },
  unp2: { name: 'Black Citadel', supply: 0, gold: 870, lumber: 440 },
  unpl: { name: 'Necropolis', supply: 0, gold: 225, lumber: 0 },
  usap: { name: 'SacrificialPit', supply: 0, gold: 75, lumber: 150 },
  usep: { name: 'Crypt', supply: 0, gold: 200, lumber: 50 },
  ushp: { name: 'undead shipyard', supply: 0, gold: 50, lumber: 0 },
  uslh: { name: 'Slaughterhouse', supply: 0, gold: 140, lumber: 135 },
  utod: { name: 'TempleoftheDamned', supply: 0, gold: 155, lumber: 140 },
  utom: { name: 'Tomb of Relics', supply: 0, gold: 130, lumber: 30 },
  uzg1: { name: 'Spirit Tower', supply: 0, gold: 295, lumber: 90 },
  uzg2: { name: 'Frost Tower', supply: 0, gold: 250, lumber: 70 },
  uzig: { name: 'Ziggurat', supply: 0, gold: 150, lumber: 50 },
  Nal2: { name: 'HeroAlchemistMorph2', supply: 5, gold: 425, lumber: 135 },
  Nal3: { name: 'HeroAlchemistMorph3', supply: 5, gold: 425, lumber: 135 },
  Nalc: { name: 'HeroAlchemist', supply: 5, gold: 425, lumber: 135 },
  Nalm: { name: 'HeroAlchemistMorph', supply: 5, gold: 425, lumber: 135 },
  Nbrn: { name: 'HeroBansheeRanger', supply: 5, gold: 425, lumber: 135 },
  Nbst: { name: 'Beastmaster', supply: 5, gold: 425, lumber: 135 },
  Nfir: { name: 'FireLord', supply: 5, gold: 425, lumber: 135 },
  Nngs: { name: 'HeroNagaSeaWitch', supply: 5, gold: 425, lumber: 135 },
  Npbm: { name: 'HeroPandarenBrewmaster', supply: 5, gold: 425, lumber: 135 },
  Nplh: { name: 'neutral pit lord', supply: 5, gold: 425, lumber: 135 },
  Nrob: { name: 'HeroTinkerMorph', supply: 5, gold: 425, lumber: 135 },
  Ntin: { name: 'HeroTinker', supply: 5, gold: 425, lumber: 135 },
  ncg1: { name: 'Clockwerk Goblin (lvl 2)', supply: 0, gold: 0, lumber: 0 },
  ncg2: { name: 'Clockwerk Goblin (lvl 3)', supply: 0, gold: 0, lumber: 0 },
  ncg3: { name: 'Clockwerk Goblin (lvl 4)', supply: 0, gold: 0, lumber: 0 },
  ncgb: { name: 'Clockwerk Goblin (lvl 1)', supply: 0, gold: 0, lumber: 0 },
  ndr1: { name: 'DarkMinion1', supply: 0, gold: 0, lumber: 0 },
  ndr2: { name: 'DarkMinion2', supply: 0, gold: 0, lumber: 0 },
  ndr3: { name: 'DarkMinion3', supply: 0, gold: 0, lumber: 0 },
  nfac: { name: 'pocket factory', supply: 0, gold: 0, lumber: 0 },
  nfa1: { name: 'pocket factory', supply: 0, gold: 0, lumber: 0 },
  nfa2: { name: 'pocket factory', supply: 0, gold: 0, lumber: 0 },
  ngz1: { name: 'grizzly bear 1', supply: 0, gold: 0, lumber: 0 },
  ngz2: { name: 'grizzly bear 2', supply: 0, gold: 0, lumber: 0 },
  ngz3: { name: 'grizzly bear 3', supply: 0, gold: 0, lumber: 0 },
  ngz4: { name: 'misha 4', supply: 0, gold: 0, lumber: 0 },
  ngzc: { name: 'misha 1', supply: 0, gold: 0, lumber: 0 },
  ngzd: { name: 'misha 2', supply: 0, gold: 0, lumber: 0 },
  npn1: { name: 'Fire pandaren split', supply: 0, gold: 0, lumber: 0 },
  npn2: { name: 'Wind pandaren split', supply: 0, gold: 0, lumber: 0 },
  npn3: { name: 'Earth pandaren split', supply: 0, gold: 0, lumber: 0 },
  npn4: { name: 'Fire pandaren split2', supply: 0, gold: 0, lumber: 0 },
  npn5: { name: 'Wind pandaren split2', supply: 0, gold: 0, lumber: 0 },
  npn6: { name: 'Earth pandaren split2', supply: 0, gold: 0, lumber: 0 },
  nqb1: { name: 'quillbeast 1', supply: 0, gold: 0, lumber: 0 },
  nqb2: { name: 'quillbeast 2', supply: 0, gold: 0, lumber: 0 },
  nqb3: { name: 'quillbeast 3', supply: 0, gold: 0, lumber: 0 },
  nqb4: { name: 'quillbeast 4', supply: 0, gold: 0, lumber: 0 },
  nwe1: { name: 'war eagle 1', supply: 0, gold: 0, lumber: 0 },
  nwe2: { name: 'war eagle 2', supply: 0, gold: 0, lumber: 0 },
  nwe3: { name: 'war eagle 3', supply: 0, gold: 0, lumber: 0 },
  nadk: { name: 'blue drake', supply: 5, gold: 365, lumber: 80 },
  nadr: { name: 'blue dragon', supply: 8, gold: 745, lumber: 200 },
  nadw: { name: 'blue dragon whelp', supply: 2, gold: 215, lumber: 20 },
  nahy: { name: 'ancient hydra', supply: 8, gold: 745, lumber: 200 },
  nanb: { name: 'barbed arachnathid', supply: 1, gold: 95, lumber: 5 },
  nanc: { name: 'crystal arachnathid', supply: 1, gold: 105, lumber: 0 },
  nane: { name: 'arachanthid earth-borer', supply: 3, gold: 150, lumber: 10 },
  nanm: { name: 'barbed arachnathid(merc)', supply: 1, gold: 95, lumber: 5 },
  nano: { name: 'arachnathid overlord', supply: 4, gold: 255, lumber: 30 },
  nanw: { name: 'arachnathid warrior', supply: 2, gold: 215, lumber: 20 },
  narg: { name: 'battle golem', supply: 2, gold: 195, lumber: 10 },
  nass: { name: 'assassin', supply: 3, gold: 260, lumber: 30 },
  nba2: { name: 'doom guard (summoned)', supply: 6, gold: 480, lumber: 120 },
  nbal: { name: 'doom guard', supply: 6, gold: 480, lumber: 120 },
  nban: { name: 'bandit', supply: 1, gold: 105, lumber: 0 },
  nbda: { name: 'blue dragonspawn apprentice', supply: 3, gold: 195, lumber: 10 },
  nbdk: { name: 'black drake', supply: 5, gold: 365, lumber: 80 },
  nbdm: { name: 'blue dragonspawn meddler', supply: 2, gold: 145, lumber: 0 },
  nbdo: { name: 'blue dragonspawn overseer', supply: 6, gold: 480, lumber: 120 },
  nbdr: { name: 'black dragon whelp', supply: 2, gold: 215, lumber: 20 },
  nbds: { name: 'blue dragonspawn sorceror', supply: 5, gold: 365, lumber: 80 },
  nbdw: { name: 'blue dragonspawn warrior', supply: 4, gold: 300, lumber: 0 },
  nbld: { name: 'bandit lord', supply: 6, gold: 425, lumber: 100 },
  nbnb: { name: 'barbed arachnathid burrowed', supply: 1, gold: 95, lumber: 5 },
  nbot: { name: 'transport ship', supply: 0, gold: 170, lumber: 50 },
  nbrg: { name: 'brigand', supply: 2, gold: 150, lumber: 10 },
  nbwm: { name: 'black dragon', supply: 8, gold: 745, lumber: 200 },
  nbzd: { name: 'bronze dragon', supply: 8, gold: 745, lumber: 200 },
  nbzk: { name: 'bronze drake', supply: 5, gold: 365, lumber: 80 },
  nbzw: { name: 'bronze dragon whelp', supply: 2, gold: 215, lumber: 20 },
  ncea: { name: 'CentaurArcher', supply: 2, gold: 150, lumber: 10 },
  ncen: { name: 'Centaur outrunner', supply: 3, gold: 195, lumber: 0 },
  ncer: { name: 'centaur drudge', supply: 2, gold: 150, lumber: 10 },
  ncfs: { name: 'watery minion cliffrunner', supply: 1, gold: 105, lumber: 0 },
  nchp: { name: 'Chaplain', supply: 2, gold: 135, lumber: 10 },
  ncim: { name: 'Centaur impaler', supply: 3, gold: 255, lumber: 30 },
  ncks: { name: 'centaur sorceror', supply: 4, gold: 320, lumber: 50 },
  ncnk: { name: 'centaur khan', supply: 6, gold: 480, lumber: 120 },
  ndqn: { name: 'succubus', supply: 3, gold: 225, lumber: 40 },
  ndqp: { name: 'maiden of pain', supply: 3, gold: 480, lumber: 120 },
  ndqs: { name: 'queen of suffering', supply: 3, gold: 225, lumber: 40 },
  ndqt: { name: 'vile temptress', supply: 3, gold: 225, lumber: 40 },
  ndqv: { name: 'vile tormentor', supply: 3, gold: 225, lumber: 40 },
  ndrv: { name: 'revenant of the depths', supply: 6, gold: 425, lumber: 100 },
  ndtb: { name: 'dark troll berserker', supply: 3, gold: 245, lumber: 30 },
  ndth: { name: 'dark troll high priest', supply: 3, gold: 255, lumber: 30 },
  ndtp: { name: 'dark troll shadow priest', supply: 2, gold: 175, lumber: 10 },
  ndtr: { name: 'darkTroll', supply: 2, gold: 150, lumber: 10 },
  ndtt: { name: 'darkTrollTrapper', supply: 2, gold: 215, lumber: 20 },
  ndtw: { name: 'darkTrollwarlord', supply: 5, gold: 365, lumber: 80 },
  nehy: { name: 'elder hydra', supply: 6, gold: 255, lumber: 30 },
  nelb: { name: 'berserk elemental', supply: 6, gold: 480, lumber: 120 },
  nele: { name: 'enraged elemental', supply: 3, gold: 255, lumber: 30 },
  nenc: { name: 'corrupted treant', supply: 1, gold: 105, lumber: 0 },
  nenf: { name: 'enforcer', supply: 4, gold: 215, lumber: 20 },
  nenp: { name: 'poison treant', supply: 2, gold: 215, lumber: 20 },
  nepl: { name: 'plague treant', supply: 4, gold: 320, lumber: 50 },
  nerd: { name: 'eredar diabolist', supply: 1, gold: 105, lumber: 0 },
  ners: { name: 'eredar sorceror', supply: 1, gold: 105, lumber: 0 },
  nerw: { name: 'eredar warlock', supply: 1, gold: 545, lumber: 150 },
  nfel: { name: 'fel stalker', supply: 4, gold: 320, lumber: 50 },
  nfgb: { name: 'bloodfiend (felguard)', supply: 2, gold: 240, lumber: 0 },
  nfgo: { name: 'Forgotten One', supply: 10, gold: 745, lumber: 250 },
  nfgt: { name: 'forgotten one tentacle', supply: 0, gold: 0, lumber: 0 },
  nfgu: { name: 'felguard', supply: 2, gold: 170, lumber: 0 },
  nfod: { name: 'faceless one deathbringer', supply: 8, gold: 745, lumber: 200 },
  nfor: { name: 'faceless one trickster', supply: 5, gold: 255, lumber: 30 },
  nfot: { name: 'faceless one terror', supply: 6, gold: 480, lumber: 120 },
  nfov: { name: 'overlord (felguard)', supply: 2, gold: 170, lumber: 0 },
  nfpc: { name: 'Polar Furbolg Champion', supply: 6, gold: 425, lumber: 100 },
  nfpe: { name: 'Polar Furbolg Elder Shaman', supply: 6, gold: 480, lumber: 120 },
  nfpl: { name: 'Polar Furbolg', supply: 3, gold: 255, lumber: 30 },
  nfps: { name: 'Polar Furbolg Shaman', supply: 3, gold: 275, lumber: 30 },
  nfpt: { name: 'Polar Furbolg Tracker', supply: 5, gold: 365, lumber: 80 },
  nfpu: { name: 'Polar Furbolg Ursa Warrior', supply: 8, gold: 480, lumber: 120 },
  nfra: { name: 'Furbolg Ursa Warrior', supply: 6, gold: 480, lumber: 120 },
  nfrb: { name: 'Furbolg Tracker', supply: 5, gold: 365, lumber: 80 },
  nfre: { name: 'Furbolg Elder Shaman', supply: 6, gold: 425, lumber: 100 },
  nfrg: { name: 'Furbolg Champion', supply: 6, gold: 425, lumber: 100 },
  nfrl: { name: 'Furbolg', supply: 3, gold: 255, lumber: 30 },
  nfrp: { name: 'Furbolg Panda', supply: 3, gold: 255, lumber: 30 },
  nfrs: { name: 'Furbolg Shaman', supply: 3, gold: 255, lumber: 30 },
  nfsh: { name: 'forest troll high priest', supply: 4, gold: 305, lumber: 40 },
  nfsp: { name: 'forest troll shadow priest', supply: 2, gold: 195, lumber: 10 },
  nftb: { name: 'forest troll berserker', supply: 3, gold: 245, lumber: 30 },
  nftk: { name: 'Forest Troll Warlord', supply: 5, gold: 365, lumber: 80 },
  nftr: { name: 'ForestTroll', supply: 2, gold: 150, lumber: 10 },
  nftt: { name: 'ForestTrollTrapper', supply: 2, gold: 215, lumber: 20 },
  ngdk: { name: 'Green Drake', supply: 5, gold: 365, lumber: 80 },
  nggr: { name: 'granite golem', supply: 8, gold: 545, lumber: 150 },
  ngh1: { name: 'ghost', supply: 2, gold: 215, lumber: 20 },
  ngh2: { name: 'wraith', supply: 5, gold: 365, lumber: 80 },
  ngir: { name: 'goblin shredder', supply: 4, gold: 375, lumber: 100 },
  nglm: { name: 'goblin land mine', supply: 0, gold: 0, lumber: 0 },
  ngna: { name: 'Gnoll Poacher', supply: 1, gold: 105, lumber: 0 },
  ngnb: { name: 'gnoll brute', supply: 2, gold: 140, lumber: 0 },
  ngno: { name: 'Gnoll Robber', supply: 1, gold: 105, lumber: 0 },
  ngns: { name: 'Gnoll Assassin', supply: 2, gold: 215, lumber: 20 },
  ngnv: { name: 'Gnoll Overseer', supply: 4, gold: 305, lumber: 35 },
  ngnw: { name: 'gnoll warden', supply: 2, gold: 180, lumber: 20 },
  ngrd: { name: 'green dragon', supply: 8, gold: 745, lumber: 200 },
  ngrk: { name: 'mud golem', supply: 2, gold: 145, lumber: 10 },
  ngrw: { name: 'Green Dragon Whelp', supply: 2, gold: 215, lumber: 20 },
  ngsp: { name: 'GoblinSapper', supply: 2, gold: 215, lumber: 100 },
  ngst: { name: 'rock golem', supply: 5, gold: 365, lumber: 80 },
  ngza: { name: 'misha 3', supply: 0, gold: 0, lumber: 0 },
  nhar: { name: 'Harpy Scout', supply: 1, gold: 150, lumber: 0 },
  nhdc: { name: 'deceiver', supply: 2, gold: 215, lumber: 20 },
  nhfp: { name: 'fallen priest', supply: 1, gold: 105, lumber: 0 },
  nhhr: { name: 'heretic', supply: 4, gold: 320, lumber: 50 },
  nhrh: { name: 'harpy hag', supply: 4, gold: 320, lumber: 50 },
  nhrq: { name: 'harpy queen', supply: 6, gold: 365, lumber: 80 },
  nhrr: { name: 'harpy rogue', supply: 2, gold: 215, lumber: 20 },
  nhrw: { name: 'harpy witch', supply: 2, gold: 240, lumber: 30 },
  nhyc: { name: 'Naga Dragon Turtle', supply: 5, gold: 320, lumber: 65 },
  nhyd: { name: 'hydra', supply: 5, gold: 255, lumber: 30 },
  nhyh: { name: 'hydra hatchling', supply: 2, gold: 255, lumber: 30 },
  nhym: { name: 'hydromancer', supply: 2, gold: 155, lumber: 20 },
  nina: { name: 'infernal automaton', supply: 4, gold: 275, lumber: 50 },
  ninc: { name: 'infernal contraption', supply: 4, gold: 275, lumber: 50 },
  ninf: { name: 'Infernal', supply: 6, gold: 480, lumber: 120 },
  ninm: { name: 'infernal machine', supply: 4, gold: 275, lumber: 50 },
  nith: { name: 'ice troll high priest', supply: 3, gold: 255, lumber: 30 },
  nitp: { name: 'ice troll priest', supply: 2, gold: 175, lumber: 10 },
  nitr: { name: 'IceTroll', supply: 2, gold: 150, lumber: 10 },
  nits: { name: 'ice troll berserker', supply: 3, gold: 245, lumber: 30 },
  nitt: { name: 'ice troll trapper', supply: 2, gold: 200, lumber: 20 },
  nitw: { name: 'ice troll warlord', supply: 5, gold: 365, lumber: 80 },
  njg1: { name: 'Jungle Stalker', supply: 2, gold: 215, lumber: 20 },
  njga: { name: 'Elder Jungle Stalker', supply: 5, gold: 375, lumber: 0 },
  njgb: { name: 'Enranged Jungle Stalker', supply: 8, gold: 545, lumber: 150 },
  nkob: { name: 'Kobold', supply: 1, gold: 90, lumber: 0 },
  nkog: { name: 'Kobold Geomancer', supply: 2, gold: 215, lumber: 30 },
  nkol: { name: 'kobold taskmaster', supply: 4, gold: 320, lumber: 50 },
  nkot: { name: 'kobold tunneler', supply: 2, gold: 150, lumber: 0 },
  nlds: { name: 'makrura deep seer', supply: 4, gold: 500, lumber: 100 },
  nlkl: { name: 'makrura tidal lord', supply: 6, gold: 105, lumber: 0 },
  nlpd: { name: 'makrura pool dweller', supply: 2, gold: 105, lumber: 0 },
  nlpr: { name: 'makrura prawn', supply: 1, gold: 105, lumber: 0 },
  nlps: { name: 'makrura prawn summoned', supply: 1, gold: 105, lumber: 0 },
  nlrv: { name: 'deeplord revenant', supply: 8, gold: 745, lumber: 200 },
  nlsn: { name: 'makrura snapper', supply: 4, gold: 315, lumber: 0 },
  nltc: { name: 'makrura tide caller', supply: 2, gold: 105, lumber: 0 },
  nltl: { name: 'lightning lizard', supply: 2, gold: 195, lumber: 10 },
  nlur: { name: 'Monster Lure ward', supply: 0, gold: 0, lumber: 0 },
  nmam: { name: 'Mammoth', supply: 2, gold: 255, lumber: 30 },
  nmbg: { name: "mur'gul blood-gill", supply: 2, gold: 195, lumber: 10 },
  nmcf: { name: "mur'gul cliffrunner", supply: 1, gold: 105, lumber: 0 },
  nmdr: { name: 'Dire Mammoth', supply: 6, gold: 480, lumber: 120 },
  nmfs: { name: 'murloc flesheater', supply: 2, gold: 140, lumber: 0 },
  nmgd: { name: 'magnataur destroyer', supply: 8, gold: 745, lumber: 200 },
  nmgr: { name: 'magnataur reaver', supply: 6, gold: 255, lumber: 30 },
  nmgw: { name: 'magnataur warrior', supply: 4, gold: 340, lumber: 15 },
  nmit: { name: 'Icetusk Mammoth', supply: 4, gold: 255, lumber: 30 },
  nmmu: { name: 'murloc mutant', supply: 5, gold: 365, lumber: 80 },
  nmpg: { name: 'murloc plaguebearer', supply: 2, gold: 105, lumber: 0 },
  nmrl: { name: 'murloc tiderunner', supply: 1, gold: 105, lumber: 0 },
  nmrm: { name: 'murloc nightcrawler', supply: 2, gold: 215, lumber: 20 },
  nmrr: { name: 'murloc huntsman', supply: 2, gold: 150, lumber: 10 },
  nmrv: { name: "mur'gul reaver", supply: 5, gold: 105, lumber: 0 },
  nmsc: { name: "mur'gul shadowcaster", supply: 6, gold: 105, lumber: 0 },
  nmsn: { name: "mur'gul snarecaster", supply: 3, gold: 265, lumber: 30 },
  nmtw: { name: "mur'gul tidewarrior", supply: 2, gold: 105, lumber: 0 },
  nmyr: { name: 'naga myrmidon', supply: 4, gold: 225, lumber: 55 },
  nmys: { name: 'naga myrmidon submerged', supply: 4, gold: 225, lumber: 55 },
  nndk: { name: 'nether drake', supply: 5, gold: 365, lumber: 80 },
  nndr: { name: 'nether dragon', supply: 8, gold: 745, lumber: 200 },
  nnht: { name: 'nether dragon hatchling', supply: 2, gold: 215, lumber: 20 },
  nnmg: { name: "naga mur'gul reaver", supply: 2, gold: 120, lumber: 0 },
  nnrg: { name: 'naga royal guard', supply: 4, gold: 300, lumber: 100 },
  nnrs: { name: 'naga royal guard submerged', supply: 4, gold: 300, lumber: 100 },
  nnsu: { name: 'naga siren', supply: 2, gold: 130, lumber: 20 },
  nnsw: { name: 'naga siren', supply: 2, gold: 130, lumber: 20 },
  nnwa: { name: 'nerubian warrior', supply: 2, gold: 205, lumber: 0 },
  nnwl: { name: 'nerubian webspinner', supply: 3, gold: 200, lumber: 35 },
  nnwq: { name: 'nerubian queen', supply: 6, gold: 425, lumber: 100 },
  nnwr: { name: 'nerubian seer', supply: 4, gold: 320, lumber: 50 },
  nnws: { name: 'nerubian spider lord', supply: 4, gold: 320, lumber: 50 },
  noga: { name: 'Stonemaul Warchief', supply: 8, gold: 750, lumber: 150 },
  nogl: { name: 'ogre lord', supply: 6, gold: 425, lumber: 100 },
  nogm: { name: 'ogre mauler', supply: 4, gold: 300, lumber: 0 },
  nogn: { name: 'Stonemaul Magi', supply: 5, gold: 450, lumber: 40 },
  nogo: { name: 'Stonemaul Ogre', supply: 5, gold: 375, lumber: 0 },
  nogr: { name: 'Ogre Warrior', supply: 2, gold: 150, lumber: 0 },
  nomg: { name: 'ogre magi', supply: 4, gold: 320, lumber: 50 },
  nowb: { name: 'wildkin', supply: 3, gold: 195, lumber: 0 },
  nowe: { name: 'enraged wildkin', supply: 5, gold: 365, lumber: 80 },
  nowk: { name: 'berserk Wildkin', supply: 6, gold: 480, lumber: 120 },
  npfl: { name: 'Fel Beast', supply: 2, gold: 155, lumber: 0 },
  npfm: { name: 'Fel Ravager', supply: 4, gold: 320, lumber: 50 },
  nplb: { name: 'polar bear', supply: 3, gold: 195, lumber: 0 },
  nplg: { name: 'giant polar bear', supply: 5, gold: 365, lumber: 80 },
  nqbh: { name: 'quillboar hunter', supply: 2, gold: 215, lumber: 20 },
  nrdk: { name: 'Red Dragon Whelp', supply: 2, gold: 215, lumber: 20 },
  nrdr: { name: 'Red Drake', supply: 5, gold: 365, lumber: 80 },
  nrel: { name: 'reef elemental', supply: 2, gold: 170, lumber: 0 },
  nrog: { name: 'rogue', supply: 2, gold: 150, lumber: 0 },
  nrvd: { name: 'death revenant', supply: 8, gold: 545, lumber: 150 },
  nrvf: { name: 'fire revenant', supply: 2, gold: 215, lumber: 20 },
  nrvi: { name: 'ice revenant', supply: 6, gold: 480, lumber: 120 },
  nrvl: { name: 'lightning revenant', supply: 5, gold: 365, lumber: 80 },
  nrvs: { name: 'frost revenant', supply: 3, gold: 255, lumber: 30 },
  nrwm: { name: 'Red Dragon', supply: 8, gold: 745, lumber: 200 },
  nrzb: { name: 'razormane brute', supply: 2, gold: 215, lumber: 20 },
  nrzg: { name: 'razormane chieftain', supply: 6, gold: 425, lumber: 100 },
  nrzm: { name: 'razormane medicine man', supply: 4, gold: 350, lumber: 60 },
  nrzs: { name: 'razormane scout', supply: 1, gold: 105, lumber: 0 },
  nrzt: { name: 'quillboar', supply: 1, gold: 105, lumber: 0 },
  nsat: { name: 'Satyr Trickster', supply: 1, gold: 105, lumber: 0 },
  nsbm: { name: 'brood mother', supply: 5, gold: 365, lumber: 80 },
  nsbs: { name: 'naga snap dragon submerged', supply: 3, gold: 200, lumber: 25 },
  nsc2: { name: 'spider crab 2', supply: 2, gold: 150, lumber: 0 },
  nsc3: { name: 'spider crab 3', supply: 4, gold: 300, lumber: 0 },
  nsca: { name: 'skeletal archer(summoned)', supply: 1, gold: 105, lumber: 0 },
  nscb: { name: 'spider crab', supply: 1, gold: 105, lumber: 0 },
  nsce: { name: 'SkeletonWarrior(summoned)', supply: 1, gold: 105, lumber: 0 },
  nsel: { name: 'sea elemental', supply: 4, gold: 170, lumber: 0 },
  nsgb: { name: 'sea giant behemoth', supply: 6, gold: 265, lumber: 85 },
  nsgg: { name: 'siege golem', supply: 8, gold: 545, lumber: 150 },
  nsgh: { name: 'sea giant hunter', supply: 4, gold: 265, lumber: 85 },
  nsgn: { name: 'sea giant', supply: 2, gold: 265, lumber: 85 },
  nsgt: { name: 'giant spider', supply: 3, gold: 255, lumber: 30 },
  nska: { name: 'skeletal archer', supply: 1, gold: 105, lumber: 0 },
  nske: { name: 'SkeletonWarrior', supply: 1, gold: 105, lumber: 0 },
  nskf: { name: 'burning archer', supply: 2, gold: 225, lumber: 25 },
  nskg: { name: 'giant SkeletonWarrior', supply: 2, gold: 165, lumber: 0 },
  nskm: { name: 'skeletal marksman', supply: 2, gold: 215, lumber: 20 },
  nsko: { name: 'skeletal orc', supply: 2, gold: 90, lumber: 0 },
  nslf: { name: 'sludge flinger', supply: 2, gold: 255, lumber: 30 },
  nslh: { name: 'salamander hatchling', supply: 2, gold: 215, lumber: 20 },
  nsll: { name: 'salamander lord', supply: 8, gold: 745, lumber: 200 },
  nslm: { name: 'sludge minion', supply: 1, gold: 105, lumber: 0 },
  nsln: { name: 'sludge monstrosity', supply: 4, gold: 320, lumber: 50 },
  nslr: { name: 'salamander', supply: 4, gold: 320, lumber: 50 },
  nslv: { name: 'salamander vizier', supply: 6, gold: 425, lumber: 100 },
  nsnp: { name: 'naga snap dragon', supply: 3, gold: 200, lumber: 25 },
  nsns: { name: 'watery minion snarecaster', supply: 3, gold: 320, lumber: 50 },
  nsoc: { name: 'skeletal orc champion', supply: 6, gold: 90, lumber: 0 },
  nsog: { name: 'skeletal orc grunt', supply: 4, gold: 300, lumber: 0 },
  nspb: { name: 'black spider', supply: 1, gold: 105, lumber: 0 },
  nspd: { name: 'spiderling', supply: 1, gold: 105, lumber: 0 },
  nspg: { name: 'green spider', supply: 1, gold: 105, lumber: 0 },
  nspp: { name: 'spirit pig', supply: 2, gold: 0, lumber: 0 },
  nspr: { name: 'spider', supply: 1, gold: 105, lumber: 0 },
  nsqa: { name: 'ancient sasquatch', supply: 8, gold: 545, lumber: 150 },
  nsqe: { name: 'elder sasquatch', supply: 5, gold: 365, lumber: 80 },
  nsqo: { name: 'sasquatch oracle', supply: 6, gold: 425, lumber: 100 },
  nsqt: { name: 'sasquatch', supply: 4, gold: 320, lumber: 50 },
  nsra: { name: 'stormreaver apprentice', supply: 1, gold: 105, lumber: 5 },
  nsrh: { name: 'stormreaver hermit', supply: 2, gold: 190, lumber: 20 },
  nsrn: { name: 'stormreaver necrolyte', supply: 5, gold: 180, lumber: 20 },
  nsrv: { name: 'revenant of the seas', supply: 4, gold: 255, lumber: 30 },
  nsrw: { name: 'stormreaver warlock', supply: 8, gold: 545, lumber: 150 },
  nssp: { name: 'spitting spider', supply: 2, gold: 235, lumber: 30 },
  nsth: { name: 'satyr hellcaller', supply: 8, gold: 480, lumber: 120 },
  nstl: { name: 'satyr soulstealer', supply: 4, gold: 320, lumber: 50 },
  nsts: { name: 'satyr shadowdancer', supply: 2, gold: 200, lumber: 20 },
  nstw: { name: 'storm wyrm', supply: 8, gold: 545, lumber: 150 },
  nsty: { name: 'Satyr', supply: 1, gold: 105, lumber: 0 },
  nthl: { name: 'thunder lizard', supply: 6, gold: 365, lumber: 150 },
  ntka: { name: 'tuskarr spearman', supply: 2, gold: 150, lumber: 10 },
  ntkc: { name: 'tuskarr chieftain', supply: 6, gold: 425, lumber: 100 },
  ntkf: { name: 'tuskarr fighter', supply: 2, gold: 170, lumber: 0 },
  ntkh: { name: 'tuskarr healer', supply: 2, gold: 215, lumber: 10 },
  ntks: { name: 'tuskarr sorceror', supply: 4, gold: 195, lumber: 10 },
  ntkt: { name: 'tuskarr trapper', supply: 3, gold: 280, lumber: 40 },
  ntkw: { name: 'tuskarr warrior', supply: 3, gold: 255, lumber: 30 },
  ntor: { name: 'tornado', supply: 0, gold: 0, lumber: 0 },
  ntrd: { name: 'dragon turtle', supply: 8, gold: 745, lumber: 200 },
  ntrg: { name: 'gargantuan sea turtle', supply: 6, gold: 255, lumber: 30 },
  ntrh: { name: 'sea turtle hatchling', supply: 1, gold: 105, lumber: 0 },
  ntrs: { name: 'sea turtle', supply: 2, gold: 255, lumber: 30 },
  ntrt: { name: 'giant sea turtle', supply: 3, gold: 295, lumber: 35 },
  ntrv: { name: 'revenant of the tides', supply: 2, gold: 255, lumber: 30 },
  ntws: { name: 'watery minion tidewarrior', supply: 2, gold: 105, lumber: 0 },
  nubk: { name: 'unbroken darkhunter', supply: 2, gold: 150, lumber: 10 },
  nubr: { name: 'unbroken rager', supply: 3, gold: 255, lumber: 30 },
  nubw: { name: 'unbroken darkweaver', supply: 4, gold: 320, lumber: 50 },
  nvde: { name: 'elder voidwalker', supply: 4, gold: 545, lumber: 150 },
  nvdg: { name: 'greater voidwalker', supply: 4, gold: 300, lumber: 45 },
  nvdl: { name: 'lesser voidwalker', supply: 1, gold: 105, lumber: 0 },
  nvdw: { name: 'voidwalker', supply: 2, gold: 245, lumber: 30 },
  nwen: { name: 'Wendigo', supply: 3, gold: 255, lumber: 30 },
  nwgs: { name: 'naga coutl', supply: 2, gold: 235, lumber: 30 },
  nwiz: { name: 'apprentice wizard', supply: 1, gold: 105, lumber: 0 },
  nwld: { name: 'dire wolf', supply: 5, gold: 365, lumber: 80 },
  nwlg: { name: 'giant wolf', supply: 3, gold: 215, lumber: 0 },
  nwlt: { name: 'timber wolf', supply: 2, gold: 150, lumber: 10 },
  nwna: { name: 'ancient wendigo', supply: 8, gold: 545, lumber: 150 },
  nwnr: { name: 'elder wendigo', supply: 5, gold: 365, lumber: 80 },
  nwns: { name: 'Wendigo shaman', supply: 6, gold: 425, lumber: 100 },
  nwrg: { name: 'war golem', supply: 5, gold: 365, lumber: 80 },
  nws1: { name: 'dragon hawk', supply: 4, gold: 350, lumber: 70 },
  nwwd: { name: 'white dire wolf', supply: 5, gold: 365, lumber: 80 },
  nwwf: { name: 'white wolf', supply: 2, gold: 150, lumber: 10 },
  nwwg: { name: 'giant white wolf', supply: 3, gold: 255, lumber: 30 },
  nwzd: { name: 'dark wizard', supply: 6, gold: 480, lumber: 120 },
  nwzg: { name: 'renegade wizard', supply: 4, gold: 320, lumber: 50 },
  nwzr: { name: 'rogue wizard', supply: 2, gold: 215, lumber: 20 },
  nzep: { name: 'GoblinZeppelin', supply: 1, gold: 240, lumber: 60 },
  nzom: { name: 'Zombie', supply: 1, gold: 85, lumber: 0 },
  nzof: { name: 'ZombieFemale', supply: 1, gold: 85, lumber: 0 },
  nalb: { name: 'Albatross', supply: 0, gold: 0, lumber: 0 },
  ncrb: { name: 'Crab', supply: 0, gold: 0, lumber: 0 },
  nder: { name: 'deer', supply: 0, gold: 0, lumber: 0 },
  ndog: { name: 'Dog', supply: 0, gold: 0, lumber: 0 },
  ndwm: { name: 'Dune Worm', supply: 0, gold: 0, lumber: 0 },
  nech: { name: 'Chicken', supply: 0, gold: 0, lumber: 0 },
  necr: { name: 'Rabbit', supply: 0, gold: 0, lumber: 0 },
  nfbr: { name: 'Felboar', supply: 0, gold: 0, lumber: 0 },
  nfro: { name: 'Frog', supply: 0, gold: 0, lumber: 0 },
  nhmc: { name: 'Hermit Crab', supply: 0, gold: 0, lumber: 0 },
  now2: { name: 'owl 2', supply: 0, gold: 0, lumber: 0 },
  now3: { name: 'owl 3', supply: 0, gold: 0, lumber: 0 },
  nowl: { name: 'owl', supply: 0, gold: 0, lumber: 0 },
  npig: { name: 'Pig', supply: 0, gold: 0, lumber: 0 },
  npng: { name: 'Penguin', supply: 0, gold: 0, lumber: 0 },
  npnw: { name: 'Penguin, water', supply: 0, gold: 0, lumber: 0 },
  nrac: { name: 'Raccoon', supply: 0, gold: 0, lumber: 0 },
  nrat: { name: 'Rat', supply: 0, gold: 0, lumber: 0 },
  nsea: { name: 'Seal', supply: 0, gold: 0, lumber: 0 },
  nsha: { name: 'Amphibious Sheep', supply: 0, gold: 0, lumber: 0 },
  nshe: { name: 'Sheep', supply: 0, gold: 0, lumber: 0 },
  nshf: { name: 'Flying Sheep', supply: 0, gold: 0, lumber: 0 },
  nshw: { name: 'Sheep of the Water!!!', supply: 0, gold: 0, lumber: 0 },
  nskk: { name: 'Skink', supply: 0, gold: 0, lumber: 0 },
  nsno: { name: 'Snowy Owl', supply: 0, gold: 0, lumber: 0 },
  nvil: { name: 'Villager Man', supply: 0, gold: 0, lumber: 0 },
  nvk2: { name: 'Villager Kid 2', supply: 0, gold: 0, lumber: 0 },
  nvl2: { name: 'Villager Man 2', supply: 0, gold: 0, lumber: 0 },
  nvlk: { name: 'Villager Kid', supply: 0, gold: 0, lumber: 0 },
  nvlw: { name: 'Villager Woman', supply: 0, gold: 0, lumber: 0 },
  nvul: { name: 'Vulture', supply: 0, gold: 0, lumber: 0 },
  ncb0: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb1: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb2: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb3: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb4: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb5: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb6: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb7: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb8: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncb9: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncba: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncbb: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncbc: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncbd: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncbe: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncbf: { name: 'city building', supply: 0, gold: 0, lumber: 0 },
  ncnt: { name: 'Centaur Tent', supply: 0, gold: 0, lumber: 0 },
  ncop: { name: 'circle of power', supply: 0, gold: 0, lumber: 0 },
  ncp2: { name: 'circle of power medium', supply: 0, gold: 0, lumber: 0 },
  ncp3: { name: 'circle of power large', supply: 0, gold: 0, lumber: 0 },
  nct1: { name: 'Centaur Tent', supply: 0, gold: 0, lumber: 0 },
  nct2: { name: 'Centaur Tent', supply: 0, gold: 0, lumber: 0 },
  ndch: { name: 'draenei chieftain hut', supply: 0, gold: 0, lumber: 0 },
  ndh0: { name: 'draenei hut 0', supply: 0, gold: 0, lumber: 0 },
  ndh1: { name: 'draenei hut 1', supply: 0, gold: 0, lumber: 0 },
  ndh2: { name: 'draenei haven', supply: 0, gold: 400, lumber: 195 },
  ndh3: { name: "draenei warrior's hall", supply: 0, gold: 170, lumber: 55 },
  ndh4: { name: "draenei seer's lodge", supply: 0, gold: 100, lumber: 140 },
  ndrg: { name: 'Dragon Roost green', supply: 0, gold: 50, lumber: 0 },
  ndrk: { name: 'Dragon Roost black', supply: 0, gold: 50, lumber: 0 },
  ndro: { name: 'Dragon Roost outland', supply: 0, gold: 50, lumber: 0 },
  ndrr: { name: 'Dragon Roost red', supply: 0, gold: 50, lumber: 0 },
  ndru: { name: 'Dragon Roost blue', supply: 0, gold: 50, lumber: 0 },
  ndrz: { name: 'Dragon Roost bronze', supply: 0, gold: 50, lumber: 0 },
  nfh0: { name: 'Forest Troll Hut 0', supply: 0, gold: 0, lumber: 0 },
  nfh1: { name: 'Forest Troll Hut 1', supply: 0, gold: 0, lumber: 0 },
  nfoh: { name: 'Fountain of Health', supply: 0, gold: 50, lumber: 0 },
  nfr1: { name: 'Furbolg Hut 1', supply: 0, gold: 0, lumber: 0 },
  nfr2: { name: 'Furbolg Hut 2', supply: 0, gold: 0, lumber: 0 },
  ngad: { name: 'Goblin Ammo Dump', supply: 0, gold: 50, lumber: 0 },
  ngme: { name: 'goblin merchant', supply: 0, gold: 50, lumber: 0 },
  ngnh: { name: 'Gnoll Hut', supply: 0, gold: 0, lumber: 0 },
  ngni: { name: 'Infected Granary', supply: 0, gold: 0, lumber: 0 },
  ngol: { name: 'GoldMine', supply: 0, gold: 0, lumber: 0 },
  ngt2: { name: 'Gnoll Hut', supply: 0, gold: 0, lumber: 0 },
  ngwr: { name: 'grain warehouse', supply: 0, gold: 0, lumber: 0 },
  nhns: { name: 'harpy nest', supply: 0, gold: 0, lumber: 0 },
  nmer: { name: 'MercenaryCamp L', supply: 0, gold: 50, lumber: 0 },
  nmg0: { name: "Mur'gul Hut 0", supply: 0, gold: 0, lumber: 0 },
  nmg1: { name: "Mur'gul Hut 1", supply: 0, gold: 0, lumber: 0 },
  nmh0: { name: 'Murloc Hut 0', supply: 0, gold: 0, lumber: 0 },
  nmh1: { name: 'Murloc Hut 1', supply: 0, gold: 0, lumber: 0 },
  nmoo: { name: 'Fountain of Life', supply: 0, gold: 50, lumber: 0 },
  nmr0: { name: 'MercenaryCamp V', supply: 0, gold: 50, lumber: 0 },
  nmr2: { name: 'MercenaryCamp F', supply: 0, gold: 50, lumber: 0 },
  nmr3: { name: 'MercenaryCamp W', supply: 0, gold: 50, lumber: 0 },
  nmr4: { name: 'MercenaryCamp B', supply: 0, gold: 50, lumber: 0 },
  nmr5: { name: 'MercenaryCamp A', supply: 0, gold: 50, lumber: 0 },
  nmr6: { name: 'MercenaryCamp C', supply: 0, gold: 50, lumber: 0 },
  nmr7: { name: 'MercenaryCamp N', supply: 0, gold: 50, lumber: 0 },
  nmr8: { name: 'MercenaryCamp Y', supply: 0, gold: 50, lumber: 0 },
  nmr9: { name: 'MercenaryCamp X', supply: 0, gold: 50, lumber: 0 },
  nmra: { name: 'MercenaryCamp D', supply: 0, gold: 50, lumber: 0 },
  nmrb: { name: 'MercenaryCamp G', supply: 0, gold: 50, lumber: 0 },
  nmrc: { name: 'MercenaryCamp Z', supply: 0, gold: 50, lumber: 0 },
  nmrd: { name: 'MercenaryCamp I', supply: 0, gold: 50, lumber: 0 },
  nmre: { name: 'MercenaryCamp O', supply: 0, gold: 50, lumber: 0 },
  nmrf: { name: 'MercenaryCamp K', supply: 0, gold: 50, lumber: 0 },
  nmrk: { name: 'Marketplace', supply: 0, gold: 50, lumber: 0 },
  nnzg: { name: 'nerubian ziggurat', supply: 0, gold: 0, lumber: 0 },
  nshp: { name: 'Goblin Shipyard', supply: 0, gold: 50, lumber: 0 },
  ntav: { name: 'Tavern', supply: 0, gold: 50, lumber: 0 },
  nten: { name: 'Tent', supply: 0, gold: 0, lumber: 0 },
  nth0: { name: 'Ice Troll Hut 0', supply: 0, gold: 0, lumber: 0 },
  nth1: { name: 'Ice Troll Hut 1', supply: 0, gold: 0, lumber: 0 },
  ntn2: { name: 'Tent', supply: 0, gold: 0, lumber: 0 },
  ntnt: { name: 'Tauren Tent', supply: 0, gold: 0, lumber: 0 },
  ntt2: { name: 'Tauren Tent', supply: 0, gold: 0, lumber: 0 },
  nwgt: { name: 'WayGate', supply: 0, gold: 50, lumber: 0 },
  Ecen: { name: 'cenarius', supply: 0, gold: 425, lumber: 100 },
  Eevi: { name: 'evil illidan', supply: 0, gold: 425, lumber: 100 },
  Eevm: { name: 'evil illidan demon form', supply: 0, gold: 425, lumber: 100 },
  Efur: { name: 'furion', supply: 0, gold: 425, lumber: 0 },
  Eidm: { name: 'illidan demon form', supply: 0, gold: 425, lumber: 100 },
  Eill: { name: 'illidan', supply: 0, gold: 425, lumber: 100 },
  Eilm: { name: 'illidanmorphed', supply: 0, gold: 425, lumber: 100 },
  Ekgg: { name: 'HeroKeeperoftheGrove ghost', supply: 5, gold: 425, lumber: 100 },
  Emfr: { name: "Mal'furion", supply: 0, gold: 425, lumber: 0 },
  Emns: { name: "Mal'furion no stag", supply: 0, gold: 425, lumber: 100 },
  Etyr: { name: 'Tyrande', supply: 0, gold: 425, lumber: 100 },
  Ewrd: { name: 'Maiev', supply: 0, gold: 425, lumber: 100 },
  Hant: { name: 'antonidus', supply: 0, gold: 425, lumber: 100 },
  Hapm: { name: 'Admiral Proudmoore', supply: 0, gold: 425, lumber: 100 },
  Harf: { name: 'arthas w/ frostmourne', supply: 0, gold: 425, lumber: 100 },
  Hart: { name: 'arthas', supply: 0, gold: 425, lumber: 100 },
  Hdgo: { name: 'Dagren the Orcslayer', supply: 0, gold: 425, lumber: 100 },
  Hgam: { name: 'ghostly archmage', supply: 0, gold: 425, lumber: 100 },
  Hhkl: { name: 'Halahk the Lifebringer', supply: 0, gold: 425, lumber: 100 },
  Hjai: { name: 'jaina', supply: 0, gold: 425, lumber: 100 },
  Hkal: { name: 'Kael', supply: 0, gold: 425, lumber: 100 },
  Hlgr: { name: 'Lord Garithos', supply: 0, gold: 425, lumber: 100 },
  Hmbr: { name: 'muradin bronzebeard', supply: 0, gold: 425, lumber: 100 },
  Hmgd: { name: 'Magroth the Defender', supply: 0, gold: 425, lumber: 100 },
  Hpb1: { name: 'Paladin Boss 1', supply: 0, gold: 425, lumber: 100 },
  Hpb2: { name: 'Paladin Boss 2', supply: 0, gold: 425, lumber: 100 },
  Huth: { name: 'uther', supply: 0, gold: 425, lumber: 100 },
  Hvsh: { name: 'Lady Vashj', supply: 0, gold: 425, lumber: 100 },
  Hvwd: { name: 'sylvanus windrunner', supply: 0, gold: 425, lumber: 100 },
  Naka: { name: 'Akama', supply: 5, gold: 425, lumber: 100 },
  Nbbc: { name: 'blackrock blademaster', supply: 0, gold: 425, lumber: 100 },
  Nkjx: { name: 'Kiljaeden - cinematic only', supply: 0, gold: 425, lumber: 100 },
  Nklj: { name: 'Kiljaeden', supply: 0, gold: 425, lumber: 100 },
  Nmag: { name: 'Magtheridon', supply: 0, gold: 425, lumber: 100 },
  Nman: { name: 'mannoroth', supply: 0, gold: 425, lumber: 100 },
  Npld: { name: 'pit lord', supply: 0, gold: 425, lumber: 100 },
  Nsjs: { name: 'Sinjo Stormstout', supply: 0, gold: 425, lumber: 100 },
  Ocb2: { name: 'cairne bloodhoof (war3x)', supply: 0, gold: 425, lumber: 100 },
  Ocbh: { name: 'cairne bloodhoof', supply: 0, gold: 425, lumber: 100 },
  Odrt: { name: "Drek'Thar", supply: 0, gold: 425, lumber: 100 },
  Ogld: { name: "Gul'dan", supply: 0, gold: 425, lumber: 100 },
  Ogrh: { name: 'grom hellscream', supply: 0, gold: 425, lumber: 100 },
  Opgh: { name: 'possessed grom hellscream', supply: 0, gold: 425, lumber: 100 },
  Orex: { name: 'Rexxar', supply: 0, gold: 425, lumber: 100 },
  Orkn: { name: 'Rokhan', supply: 0, gold: 425, lumber: 100 },
  Osam: { name: 'Samuro', supply: 0, gold: 425, lumber: 100 },
  Otcc: { name: 'cairne bloodhoof cinematic', supply: 0, gold: 425, lumber: 100 },
  Othr: { name: 'thrall', supply: 0, gold: 425, lumber: 100 },
  Oths: { name: 'thrall unmounted', supply: 0, gold: 425, lumber: 100 },
  Uanb: { name: "anub'arak", supply: 0, gold: 425, lumber: 100 },
  Ubal: { name: 'balnazzar', supply: 0, gold: 425, lumber: 100 },
  Uclc: { name: 'kelthuzadlich cinematic', supply: 0, gold: 425, lumber: 100 },
  Udth: { name: 'dethecus', supply: 0, gold: 425, lumber: 100 },
  Uear: { name: 'evil arthas', supply: 0, gold: 425, lumber: 100 },
  Uktl: { name: 'kelthuzadlich', supply: 0, gold: 425, lumber: 100 },
  Umal: { name: 'malganis', supply: 0, gold: 425, lumber: 100 },
  Usyl: { name: 'Evil Sylvanas', supply: 0, gold: 425, lumber: 100 },
  Utic: { name: 'tichondrius', supply: 0, gold: 425, lumber: 100 },
  Uvar: { name: 'varimathras', supply: 0, gold: 425, lumber: 100 },
  Uvng: { name: 'vengyr', supply: 0, gold: 425, lumber: 100 },
  Uwar: { name: 'archimonde', supply: 0, gold: 425, lumber: 100 },
  eilw: { name: 'illidan wagon', supply: 0, gold: 195, lumber: 35 },
  enec: { name: 'night elf courier', supply: 0, gold: 0, lumber: 0 },
  ensh: { name: 'Naisha', supply: 3, gold: 195, lumber: 20 },
  eshd: { name: 'shandris', supply: 2, gold: 215, lumber: 20 },
  etrs: { name: 'night elf transport ship', supply: 0, gold: 170, lumber: 50 },
  hbew: { name: 'blood elf wagon', supply: 0, gold: 195, lumber: 35 },
  hcth: { name: 'the captain', supply: 0, gold: 130, lumber: 0 },
  hhdl: { name: 'riderless horse', supply: 0, gold: 240, lumber: 40 },
  hhes: { name: 'high elven swordsman', supply: 2, gold: 135, lumber: 0 },
  hprt: { name: 'portal unit', supply: 0, gold: 0, lumber: 0 },
  hrdh: { name: 'pack horse', supply: 0, gold: 240, lumber: 40 },
  nbee: { name: 'blood elf engineer', supply: 1, gold: 75, lumber: 0 },
  nbel: { name: 'blood elf lieutenant', supply: 2, gold: 155, lumber: 20 },
  nbsp: { name: 'battleship', supply: 0, gold: 0, lumber: 0 },
  nchg: { name: 'chaos grunt', supply: 3, gold: 200, lumber: 0 },
  nchr: { name: 'ChaosWolfRider', supply: 3, gold: 180, lumber: 40 },
  nchw: { name: 'ChaosWarlock', supply: 2, gold: 220, lumber: 0 },
  nckb: { name: 'Chaos Kodo Beast', supply: 4, gold: 255, lumber: 60 },
  ncpn: { name: 'Chaos Peon', supply: 1, gold: 70, lumber: 0 },
  ndmu: { name: 'dalaran mutant', supply: 2, gold: 120, lumber: 0 },
  ndrd: { name: 'draenei darkslayer', supply: 4, gold: 260, lumber: 40 },
  ndrf: { name: 'draenei guardian', supply: 2, gold: 85, lumber: 0 },
  ndrh: { name: 'draenei harbinger', supply: 2, gold: 165, lumber: 20 },
  ndrj: { name: 'dalaran reject', supply: 1, gold: 85, lumber: 0 },
  ndrl: { name: 'draenei laborer', supply: 1, gold: 75, lumber: 0 },
  ndrm: { name: 'draenei disciple', supply: 2, gold: 195, lumber: 10 },
  ndrn: { name: 'Draeni Vindicator', supply: 4, gold: 225, lumber: 15 },
  ndrp: { name: 'draenei protector', supply: 2, gold: 135, lumber: 0 },
  ndrs: { name: 'draenei seer', supply: 3, gold: 210, lumber: 30 },
  ndrt: { name: 'Draeni Stalker', supply: 4, gold: 270, lumber: 30 },
  ndrw: { name: 'draenei watcher', supply: 2, gold: 135, lumber: 0 },
  ndsa: { name: 'draenei salamander', supply: 3, gold: 215, lumber: 40 },
  negz: { name: 'engineer gazlowe', supply: 2, gold: 215, lumber: 100 },
  nemi: { name: 'emissary', supply: 2, gold: 205, lumber: 0 },
  nfgl: { name: 'flesh golem', supply: 5, gold: 500, lumber: 150 },
  ngbl: { name: 'goblin blaster', supply: 0, gold: 375, lumber: 100 },
  nhea: { name: 'high elven archer', supply: 2, gold: 130, lumber: 10 },
  nhef: { name: 'high elven female', supply: 0, gold: 0, lumber: 0 },
  nhem: { name: 'high elven male', supply: 0, gold: 0, lumber: 0 },
  nhew: { name: 'blood elf worker', supply: 1, gold: 75, lumber: 0 },
  njks: { name: 'jailor kassan', supply: 1, gold: 85, lumber: 0 },
  nmdm: { name: 'medivh morphed', supply: 0, gold: 185, lumber: 0 },
  nmed: { name: 'medivh', supply: 0, gold: 185, lumber: 0 },
  nmpe: { name: 'naga peon', supply: 1, gold: 75, lumber: 0 },
  nmsh: { name: 'misha the bear', supply: 3, gold: 155, lumber: 0 },
  nser: { name: 'searinox', supply: 6, gold: 510, lumber: 120 },
  nspc: { name: 'support column', supply: 0, gold: 50, lumber: 0 },
  nssn: { name: 'night elf assassin', supply: 3, gold: 195, lumber: 20 },
  nthr: { name: 'tharifas', supply: 6, gold: 510, lumber: 150 },
  nw2w: { name: 'War2Warlock', supply: 2, gold: 215, lumber: 0 },
  nwat: { name: 'watcher', supply: 2, gold: 140, lumber: 0 },
  nzlc: { name: 'cinematic lich king', supply: 0, gold: 0, lumber: 0 },
  odkt: { name: "Drak'Thul", supply: 2, gold: 145, lumber: 20 },
  ogrk: { name: "Gar'thok", supply: 3, gold: 200, lumber: 0 },
  ojgn: { name: 'actual orc juggernaut unit', supply: 0, gold: 500, lumber: 200 },
  omtg: { name: 'mathog', supply: 2, gold: 130, lumber: 0 },
  onzg: { name: 'nazgrel', supply: 3, gold: 180, lumber: 40 },
  oosc: { name: 'riderless kodo beast', supply: 0, gold: 195, lumber: 35 },
  oswy: { name: 'spirit wyvern', supply: 3, gold: 130, lumber: 0 },
  ovlj: { name: "vol'jin", supply: 2, gold: 145, lumber: 25 },
  owar: { name: 'orc warchief', supply: 2, gold: 130, lumber: 0 },
  ownr: { name: 'wyvern', supply: 3, gold: 130, lumber: 0 },
  uabc: { name: 'Abomination cinematic', supply: 4, gold: 240, lumber: 70 },
  uarb: { name: 'air barge', supply: 0, gold: 240, lumber: 60 },
  ubdd: { name: 'undead azurelore', supply: 7, gold: 385, lumber: 120 },
  ubdr: { name: 'azurelore', supply: 8, gold: 595, lumber: 200 },
  ubot: { name: 'undead transport ship', supply: 0, gold: 170, lumber: 50 },
  udes: { name: 'undead frigate', supply: 0, gold: 250, lumber: 100 },
  uktg: { name: 'kelthuzad ghost', supply: 0, gold: 195, lumber: 0 },
  uktn: { name: 'kelthuzadnecro', supply: 0, gold: 195, lumber: 0 },
  uswb: { name: 'sylvanus banshee', supply: 3, gold: 225, lumber: 0 },
  haro: { name: 'Arcane Observatory', supply: 0, gold: 240, lumber: 100 },
  nbfl: { name: 'Fountain of Blood', supply: 0, gold: 50, lumber: 0 },
  nbse: { name: 'bindstone southeast', supply: 0, gold: 50, lumber: 0 },
  nbsm: { name: 'book of summoning pedestal', supply: 0, gold: 50, lumber: 0 },
  nbsw: { name: 'bindstone southwest', supply: 0, gold: 50, lumber: 0 },
  nbt1: { name: 'boulder tower', supply: 0, gold: 120, lumber: 60 },
  nbt2: { name: 'boulder tower upgraded', supply: 0, gold: 120, lumber: 60 },
  nbwd: { name: 'barrow den', supply: 0, gold: 210, lumber: 100 },
  ncap: { name: 'corrupted Ancient Protector', supply: 0, gold: 240, lumber: 130 },
  ncaw: { name: 'AncientofWar', supply: 0, gold: 255, lumber: 70 },
  ncmw: { name: 'corrupted MoonWell', supply: 0, gold: 155, lumber: 40 },
  ncta: { name: 'corrupted treeofAges', supply: 0, gold: 270, lumber: 80 },
  ncte: { name: 'corrupted treeofEternity', supply: 0, gold: 995, lumber: 200 },
  nctl: { name: 'corrupted treeofLife', supply: 0, gold: 385, lumber: 0 },
  ndfl: { name: 'Defiled Fountain of Life', supply: 0, gold: 50, lumber: 0 },
  ndgt: { name: 'dalaran guard tower', supply: 0, gold: 120, lumber: 60 },
  ndke: { name: 'dark portal (southeast)', supply: 0, gold: 50, lumber: 0 },
  ndkw: { name: 'dark portal (southwest)', supply: 0, gold: 50, lumber: 0 },
  ndmg: { name: 'demon gate', supply: 0, gold: 50, lumber: 0 },
  ndrb: { name: 'Dragon Building', supply: 0, gold: 50, lumber: 0 },
  ndt1: { name: 'cold tower', supply: 0, gold: 120, lumber: 60 },
  ndt2: { name: 'cold tower upgraded', supply: 0, gold: 120, lumber: 60 },
  nef0: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  nef1: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  nef2: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  nef3: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  nef4: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  nef5: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  nef6: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  nef7: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  nefm: { name: 'elven farm', supply: 0, gold: 70, lumber: 20 },
  negf: { name: 'elven guard fire tower', supply: 0, gold: 120, lumber: 60 },
  negm: { name: 'elven guard magic tower', supply: 0, gold: 120, lumber: 60 },
  negt: { name: 'elven guard tower', supply: 0, gold: 120, lumber: 60 },
  net1: { name: 'energy tower', supply: 0, gold: 120, lumber: 60 },
  net2: { name: 'energy tower upgraded', supply: 0, gold: 120, lumber: 60 },
  nfnp: { name: 'purple fountain', supply: 0, gold: 50, lumber: 0 },
  nfrm: { name: 'frostmourne pedestal', supply: 0, gold: 50, lumber: 0 },
  nfrt: { name: 'fruit stand', supply: 0, gold: 50, lumber: 0 },
  nft1: { name: 'flame tower', supply: 0, gold: 120, lumber: 60 },
  nft2: { name: 'flame tower upgraded', supply: 0, gold: 120, lumber: 60 },
  nfv0: { name: 'elven fishing village', supply: 0, gold: 50, lumber: 0 },
  nfv1: { name: 'elven fishing village', supply: 0, gold: 50, lumber: 0 },
  nfv2: { name: 'elven fishing village', supply: 0, gold: 50, lumber: 0 },
  nfv3: { name: 'elven fishing village', supply: 0, gold: 50, lumber: 0 },
  nfv4: { name: 'elven fishing village', supply: 0, gold: 50, lumber: 0 },
  ngob: { name: 'gemstone obelisk', supply: 0, gold: 50, lumber: 0 },
  nhcn: { name: 'horn of cenarius pedestal', supply: 0, gold: 50, lumber: 0 },
  nheb: { name: 'High Elf Barracks', supply: 0, gold: 255, lumber: 80 },
  nico: { name: 'icecrown obelisk', supply: 0, gold: 50, lumber: 0 },
  nitb: { name: 'treasure box', supply: 0, gold: 50, lumber: 0 },
  nmgv: { name: 'magic vault', supply: 0, gold: 50, lumber: 0 },
  nnad: { name: 'altar of the depths - naga altar', supply: 0, gold: 255, lumber: 100 },
  nnfm: { name: 'coral bed - naga farm', supply: 0, gold: 115, lumber: 40 },
  nnsa: { name: 'shrine of azshara - naga caster barracks', supply: 0, gold: 180, lumber: 70 },
  nnsg: { name: 'spawning grounds - naga barracks', supply: 0, gold: 205, lumber: 60 },
  nntg: { name: 'tidal guardian - naga tower', supply: 0, gold: 130, lumber: 80 },
  nntt: { name: 'temple of tides - naga town hall', supply: 0, gold: 385, lumber: 150 },
  npgf: { name: 'pig farm', supply: 0, gold: 115, lumber: 40 },
  npgr: { name: 'power generator', supply: 0, gold: 50, lumber: 0 },
  nshr: { name: 'shrine', supply: 0, gold: 50, lumber: 0 },
  ntt1: { name: 'death tower', supply: 0, gold: 120, lumber: 60 },
  ntx2: { name: 'death tower upgraded', supply: 0, gold: 120, lumber: 60 },
  nvr0: { name: 'elven fishing village', supply: 0, gold: 50, lumber: 0 },
  nvr1: { name: 'elven fishing village', supply: 0, gold: 50, lumber: 0 },
  nvr2: { name: 'elven fishing village', supply: 0, gold: 50, lumber: 0 },
  nwc1: { name: 'wyvern cage 1', supply: 0, gold: 50, lumber: 0 },
  nwc2: { name: 'wyvern cage 2', supply: 0, gold: 50, lumber: 0 },
  nwc3: { name: 'wyvern cage 3', supply: 0, gold: 50, lumber: 0 },
  nwc4: { name: 'wyvern cage 4', supply: 0, gold: 50, lumber: 0 },
  nzin: { name: 'zone indicator', supply: 0, gold: 50, lumber: 0 },
  ocbw: { name: 'Chaos OrcBurrow', supply: 0, gold: 160, lumber: 70 },
  zcso: { name: 'chaos space orc', supply: 3, gold: 215, lumber: 10 },
  zhyd: { name: 'hydralisk', supply: 3, gold: 280, lumber: 30 },
  zjug: { name: 'orc juggernaut', supply: 4, gold: 205, lumber: 30 },
  zmar: { name: 'Marine', supply: 2, gold: 215, lumber: 0 },
  zshv: { name: 'shoveler', supply: 5, gold: 680, lumber: 200 },
  zsmc: { name: 'sammy cube', supply: 4, gold: 425, lumber: 150 },
  zzrg: { name: 'zergling', supply: 1, gold: 85, lumber: 0 },
  Nmsr: { name: 'Murloc Sorceror', supply: 5, gold: 500, lumber: 100 },
  Nswt: { name: 'Sea Witch', supply: 5, gold: 500, lumber: 100 },
  ntn3: { name: 'Tent', supply: 0, gold: 0, lumber: 0 },
  nggm: { name: 'granite golem', supply: 8, gold: 545, lumber: 150 },
  nggg: { name: 'granite golem', supply: 8, gold: 545, lumber: 150 },
  nggd: { name: 'rock golem', supply: 5, gold: 365, lumber: 80 },
  ngow: { name: 'gnoll king', supply: 4, gold: 305, lumber: 35 },
  nwzw: { name: 'rogue wizard', supply: 2, gold: 215, lumber: 20 },
  ngos: { name: 'gnoll king', supply: 4, gold: 305, lumber: 35 },
  ngog: { name: 'dog', supply: 0, gold: 0, lumber: 0 },
  nwar: { name: 'Siege Engine', supply: 4, gold: 195, lumber: 60 },
  nccd: { name: 'Siege Engine', supply: 0, gold: 195, lumber: 0 },
  ncco: { name: 'Siege Engine', supply: 4, gold: 195, lumber: 60 },
  nccu: { name: 'Siege Engine', supply: 4, gold: 195, lumber: 60 },
  nccr: { name: 'Siege Engine', supply: 4, gold: 195, lumber: 60 },
  Hjnd: { name: 'sylvanus windrunner', supply: 0, gold: 425, lumber: 100 },
  nmg2: { name: "Mur'gul Hut 1", supply: 0, gold: 0, lumber: 0 },
  nhn2: { name: 'harpy nest', supply: 0, gold: 0, lumber: 0 },
  obai: { name: 'spiritwalker', supply: 0, gold: 195, lumber: 35 },
  hrrh: { name: 'Peasant', supply: 1, gold: 75, lumber: 0 },
  Haah: { name: 'HeroArchMage', supply: 5, gold: 425, lumber: 100 },
  Hssa: { name: 'HeroPaladin', supply: 5, gold: 425, lumber: 100 },
  Hddt: { name: 'ThalorienDawnseeker', supply: 5, gold: 425, lumber: 100 },
  owad: { name: 'WolfRider', supply: 3, gold: 180, lumber: 40 },
}
