import type { UpgradeData } from './balance.js'

export const UPGRADES_TECH: Record<string, UpgradeData> = {
  Rhme: { name: 'human melee attack', gold: 100, lumber: 50 },
  Rhra: { name: 'human ranged attack', gold: 100, lumber: 50 },
  Rhhb: { name: 'human hammer bounce', gold: 125, lumber: 225 },
  Rhar: { name: 'human armor', gold: 125, lumber: 75 },
  Rhgb: { name: 'human gyro bombs', gold: 150, lumber: 100 },
  Rhac: { name: 'human architecture', gold: 125, lumber: 50 },
  Rhde: { name: 'human footman defend', gold: 125, lumber: 75 },
  Rhan: { name: 'human animal breeding', gold: 125, lumber: 125 },
  Rhpt: { name: 'human priest training', gold: 100, lumber: 50 },
  Rhst: { name: 'human sorceress training', gold: 100, lumber: 50 },
  Rhla: { name: 'human leather armor', gold: 100, lumber: 100 },
  Rhri: { name: 'human rifleman plus range', gold: 75, lumber: 125 },
  Rhlh: { name: 'human lumber harvesting', gold: 100, lumber: 0 },
  Rhse: { name: 'human magical sentinal', gold: 50, lumber: 50 },
  Rhfl: { name: 'human flare', gold: 50, lumber: 50 },
  Rhss: { name: 'human control magic', gold: 75, lumber: 75 },
  Rhrt: { name: 'human rocket tank', gold: 50, lumber: 150 },
  Rhpm: { name: 'human backpack', gold: 50, lumber: 25 },
  Rhfc: { name: 'human flak cannon', gold: 100, lumber: 150 },
  Rhfs: { name: 'human frag shards', gold: 50, lumber: 100 },
  Rhcd: { name: 'human cloud research', gold: 50, lumber: 100 },
  Rhsb: { name: 'human sundering blades', gold: 100, lumber: 150 },
  Rome: { name: 'orc melee attack', gold: 100, lumber: 75 },
  Rora: { name: 'orc ranged attack', gold: 100, lumber: 100 },
  Roar: { name: 'orc armor', gold: 150, lumber: 75 },
  Rwdm: { name: 'orc war drums damage', gold: 100, lumber: 150 },
  Ropg: { name: 'orc pillage', gold: 75, lumber: 25 },
  Robs: { name: 'orc grunt berserk', gold: 50, lumber: 150 },
  Rows: { name: 'orc tauren smash', gold: 100, lumber: 175 },
  Roen: { name: 'orc raider ensare', gold: 50, lumber: 75 },
  Rovs: { name: 'orc wyvern venom spear', gold: 100, lumber: 150 },
  Rowd: { name: 'orc witch doctor training', gold: 100, lumber: 50 },
  Rost: { name: 'orc shaman training', gold: 100, lumber: 50 },
  Rosp: { name: 'orc spiked barricade', gold: 25, lumber: 75 },
  Rotr: { name: 'orc troll regeneration', gold: 100, lumber: 100 },
  Rolf: { name: 'orc liquid fire', gold: 75, lumber: 125 },
  Roch: { name: 'orc chaos conversion', gold: 0, lumber: 0 },
  Rowt: { name: 'orc spiritwalker training', gold: 100, lumber: 50 },
  Rorb: { name: 'orc reinforced defense', gold: 75, lumber: 175 },
  Robk: { name: 'orc berserkers', gold: 75, lumber: 175 },
  Ropm: { name: 'orc backpack', gold: 50, lumber: 25 },
  Robf: { name: 'orc naptha', gold: 50, lumber: 150 },
  Rume: { name: 'undead unholy strength', gold: 125, lumber: 50 },
  Rura: { name: 'undead creature attack', gold: 150, lumber: 50 },
  Ruar: { name: 'undead unholy armor', gold: 125, lumber: 50 },
  Ruac: { name: 'undead ghoul cannibalize', gold: 50, lumber: 0 },
  Rugf: { name: 'undead ghoul frenzy', gold: 100, lumber: 150 },
  Ruwb: { name: 'undead fiend web', gold: 100, lumber: 100 },
  Rusf: { name: 'undead gargoyle stone', gold: 75, lumber: 150 },
  Rune: { name: 'undead necromancer training', gold: 100, lumber: 50 },
  Ruba: { name: 'undead banshee training', gold: 100, lumber: 50 },
  Rufb: { name: 'undead frost wyrm breath', gold: 150, lumber: 225 },
  Rusl: { name: 'undead skeleton life span', gold: 75, lumber: 75 },
  Rucr: { name: 'undead creature armor', gold: 150, lumber: 75 },
  Rupc: { name: 'undead plague cloud', gold: 100, lumber: 200 },
  Rusm: { name: 'undead skeletal mastery', gold: 150, lumber: 100 },
  Rubu: { name: 'undead burrowing', gold: 75, lumber: 75 },
  Rusp: { name: 'undead avenger transform', gold: 75, lumber: 150 },
  Ruex: { name: 'undead exhume corpses', gold: 75, lumber: 50 },
  Rupm: { name: 'undead backpack', gold: 50, lumber: 25 },
  Resm: { name: 'nightelf strength of moon', gold: 125, lumber: 75 },
  Resw: { name: 'nightelf strength of wild', gold: 100, lumber: 75 },
  Rema: { name: 'nightelf moon armor', gold: 150, lumber: 75 },
  Rerh: { name: 'nightelf reinforced hides', gold: 150, lumber: 50 },
  Reuv: { name: 'nightelf ultravision', gold: 50, lumber: 50 },
  Renb: { name: "nightelf nature's blessing", gold: 150, lumber: 200 },
  Resc: { name: 'nightelf scout', gold: 50, lumber: 50 },
  Remg: { name: 'nightelf moon glaive upgrade', gold: 125, lumber: 175 },
  Reib: { name: 'nightelf improved bows', gold: 50, lumber: 100 },
  Remk: { name: 'nightelf marksmanship', gold: 100, lumber: 175 },
  Redt: { name: 'nightelf DoT training', gold: 100, lumber: 50 },
  Redc: { name: 'nightelf DoC training', gold: 100, lumber: 50 },
  Resi: { name: 'nightelf abolish magic', gold: 50, lumber: 50 },
  Recb: { name: 'nightelf corrosive breath', gold: 125, lumber: 225 },
  Reht: { name: 'nightelf hippogryph taming', gold: 75, lumber: 75 },
  Repb: { name: 'nightelf impaling bolt', gold: 125, lumber: 100 },
  Rers: { name: 'nightelf resistant skin', gold: 50, lumber: 100 },
  Rehs: { name: 'nightelf hardened skin', gold: 100, lumber: 175 },
  Reeb: { name: 'nightelf enchanted bears', gold: 25, lumber: 100 },
  Reec: { name: 'nightelf enchanted crows', gold: 25, lumber: 100 },
  Rews: { name: 'nightelf well spring', gold: 75, lumber: 150 },
  Repm: { name: 'nightelf backpack', gold: 50, lumber: 25 },
  Rgfo: { name: 'glyph of fortification', gold: 100, lumber: 100 },
  Rguv: { name: 'glyph of ultravision', gold: 100, lumber: 100 },
  Rnen: { name: 'naga myrmidon ensnare', gold: 50, lumber: 75 },
  Rnsw: { name: 'naga sea witch training', gold: 100, lumber: 50 },
  Rnsi: { name: 'naga abolish magic', gold: 50, lumber: 50 },
  Rnat: { name: 'naga attack', gold: 150, lumber: 75 },
  Rnam: { name: 'naga armor', gold: 125, lumber: 75 },
  Rnsb: { name: 'naga submerge', gold: 25, lumber: 25 },
}
