// ---------------------------------------------------------------------------
// Warcraft III unit and hero reference data
// ---------------------------------------------------------------------------

export interface UnitData {
  supply: number
  gold: number
  lumber: number
  icon?: string
}

export const UNITS: Record<string, UnitData> = {
  // Human
  Peasant: { supply: 1, gold: 75, lumber: 0, icon: 'hpea' },
  Militia: { supply: 1, gold: 75, lumber: 0, icon: 'hmil' },
  Footman: { supply: 2, gold: 135, lumber: 0, icon: 'hfoo' },
  Rifleman: { supply: 3, gold: 205, lumber: 30, icon: 'hrif' },
  Knight: { supply: 4, gold: 245, lumber: 60, icon: 'hkni' },
  Priest: { supply: 2, gold: 135, lumber: 10, icon: 'hmpr' },
  Sorceress: { supply: 2, gold: 155, lumber: 20, icon: 'hsor' },
  Spellbreaker: { supply: 3, gold: 215, lumber: 30, icon: 'hspt' },
  'Flying Machine': { supply: 1, gold: 90, lumber: 30, icon: 'hgyr' },
  'Mortar Team': { supply: 3, gold: 180, lumber: 70, icon: 'hmtm' },
  'Siege Engine': { supply: 3, gold: 195, lumber: 60, icon: 'hmtt' },
  'Gryphon Rider': { supply: 4, gold: 280, lumber: 70, icon: 'hgry' },
  'Dragonhawk Rider': { supply: 3, gold: 200, lumber: 30, icon: 'hdhw' },
  'Water Elemental': { supply: 0, gold: 0, lumber: 0, icon: 'hwel' },
  // Orc
  Peon: { supply: 1, gold: 75, lumber: 0, icon: 'opeo' },
  Grunt: { supply: 3, gold: 200, lumber: 0, icon: 'ogru' },
  'Troll Headhunter': { supply: 2, gold: 135, lumber: 20, icon: 'ohun' },
  Headhunter: { supply: 2, gold: 135, lumber: 20, icon: 'ohun' },
  'Troll Berserker': { supply: 2, gold: 135, lumber: 20, icon: 'otbk' },
  Shaman: { supply: 2, gold: 130, lumber: 20, icon: 'oshm' },
  'Troll Witch Doctor': { supply: 2, gold: 145, lumber: 25, icon: 'odoc' },
  Raider: { supply: 3, gold: 180, lumber: 40, icon: 'orai' },
  'Spirit Walker': { supply: 3, gold: 195, lumber: 35, icon: 'ospw' },
  'Spirit Wolf': { supply: 0, gold: 0, lumber: 0, icon: 'osw1' },
  'Troll Batrider': { supply: 2, gold: 160, lumber: 40, icon: 'otbr' },
  Demolisher: { supply: 4, gold: 220, lumber: 50, icon: 'ocat' },
  'Kodo Beast': { supply: 4, gold: 255, lumber: 60, icon: 'okod' },
  'Wind Rider': { supply: 4, gold: 265, lumber: 40, icon: 'owyv' },
  Tauren: { supply: 5, gold: 280, lumber: 80, icon: 'otau' },
  // Undead
  Acolyte: { supply: 1, gold: 75, lumber: 0, icon: 'uaco' },
  Shade: { supply: 1, gold: 0, lumber: 0, icon: 'ushd' },
  Ghoul: { supply: 2, gold: 120, lumber: 0, icon: 'ugho' },
  Gargoyle: { supply: 2, gold: 185, lumber: 30, icon: 'ugar' },
  Banshee: { supply: 2, gold: 155, lumber: 30, icon: 'uban' },
  Necromancer: { supply: 2, gold: 145, lumber: 20, icon: 'unec' },
  'Crypt Fiend': { supply: 3, gold: 215, lumber: 40, icon: 'ucry' },
  'Obsidian Statue': { supply: 3, gold: 200, lumber: 35, icon: 'uobs' },
  Abomination: { supply: 4, gold: 240, lumber: 70, icon: 'uabo' },
  'Meat Wagon': { supply: 4, gold: 230, lumber: 50, icon: 'umtw' },
  Destroyer: { supply: 5, gold: 0, lumber: 0, icon: 'ubsp' },
  'Frost Wyrm': { supply: 7, gold: 385, lumber: 120, icon: 'ufro' },
  'Skeleton Warrior': { supply: 0, gold: 0, lumber: 0, icon: 'uskw' },
  'Skeletal Mage': { supply: 0, gold: 0, lumber: 0, icon: 'uskm' },
  'Carrion Beetle': { supply: 0, gold: 0, lumber: 0, icon: 'ucrb' },
  // Night Elf
  Wisp: { supply: 1, gold: 60, lumber: 0, icon: 'ewsp' },
  Archer: { supply: 2, gold: 130, lumber: 10, icon: 'earc' },
  'Druid of the Talon': { supply: 2, gold: 135, lumber: 20, icon: 'edot' },
  Hippogryph: { supply: 2, gold: 160, lumber: 20, icon: 'ehip' },
  'Faerie Dragon': { supply: 2, gold: 155, lumber: 25, icon: 'efdr' },
  Huntress: { supply: 3, gold: 195, lumber: 20, icon: 'esen' },
  Dryad: { supply: 3, gold: 145, lumber: 60, icon: 'edry' },
  'Glaive Thrower': { supply: 3, gold: 210, lumber: 65, icon: 'ebal' },
  'Druid of the Claw': { supply: 4, gold: 255, lumber: 80, icon: 'edoc' },
  'Hippogryph Rider': { supply: 4, gold: 0, lumber: 0, icon: 'ehir' },
  Chimaera: { supply: 5, gold: 330, lumber: 70, icon: 'echm' },
  'Mountain Giant': { supply: 7, gold: 425, lumber: 100, icon: 'emtg' },
  'Sentry Ward': { supply: 0, gold: 0, lumber: 0, icon: 'ensw' },
  Treant: { supply: 0, gold: 0, lumber: 0, icon: 'etrt' },
  // NE buildings that appear as units
  'Ancient of War': { supply: 0, gold: 0, lumber: 0, icon: 'eaow' },
  'Ancient of Lore': { supply: 0, gold: 0, lumber: 0, icon: 'eaol' },
  'Ancient of Wind': { supply: 0, gold: 0, lumber: 0, icon: 'eawn' },
  'Ancient Protector': { supply: 0, gold: 0, lumber: 0, icon: 'etrt' },
  'Tree of Life': { supply: 0, gold: 0, lumber: 0, icon: 'etol' },
  'Tree of Ages': { supply: 0, gold: 0, lumber: 0, icon: 'etoa' },
  'Tree of Eternity': { supply: 0, gold: 0, lumber: 0, icon: 'etoe' },
  'Moon Well': { supply: 0, gold: 0, lumber: 0, icon: 'emwl' },
  "Hunter's Hall": { supply: 0, gold: 0, lumber: 0, icon: 'ehhl' },
  'Altar of Elders': { supply: 0, gold: 0, lumber: 0, icon: 'eale' },
  'Ancient of Wonders': { supply: 0, gold: 0, lumber: 0, icon: 'eawo' },
  // Neutral — Goblin Laboratory
  'Goblin Shredder': { supply: 4, gold: 375, lumber: 100, icon: 'ngir' },
  'Goblin Sapper': { supply: 2, gold: 215, lumber: 100, icon: 'ngsp' },
  'Goblin Zeppelin': { supply: 1, gold: 240, lumber: 60, icon: 'nzep' },
  // Neutral — Mercenaries
  Assassin: { supply: 3, gold: 260, lumber: 30, icon: 'nass' },
  Bloodfiend: { supply: 2, gold: 240, lumber: 0, icon: 'nfgb' },
  'Blue Dragonspawn Warrior': { supply: 4, gold: 300, lumber: 0, icon: 'nbdw' },
  'Burning Archer': { supply: 2, gold: 225, lumber: 25, icon: 'nskf' },
  'Centaur Archer': { supply: 2, gold: 150, lumber: 10, icon: 'ncea' },
  'Centaur Outrunner': { supply: 3, gold: 195, lumber: 0, icon: 'ncen' },
  'Dark Troll Berserker': { supply: 3, gold: 245, lumber: 30, icon: 'ndtb' },
  'Dark Troll Shadow Priest': { supply: 2, gold: 175, lumber: 10, icon: 'ndtp' },
  'Draenei Disciple': { supply: 2, gold: 195, lumber: 10, icon: 'ndrm' },
  'Forest Troll Berserker': { supply: 3, gold: 245, lumber: 30, icon: 'nftb' },
  'Forest Troll High Priest': { supply: 4, gold: 305, lumber: 40, icon: 'nfsh' },
  'Forest Troll Shadow Priest': { supply: 2, gold: 195, lumber: 10, icon: 'nfsp' },
  'Frost Revenant': { supply: 3, gold: 255, lumber: 30, icon: 'nrvs' },
  'Giant Wolf': { supply: 3, gold: 215, lumber: 0, icon: 'nwlg' },
  'Gnoll Brute': { supply: 2, gold: 140, lumber: 0, icon: 'ngnb' },
  'Gnoll Warden': { supply: 2, gold: 180, lumber: 20, icon: 'ngnw' },
  'Harpy Windwitch': { supply: 2, gold: 240, lumber: 30, icon: 'nhrw' },
  'Ice Troll Berserker': { supply: 3, gold: 245, lumber: 30, icon: 'nits' },
  'Ice Troll Priest': { supply: 2, gold: 175, lumber: 10, icon: 'nitp' },
  'Kobold Geomancer': { supply: 2, gold: 215, lumber: 30, icon: 'nkog' },
  'Kobold Taskmaster': { supply: 4, gold: 320, lumber: 50, icon: 'nkol' },
  'Kobold Tunneler': { supply: 2, gold: 150, lumber: 0, icon: 'nkot' },
  "Mur'gul Blood-Gill": { supply: 2, gold: 195, lumber: 10, icon: 'nmbg' },
  "Mur'gul Snarecaster": { supply: 3, gold: 265, lumber: 30, icon: 'nmsn' },
  'Mud Golem': { supply: 2, gold: 145, lumber: 10, icon: 'ngrk' },
  'Murloc Flesheater': { supply: 2, gold: 140, lumber: 0, icon: 'nmfs' },
  'Nerubian Seer': { supply: 4, gold: 320, lumber: 50, icon: 'nnwr' },
  'Nerubian Warrior': { supply: 2, gold: 205, lumber: 0, icon: 'nnwa' },
  'Ogre Magi': { supply: 4, gold: 320, lumber: 50, icon: 'nomg' },
  'Ogre Mauler': { supply: 4, gold: 300, lumber: 50, icon: 'nogm' },
  'Quillboar Hunter': { supply: 2, gold: 215, lumber: 20, icon: 'nqbh' },
  Rogue: { supply: 2, gold: 150, lumber: 0, icon: 'nrog' },
  'Satyr Shadowdancer': { supply: 2, gold: 190, lumber: 20, icon: 'nsts' },
  'Skeletal Orc Grunt': { supply: 4, gold: 300, lumber: 0, icon: 'nsog' },
  'Sludge Monstrosity': { supply: 4, gold: 320, lumber: 50, icon: 'nsln' },
  'Spitting Spider': { supply: 2, gold: 235, lumber: 30, icon: 'nssp' },
  'Stormreaver Hermit': { supply: 2, gold: 190, lumber: 20, icon: 'nsrh' },
  'Tuskarr Healer': { supply: 2, gold: 215, lumber: 10, icon: 'ntkh' },
  'Unbroken Darkweaver': { supply: 4, gold: 320, lumber: 50, icon: 'nubw' },
  Voidwalker: { supply: 2, gold: 245, lumber: 30, icon: 'nvdw' },
  Wildkin: { supply: 3, gold: 195, lumber: 0, icon: 'nowb' },
}

export const UNIT_SUPPLY: Record<string, number> = Object.fromEntries(
  Object.entries(UNITS).map(([name, u]) => [name, u.supply]),
)

export const UNIT_ICON_ID: Record<string, string> = Object.fromEntries(
  Object.entries(UNITS)
    .filter(([, u]) => u.icon !== undefined)
    .map(([name, u]) => [name, u.icon!]),
)

/** Display name keyed by fourcc item id (e.g. 'phea' → 'Potion of Healing'). */
export const ITEM_NAME_BY_ID: Record<string, string> = {
  amrc: 'Amulet of Recall',
  ankh: 'Ankh of Reincarnation',
  belv: "Boots of Quel'Thalas +6",
  bgst: 'Belt of Giant Strength +6',
  bspd: 'Boots of Speed',
  ccmd: 'Scepter of Mastery',
  ciri: 'Robe of the Magi +6',
  ckng: 'Crown of Kings +5',
  clsd: 'Cloak of Shadows',
  crys: 'Crystal Ball',
  desc: "Kelen's Dagger of Escape",
  gemt: 'Gem of True Seeing',
  gobm: 'Goblin Land Mines',
  gsou: 'Soul Gem',
  guvi: 'Glyph of Ultravision',
  gfor: 'Glyph of Fortification',
  soul: 'Soul',
  mdpb: 'Medusa Pebble',
  rag1: 'Slippers of Agility +3',
  rat3: 'Claws of Attack +3',
  rin1: 'Mantle of Intelligence +3',
  rde1: 'Ring of Protection +2',
  rde2: 'Ring of Protection +3',
  rde3: 'Ring of Protection +4',
  rhth: "Khadgar's Gem of Health",
  rst1: 'Gauntlets of Ogre Strength +3',
  ofir: 'Orb of Fire',
  ofro: 'Orb of Frost',
  olig: 'Orb of Lightning',
  oli2: 'Orb of Lightning',
  oven: 'Orb of Venom',
  odef: 'Orb of Darkness',
  ocor: 'Orb of Corruption',
  pdiv: 'Potion of Divinity',
  phea: 'Potion of Healing',
  pghe: 'Potion of Greater Healing',
  pinv: 'Potion of Invisibility',
  pgin: 'Potion of Greater Invisibility',
  pman: 'Potion of Mana',
  pgma: 'Potion of Greater Mana',
  pnvu: 'Potion of Invulnerability',
  pnvl: 'Potion of Lesser Invulnerability',
  pres: 'Potion of Restoration',
  pspd: 'Potion of Speed',
  rlif: 'Ring of Regeneration',
  rwiz: 'Sobi Mask',
  sfog: 'Horn of the Clouds',
  shea: 'Scroll of Healing',
  sman: 'Scroll of Mana',
  spro: 'Scroll of Protection',
  sres: 'Scroll of Restoration',
  ssil: 'Staff of Silence',
  stwp: 'Scroll of Town Portal',
  tels: 'Goblin Night Scope',
  tdex: 'Tome of Agility',
  texp: 'Tome of Experience',
  tint: 'Tome of Intelligence',
  tkno: 'Tome of Power',
  tstr: 'Tome of Strength',
  ward: 'Warsong Battle Drums',
  will: 'Wand of Illusion',
  wneg: 'Wand of Negation',
  rdis: 'Rune of Dispel Magic',
  rwat: 'Rune of the Watcher',
  fgrd: 'Red Drake Egg',
  fgrg: 'Stone Token',
  fgdg: 'Demonic Figurine',
  fgfh: 'Spiked Collar',
  fgsk: 'Book of the Dead',
  engs: 'Enchanted Gemstone',
  k3m1: 'Mooncrystal',
  modt: 'Mask of Death',
  sand: 'Scroll of Animate Dead',
  srrc: 'Scroll of Resurrection',
  sror: 'Scroll of the Beast',
  infs: 'Inferno Stone',
  shar: 'Ice Shard',
  wild: 'Amulet of the Wild',
  wswd: 'Sentry Wards',
  whwd: 'Healing Wards',
  wlsd: 'Wand of Lightning Shield',
  wcyc: 'Wand of the Wind',
  rnec: 'Rod of Necromancy',
  pams: 'Anti-magic Potion',
  clfm: 'Cloak of Flames',
  evtl: 'Talisman of Evasion',
  nspi: 'Necklace of Spell Immunity',
  lhst: 'The Lion Horn of Stormwind',
  kpin: "Khadgar's Pipe of Insight",
  sbch: 'Scourge Bone Chimes',
  afac: "Alleria's Flute of Accuracy",
  ajen: 'Ancient Janggo of Endurance',
  lgdh: 'Legion Doom-Horn',
  hcun: 'Hood of Cunning',
  mcou: 'Medallion of Courage',
  hval: 'Helm of Valor',
  cnob: 'Circlet of Nobility',
  prvt: 'Periapt of Vitality',
  tgxp: 'Tome of Greater Experience',
  mnst: 'Mana Stone',
  hlst: 'Health Stone',
  tpow: 'Tome of Knowledge',
  tst2: 'Tome of Strength +2',
  tin2: 'Tome of Intelligence +2',
  tdx2: 'Tome of Agility +2',
  rde0: 'Ring of Protection +1',
  rde4: 'Ring of Protection +5',
  rat6: 'Claws of Attack +6',
  rat9: 'Claws of Attack +9',
  ratc: 'Claws of Attack +12',
  ratf: 'Claws of Attack +15',
  manh: 'Manual of Health',
  pmna: 'Pendant of Mana',
  penr: 'Pendant of Energy',
  gcel: 'Gloves of Haste',
  totw: 'Talisman of the Wild',
  phlt: 'Phat Lewt',
  gopr: 'Glyph of Purification',
  ches: 'Cheese',
  mlst: 'Maul of Strength',
  rnsp: 'Ring of Superiority',
  brag: 'Bracer of Agility',
  sksh: 'Skull Shield',
  vddl: 'Voodoo Doll',
  sprn: 'Spider Ring',
  tmmt: 'Totem of Might',
  anfg: 'Ancient Figurine',
  lnrn: "Lion's Ring",
  iwbr: 'Ironwood Branch',
  jdrn: 'Jade Ring',
  drph: 'Druid Pouch',
  hslv: 'Healing Salve',
  pclr: 'Clarity Potion',
  plcl: 'Lesser Clarity Potion',
  rej1: 'Minor Replenishment Potion',
  rej2: 'Lesser Replenishment Potion',
  rej3: 'Replenishment Potion',
  rej4: 'Greater Replenishment Potion',
  rej5: 'Lesser Scroll of Replenishment',
  rej6: 'Greater Scroll of Replenishment',
  sreg: 'Scroll of Regeneration',
  gold: 'Gold Coins',
  lmbr: 'Bundle of Lumber',
  fgun: 'Flare Gun',
  pomn: 'Potion of Omniscience',
  gomn: 'Glyph of Omniscience',
  wneu: 'Wand of Neutralization',
  silk: 'Spider Silk Broach',
  lure: 'Monster Lure',
  skul: 'Sacrificial Skull',
  moon: 'Moonstone',
  brac: 'Runed Bracers',
  vamp: 'Vampiric Potion',
  woms: 'Wand of Mana Stealing',
  tcas: 'Tiny Castle',
  tgrh: 'Tiny Great Hall',
  tsct: 'Ivory Tower',
  wshs: 'Wand of Shadowsight',
  tret: 'Tome of Retraining',
  sneg: 'Staff of Negation',
  stel: 'Staff of Teleportation',
  spre: 'Staff of Preservation',
  mcri: 'Mechanical Critter',
  spsh: 'Amulet of Spell Shield',
  sbok: 'Spell Book',
  ssan: 'Staff of Sanctuary',
  shas: 'Scroll of Speed',
  dust: 'Dust of Appearance',
  oslo: 'Orb of Slow',
  dsum: 'Diamond of Summoning',
  sor1: 'Shadow Orb +1',
  sor2: 'Shadow Orb +2',
  sor3: 'Shadow Orb +3',
  sor4: 'Shadow Orb +4',
  sor5: 'Shadow Orb +5',
  sor6: 'Shadow Orb +6',
  sor7: 'Shadow Orb +7',
  sor8: 'Shadow Orb +8',
  sor9: 'Shadow Orb +9',
  sora: 'Shadow Orb +10',
  sorf: 'Shadow Orb Fragment',
  fwss: 'Frost Wyrm Skull Shield',
  ram1: 'Ring of the Archmagi',
  ram2: 'Ring of the Archmagi',
  ram3: 'Ring of the Archmagi',
  ram4: 'Ring of the Archmagi',
  shtm: 'Shamanic Totem',
  shwd: 'Shimmerweed',
  btst: 'Battle Standard',
  skrt: 'Skeletal Artifact',
  thle: 'Thunder Lizard Egg',
  sclp: 'Secret Level Powerup',
  gldo: "Orb of Kil'jaeden",
  tbsm: 'Tiny Blacksmith',
  tfar: 'Tiny Farm',
  tlum: 'Tiny Lumber Mill',
  tbar: 'Tiny Barracks',
  tbak: 'Tiny Altar of Kings',
  mgtk: 'Magic Key Chain',
  stre: 'Staff of Reanimation',
  horl: 'Sacred Relic',
  hbth: 'Helm of Battlethirst',
  blba: 'Bladebane Armor',
  rugt: 'Runed Gauntlets',
  frhg: 'Firehand Gauntlets',
  gvsm: 'Gloves of Spell Mastery',
  crdt: 'Crown of the Deathlord',
  arsc: 'Arcane Scroll',
  scul: 'Scroll of the Unholy Legion',
  tmsc: 'Tome of Sacrifices',
  dtsb: "Drek'thar's Spellbook",
  grsl: 'Grimoire of Souls',
  arsh: 'Arcanite Shield',
  shdt: 'Shield of the Deathlord',
  shhn: 'Shield of Honor',
  shen: 'Enchanted Shield',
  thdm: 'Thunderlizard Diamond',
  stpg: 'Clockwork Penguin',
  shrs: 'Shimmerglaze Roast',
  bfhr: "Bloodfeather's Heart",
  cosl: 'Celestial Orb of Souls',
  shcw: 'Shaman Claws',
  srbd: 'Searing Blade',
  frgd: 'Frostguard',
  envl: 'Enchanted Vial',
  rump: 'Rusty Mining Pick',
  mort: "Mogrin's Report",
  srtl: 'Serathil',
  stwa: 'Sturdy War Axe',
  klmm: 'Killmaim',
  rots: 'Scepter of the Sea',
  axas: 'Ancestral Staff',
  mnsf: 'Mindstaff',
  schl: 'Scepter of Healing',
  asbl: "Assassin's Blade",
  kgal: 'Keg of Ale',
  dphe: 'Thunder Phoenix Egg',
  dkfw: 'Keg of Thunderwater',
  dthb: 'Thunderbloom Bulb',
}

/** Gold cost keyed by fourcc item id (e.g. 'phea' → 75). Only purchasable items are present. */
export const ITEM_GOLD_BY_ID: Record<string, number> = {
  // Consumables
  phea: 75,
  pghe: 100,
  pman: 75,
  pgma: 100,
  pres: 350,
  pinv: 75,
  pgin: 100,
  pnvu: 150,
  pnvl: 100,
  pspd: 75,
  pdiv: 250,
  pomn: 300,
  pams: 150,
  vamp: 150,
  hslv: 100,
  pclr: 75,
  plcl: 50,
  rej1: 75,
  rej2: 100,
  rej3: 150,
  rej4: 200,
  rej5: 150,
  rej6: 200,
  // Scrolls / Glyphs
  stwp: 90,
  shea: 150,
  sman: 150,
  spro: 150,
  sres: 200,
  shas: 75,
  sreg: 150,
  sand: 300,
  srrc: 250,
  sror: 150,
  scul: 300,
  guvi: 150,
  gfor: 75,
  gopr: 100,
  gomn: 300,
  // Stat items
  bspd: 150,
  rde0: 50,
  rde1: 75,
  rde2: 100,
  rde3: 150,
  rde4: 200,
  rat3: 100,
  rat6: 200,
  rat9: 300,
  ratc: 450,
  ratf: 600,
  rag1: 150,
  rin1: 150,
  rst1: 150,
  ckng: 250,
  belv: 300,
  bgst: 300,
  ciri: 300,
  cnob: 50,
  rlif: 200,
  gcel: 200,
  evtl: 250,
  prvt: 200,
  manh: 250,
  pmna: 150,
  penr: 350,
  rhth: 150,
  rwiz: 100,
  crys: 150,
  gemt: 250,
  clsd: 200,
  clfm: 250,
  nspi: 150,
  hcun: 200,
  mcou: 200,
  hval: 200,
  // Orbs
  ofir: 200,
  ofro: 200,
  olig: 200,
  oli2: 200,
  oven: 200,
  odef: 200,
  ocor: 200,
  oslo: 200,
  // Artifacts / Unique
  modt: 250,
  amrc: 150,
  ankh: 125,
  desc: 125,
  lhst: 175,
  afac: 200,
  ajen: 200,
  lgdh: 200,
  sfog: 150,
  ward: 150,
  gsou: 150,
  // Tomes
  tdex: 200,
  tint: 200,
  tstr: 200,
  tkno: 150,
  texp: 100,
  tgxp: 100,
  tst2: 300,
  tin2: 300,
  tdx2: 300,
  tpow: 150,
  tret: 75,
  // Wands / Staves / Rods
  will: 100,
  wneg: 100,
  wneu: 200,
  wlsd: 150,
  wcyc: 150,
  rnec: 150,
  ssil: 200,
  kpin: 100,
  sneg: 150,
  stel: 150,
  spre: 100,
  ssan: 100,
  // Wards / Mines
  wswd: 150,
  whwd: 150,
  gobm: 150,
  tels: 150,
  dust: 75,
}

/** Display name keyed by fourcc unit id (e.g. 'hfoo' → 'Footman'). */
export const UNIT_NAME_BY_ID: Record<string, string> = Object.fromEntries(
  Object.entries(UNITS)
    .filter(([, u]) => u.icon !== undefined)
    .map(([name, u]) => [u.icon!, name]),
)

/** Supply cost keyed by fourcc unit id (e.g. 'hfoo' → 2). */
export const UNIT_SUPPLY_BY_ID: Record<string, number> = Object.fromEntries(
  Object.entries(UNITS)
    .filter(([, u]) => u.icon !== undefined)
    .map(([, u]) => [u.icon!, u.supply]),
)

/** Gold cost keyed by fourcc unit id (e.g. 'hfoo' → 135). */
export const UNIT_GOLD_BY_ID: Record<string, number> = Object.fromEntries(
  Object.entries(UNITS)
    .filter(([, u]) => u.icon !== undefined)
    .map(([, u]) => [u.icon!, u.gold]),
)

/** Lumber cost keyed by fourcc unit id (e.g. 'hfoo' → 0). */
export const UNIT_LUMBER_BY_ID: Record<string, number> = Object.fromEntries(
  Object.entries(UNITS)
    .filter(([, u]) => u.icon !== undefined)
    .map(([, u]) => [u.icon!, u.lumber]),
)

// ---------------------------------------------------------------------------
// Upgrade reference data (base cost = level 1 research cost)
// ---------------------------------------------------------------------------

interface UpgradeData {
  name: string
  gold: number
  lumber: number
}

export const UPGRADES_TECH: Record<string, UpgradeData> = {
  // Human
  Rhme: { name: 'Iron Forged Swords', gold: 75, lumber: 0 },
  Rhan: { name: 'Animal War Training', gold: 50, lumber: 25 },
  Rhar: { name: 'Iron Plating', gold: 75, lumber: 50 },
  Rhla: { name: 'Studded Leather Armor', gold: 75, lumber: 25 },
  Rhlh: { name: 'Improved Lumber Harvesting', gold: 125, lumber: 125 },
  Rhac: { name: 'Improved Masonry', gold: 50, lumber: 150 },
  Rhde: { name: 'Defend', gold: 50, lumber: 25 },
  Rhfc: { name: 'Flak Cannons', gold: 175, lumber: 100 },
  Rhfl: { name: 'Flare', gold: 100, lumber: 50 },
  Rhfs: { name: 'Fragmentation Shards', gold: 75, lumber: 25 },
  Rhgb: { name: 'Flying Machine Bombs', gold: 100, lumber: 125 },
  Rhhb: { name: 'Storm Hammers', gold: 100, lumber: 175 },
  Rhpm: { name: 'Backpack', gold: 100, lumber: 50 },
  Rhpt: { name: 'Priest Adept Training', gold: 100, lumber: 150 },
  Rhra: { name: 'Black Gunpowder', gold: 100, lumber: 75 },
  Rhri: { name: 'Long Rifles', gold: 150, lumber: 150 },
  Rhrt: { name: 'Barrage', gold: 50, lumber: 0 },
  Rhsb: { name: 'Sundering Blades', gold: 100, lumber: 50 },
  Rhse: { name: 'Magic Sentry', gold: 150, lumber: 150 },
  Rhss: { name: 'Spell Steal', gold: 100, lumber: 150 },
  Rhst: { name: 'Sorceress Adept Training', gold: 50, lumber: 75 },
  Rhcd: { name: 'Cloud', gold: 75, lumber: 75 },
  // Orc
  Roar: { name: 'Steel Armor', gold: 75, lumber: 0 },
  Robf: { name: 'Burning Oil', gold: 50, lumber: 75 },
  Robk: { name: 'Berserker Upgrade', gold: 75, lumber: 50 },
  Robs: { name: 'Brute Strength', gold: 150, lumber: 75 },
  Roen: { name: 'Ensnare', gold: 75, lumber: 0 },
  Rolf: { name: 'Liquid Fire', gold: 100, lumber: 125 },
  Rome: { name: 'Steel Melee Weapons', gold: 50, lumber: 150 },
  Ropg: { name: 'Pillage', gold: 50, lumber: 0 },
  Ropm: { name: 'Backpack', gold: 50, lumber: 75 },
  Rora: { name: 'Orc Ranged Attack', gold: 75, lumber: 0 },
  Rorb: { name: 'Reinforced Defenses', gold: 75, lumber: 50 },
  Rosp: { name: 'Spiked Barricades', gold: 100, lumber: 50 },
  Rost: { name: 'Shaman Adept Training', gold: 100, lumber: 50 },
  Rotr: { name: 'Troll Regeneration', gold: 75, lumber: 50 },
  Rovs: { name: 'Envenomed Spears', gold: 100, lumber: 50 },
  Rowd: { name: 'Witch Doctor Adept Training', gold: 100, lumber: 50 },
  Rows: { name: 'Pulverize', gold: 100, lumber: 150 },
  Rowt: { name: 'Sprit Walker Adept Training', gold: 100, lumber: 150 },
  // Undead
  Ruac: { name: 'Cannibalism', gold: 100, lumber: 50 },
  Ruar: { name: 'Unholy Armor', gold: 75, lumber: 50 },
  Ruba: { name: 'Banshee Adept Training', gold: 100, lumber: 50 },
  Rubu: { name: 'Burrow', gold: 100, lumber: 150 },
  Rucr: { name: 'Creature Carapace', gold: 75, lumber: 50 },
  Ruex: { name: 'Exhume Corpses', gold: 75, lumber: 25 },
  Rufb: { name: 'Freezing Breath', gold: 75, lumber: 75 },
  Rugf: { name: 'Ghoul Frenzy', gold: 75, lumber: 0 },
  Rume: { name: 'Unholy Strength', gold: 75, lumber: 0 },
  Rune: { name: 'Necromancer Adept Training', gold: 100, lumber: 50 },
  Rupc: { name: 'Disease Cloud', gold: 150, lumber: 150 },
  Rupm: { name: 'Backpack', gold: 50, lumber: 150 },
  Rura: { name: 'Creature Attack', gold: 75, lumber: 0 },
  Rusf: { name: 'Stone Form', gold: 50, lumber: 75 },
  Rusm: { name: 'Skeletal Mastery', gold: 50, lumber: 75 },
  Rusp: { name: 'Destroyer Form', gold: 150, lumber: 150 },
  Ruwb: { name: 'Web', gold: 75, lumber: 50 },
  // Night Elf
  Recb: { name: 'Corrosive Breath', gold: 75, lumber: 75 },
  Redc: { name: 'Druid of the Claw Adept Training', gold: 100, lumber: 50 },
  Redt: { name: 'Druid of the Talon Adept Training', gold: 100, lumber: 50 },
  Reeb: { name: 'Mark of the Claw', gold: 75, lumber: 50 },
  Reec: { name: 'Mark of the Talon', gold: 100, lumber: 150 },
  Rehs: { name: 'Hardened Skin', gold: 100, lumber: 50 },
  Reib: { name: 'Improved Bows', gold: 100, lumber: 150 },
  Rema: { name: 'Moon Armor', gold: 75, lumber: 50 },
  Remg: { name: 'Upgrade Moon Glaive', gold: 100, lumber: 75 },
  Remk: { name: 'Marksmanship', gold: 75, lumber: 50 },
  Renb: { name: "Nature's Blessing", gold: 75, lumber: 100 },
  Repb: { name: 'Vorpal Blades', gold: 75, lumber: 0 },
  Repm: { name: 'Backpack', gold: 100, lumber: 50 },
  Rerh: { name: 'Reinforced Hides', gold: 75, lumber: 50 },
  Rers: { name: 'Resistant Skin', gold: 75, lumber: 75 },
  Resc: { name: 'Sentinel', gold: 50, lumber: 25 },
  Resi: { name: 'Abolish Magic', gold: 50, lumber: 25 },
  Resm: { name: 'Strength of the Moon', gold: 75, lumber: 0 },
  Resw: { name: 'Strength of the Wild', gold: 75, lumber: 0 },
  Reuv: { name: 'Ultravision', gold: 75, lumber: 0 },
  Rews: { name: 'Well Spring', gold: 120, lumber: 80 },
  // Neutral
  Rwdm: { name: 'War Drums Damage Increase', gold: 100, lumber: 50 },
}

export const UPGRADE_NAME_BY_ID: Record<string, string> = Object.fromEntries(
  Object.entries(UPGRADES_TECH).map(([id, u]) => [id, u.name]),
)

export const UPGRADE_GOLD_BY_ID: Record<string, number> = Object.fromEntries(
  Object.entries(UPGRADES_TECH).map(([id, u]) => [id, u.gold]),
)

export const UPGRADE_LUMBER_BY_ID: Record<string, number> = Object.fromEntries(
  Object.entries(UPGRADES_TECH).map(([id, u]) => [id, u.lumber]),
)

export const WORKERS = new Set(['Peasant', 'Peon', 'Wisp', 'Acolyte'])

/** Worker unit ids by fourcc (e.g. 'hpea'). */
export const WORKERS_BY_ID = new Set(['hpea', 'opeo', 'ewsp', 'uaco'])

export const HERO_OBSERVER: Record<string, { icon: string; display: string }> = {
  archmage: { icon: 'Hamg', display: 'Archmage' },
  mountainking: { icon: 'Hmkg', display: 'Mountain King' },
  paladin: { icon: 'Hpal', display: 'Paladin' },
  bloodmage: { icon: 'Hblm', display: 'Blood Mage' },
  blademaster: { icon: 'Obla', display: 'Blademaster' },
  farseer: { icon: 'Ofar', display: 'Far Seer' },
  shadowhunter: { icon: 'Oshd', display: 'Shadow Hunter' },
  taurenchieftain: { icon: 'Otch', display: 'Tauren Chieftain' },
  deathknight: { icon: 'Udea', display: 'Death Knight' },
  dreadlord: { icon: 'Udre', display: 'Dreadlord' },
  lich: { icon: 'Ulic', display: 'Lich' },
  cryptlord: { icon: 'Ucrl', display: 'Crypt Lord' },
  demonhunter: { icon: 'Edem', display: 'Demon Hunter' },
  keeperofthegrove: { icon: 'Ekee', display: 'Keeper of the Grove' },
  priestessofthemoon: { icon: 'Emoo', display: 'Priestess of the Moon' },
  warden: { icon: 'Ewar', display: 'Warden' },
  alchemist: { icon: 'Nalc', display: 'Alchemist' },
  beastmaster: { icon: 'Nbst', display: 'Beastmaster' },
  darkranger: { icon: 'Nbrn', display: 'Dark Ranger' },
  firelord: { icon: 'Nfir', display: 'Fire Lord' },
  seawitch: { icon: 'Nngs', display: 'Naga Sea Witch' },
  pandarenbrewmaster: { icon: 'Npbm', display: 'Pandaren Brewmaster' },
  pitlord: { icon: 'Nplh', display: 'Pit Lord' },
  tinker: { icon: 'Ntin', display: 'Tinker' },
}

/** Cumulative XP required to reach each hero level (index = level - 1). */
export const HERO_XP_THRESHOLDS = [0, 200, 500, 900, 1400, 2000, 2700, 3500, 4400, 5400]

/** Hero observer data keyed by fourcc hero id (e.g. 'Hamg'). */
export const HERO_OBSERVER_BY_ID: Record<string, { display: string }> = Object.fromEntries(
  Object.entries(HERO_OBSERVER).map(([, v]) => [v.icon, { display: v.display }]),
)

/** Hero ability metadata keyed by fourcc ability id (e.g. 'AHbz'). */
export const ABILITY_BY_ID: Record<string, { name: string; ext: 'png' | 'gif' | 'jpg' }> = {
  // Archmage
  AHbz: { name: 'Blizzard', ext: 'png' },
  AHab: { name: 'Brilliance Aura', ext: 'png' },
  AHmt: { name: 'Mass Teleport', ext: 'png' },
  AHwe: { name: 'Summon Water Elemental', ext: 'png' },
  // Mountain King
  AHav: { name: 'Avatar', ext: 'gif' },
  AHbh: { name: 'Bash', ext: 'gif' },
  AHtb: { name: 'Storm Bolt', ext: 'gif' },
  AHtc: { name: 'Thunder Clap', ext: 'gif' },
  // Paladin
  AHad: { name: 'Devotion Aura', ext: 'png' },
  AHds: { name: 'Divine Shield', ext: 'png' },
  AHhb: { name: 'Holy Light', ext: 'png' },
  AHre: { name: 'Resurrection', ext: 'png' },
  // Blood Mage
  AHbn: { name: 'Banish', ext: 'png' },
  AHfs: { name: 'Flame Strike', ext: 'png' },
  AHpx: { name: 'Summon Phoenix', ext: 'png' },
  AHdr: { name: 'Siphon Mana', ext: 'png' },
  // Demon Hunter
  AEmb: { name: 'Mana Burn', ext: 'gif' },
  AEim: { name: 'Immolation', ext: 'gif' },
  AEev: { name: 'Evasion', ext: 'gif' },
  AEme: { name: 'Metamorphosis', ext: 'gif' },
  // Keeper of the Grove
  AEer: { name: 'Entangling Roots', ext: 'gif' },
  AEfn: { name: 'Force of Nature', ext: 'gif' },
  AEah: { name: 'Thorns Aura', ext: 'gif' },
  AEtq: { name: 'Tranquility', ext: 'gif' },
  // Priestess of the Moon
  AEst: { name: 'Scout', ext: 'gif' },
  AHfa: { name: 'Searing Arrows', ext: 'gif' },
  AEar: { name: 'Trueshot Aura', ext: 'gif' },
  AEsf: { name: 'Starfall', ext: 'gif' },
  // Warden
  AEbl: { name: 'Blink', ext: 'gif' },
  AEfk: { name: 'Fan of Knives', ext: 'gif' },
  AEsh: { name: 'Shadow Strike', ext: 'gif' },
  AEsv: { name: 'Spirit of Vengeance', ext: 'gif' },
  // Blademaster
  AOww: { name: 'Bladestorm', ext: 'gif' },
  AOcr: { name: 'Critical Strike', ext: 'gif' },
  AOmi: { name: 'Mirror Image', ext: 'gif' },
  AOwk: { name: 'Wind Walk', ext: 'gif' },
  // Far Seer
  AOcl: { name: 'Chain Lightning', ext: 'gif' },
  AOeq: { name: 'Earthquake', ext: 'gif' },
  AOfs: { name: 'Far Sight', ext: 'gif' },
  AOsf: { name: 'Feral Spirit', ext: 'gif' },
  // Shadow Hunter
  AOvd: { name: 'Big Bad Voodoo', ext: 'gif' },
  AOhw: { name: 'Healing Wave', ext: 'gif' },
  AOhx: { name: 'Hex', ext: 'gif' },
  AOsw: { name: 'Serpent Ward', ext: 'gif' },
  // Tauren Chieftain
  AOae: { name: 'Endurance Aura', ext: 'gif' },
  AOre: { name: 'Reincarnation', ext: 'gif' },
  AOsh: { name: 'Shockwave', ext: 'gif' },
  AOws: { name: 'War Stomp', ext: 'gif' },
  // Death Knight
  AUan: { name: 'Animate Dead', ext: 'gif' },
  AUdc: { name: 'Death Coil', ext: 'gif' },
  AUdp: { name: 'Death Pact', ext: 'gif' },
  AUau: { name: 'Unholy Aura', ext: 'gif' },
  // Dreadlord
  AUcs: { name: 'Carrion Swarm', ext: 'gif' },
  AUin: { name: 'Inferno', ext: 'gif' },
  AUsl: { name: 'Sleep', ext: 'gif' },
  AUav: { name: 'Vampiric Aura', ext: 'gif' },
  // Lich
  AUfn: { name: 'Frost Nova', ext: 'gif' },
  AUfa: { name: 'Frost Armor', ext: 'gif' },
  AUfu: { name: 'Frost Armor', ext: 'gif' },
  AUdr: { name: 'Dark Ritual', ext: 'gif' },
  AUdd: { name: 'Death and Decay', ext: 'gif' },
  // Crypt Lord
  AUim: { name: 'Impale', ext: 'gif' },
  AUts: { name: 'Spiked Carapace', ext: 'png' },
  AUcb: { name: 'Carrion Beetles', ext: 'gif' },
  AUls: { name: 'Locust Swarm', ext: 'gif' },
  // Pandaren Brewmaster
  ANbf: { name: 'Breath of Fire', ext: 'gif' },
  ANdb: { name: 'Drunken Brawler', ext: 'gif' },
  ANdh: { name: 'Drunken Haze', ext: 'gif' },
  ANef: { name: 'Storm, Earth, and Fire', ext: 'gif' },
  // Dark Ranger
  ANdr: { name: 'Life Drain', ext: 'gif' },
  ANsi: { name: 'Silence', ext: 'gif' },
  ANba: { name: 'Black Arrow', ext: 'gif' },
  ANch: { name: 'Charm', ext: 'gif' },
  // Naga Sea Witch
  ANms: { name: 'Mana Shield', ext: 'gif' },
  ANfa: { name: 'Frost Arrows', ext: 'gif' },
  ANfl: { name: 'Forked Lightning', ext: 'gif' },
  ANto: { name: 'Tornado', ext: 'gif' },
  // Pit Lord
  ANrf: { name: 'Rain of Fire', ext: 'gif' },
  ANca: { name: 'Cleaving Attack', ext: 'gif' },
  ANht: { name: 'Howl of Terror', ext: 'gif' },
  ANdo: { name: 'Doom', ext: 'gif' },
  // Beastmaster
  ANsg: { name: 'Summon Bear', ext: 'gif' },
  ANsq: { name: 'Summon Quilbeast', ext: 'gif' },
  ANsw: { name: 'Summon Hawk', ext: 'gif' },
  ANst: { name: 'Stampede', ext: 'gif' },
  // Goblin Tinker
  ANeg: { name: 'Engineering Upgrade', ext: 'png' },
  ANcs: { name: 'Cluster Rockets', ext: 'gif' },
  ANc1: { name: 'Cluster Rockets', ext: 'gif' },
  ANc2: { name: 'Cluster Rockets', ext: 'gif' },
  ANc3: { name: 'Cluster Rockets', ext: 'gif' },
  ANsy: { name: 'Pocket Factory', ext: 'gif' },
  ANs1: { name: 'Pocket Factory', ext: 'gif' },
  ANs2: { name: 'Pocket Factory', ext: 'gif' },
  ANs3: { name: 'Pocket Factory', ext: 'gif' },
  ANrg: { name: 'Robo-Goblin', ext: 'gif' },
  ANg1: { name: 'Robo-Goblin', ext: 'gif' },
  ANg2: { name: 'Robo-Goblin', ext: 'gif' },
  ANg3: { name: 'Robo-Goblin', ext: 'gif' },
  // Firelord
  ANic: { name: 'Incinerate', ext: 'jpg' },
  ANia: { name: 'Incinerate', ext: 'jpg' },
  ANso: { name: 'Soul Burn', ext: 'gif' },
  ANlm: { name: 'Summon Lava Spawn', ext: 'gif' },
  ANvc: { name: 'Volcano', ext: 'gif' },
  // Goblin Alchemist
  ANhs: { name: 'Healing Spray', ext: 'png' },
  ANab: { name: 'Acid Bomb', ext: 'png' },
  ANcr: { name: 'Chemical Rage', ext: 'png' },
  ANtm: { name: 'Transmute', ext: 'png' },
}

// ---------------------------------------------------------------------------
// Ability IDs
// ---------------------------------------------------------------------------

export const ABILITY_IDS: Record<string, string> = {
  abilityBase: 'abil',
  aOEdamageupondeath: 'Adda',
  abolishMagic: 'Aadm',
  abolishMagicCreep: 'ACdm',
  abolishMagicCreep12Pos: 'ACd2',
  abolishMagicNaga: 'Andm',
  absorbMana: 'Aabs',
  acidBomb: 'ANab',
  aerialShackles: 'Amls',
  agilityBonusPlus1: 'AIa1',
  agilityBonusPlus2: 'AIa2',
  agilityBonusPlus3: 'AIa3',
  agilityBonusPlus4: 'AIa4',
  agilityBonusPlus5: 'AIa5',
  agilityBonusPlus6: 'AIa6',
  agilityBonusPlus10: 'AIaz',
  agilityModPlus2: 'AIgm',
  ahrs: 'Ahrs',
  aIde: 'AIde',
  alarm: 'Aalr',
  alchemistChemicalRage: 'ANcr',
  alchemistHealingSpray: 'ANhs',
  allPlus1: 'AIx1',
  allPlus2: 'AIx2',
  allPlus3: 'AIx3',
  allPlus4: 'AIx4',
  alliedBuilding: 'Aall',
  ancestralSpirit: 'Aast',
  animateDead: 'ACad',
  animateDead1: 'AUan',
  animateDeadDk: 'AUa2',
  animateDeaditemspecial: 'AInd',
  antimagicShell: 'ACam',
  antimagicShell1: 'Aams',
  antimagicShieldAIxs: 'AIxs',
  antimagicShieldMatrix: 'Aam2',
  anwm: 'Anwm',
  aspx: 'Aspx',
  attack: 'Aatk',
  attackBonusAIt6: 'AIt6',
  attackBonusAIt9: 'AIt9',
  attackBonusAItc: 'AItc',
  attackBonusAItf: 'AItf',
  attackBonusPlus1: 'AItg',
  attackBonusPlus2: 'AIth',
  attackBonusPlus4: 'AIti',
  attackBonusPlus5: 'AItj',
  attackBonusPlus7: 'AItk',
  attackBonusPlus8: 'AItl',
  attackBonusPlus10: 'AItn',
  attackBonusPlus20: 'AItx',
  attackSpeedIncrease: 'AIsx',
  attackSpeedIncreaseGreater: 'AIs2',
  attackTargetPriority: 'Aatp',
  attributeModifierSkill: 'Aamk',
  aura: 'aura',
  auraCommandCreep: 'ACac',
  auraPlagueAbomination: 'Aap1',
  auraPlagueAnimatedDead: 'Aap5',
  auraPlagueCreep: 'Aap3',
  auraPlagueCreepnodamage: 'Aap4',
  auraRegenerationItem: 'AIgx',
  auraRegenerationStatue: 'Aabr',
  auraSpell: 'Aasp',
  autoTargetSpell: 'AAat',
  avatar: 'AHav',
  avatarGarithos: 'ANav',
  avengerForm: 'Aave',
  awakenHero: 'Aawa',
  ballsofFire: 'Abof',
  banish: 'AHbn',
  banishCreep: 'ACbn',
  barkskin: 'Abar',
  baseBuild: 'ABbs',
  baseSell: 'ASbs',
  bash: 'AHbh',
  bash1: 'ACbh',
  bashBeastmasterBear: 'ANbh',
  bashitem: 'AIbx',
  bashmaulSPBearlevel3: 'ANb2',
  battleRoar: 'ANbr',
  battleStations: 'Abtl',
  battlestationsChaos: 'Sbtl',
  bearForm: 'Abrf',
  beastMasterStampede: 'ANst',
  beastMasterSummonBear: 'ANsg',
  beastMasterSummonHawk: 'ANsw',
  beastMasterSummonQuilbeast: 'ANsq',
  berserkerRage: 'ACbr',
  berserkerRage1: 'Absk',
  berserkerUpgrade: 'Sbsk',
  beserkItem: 'AIxk',
  bigBadVoodoo: 'AOvd',
  blackArrowMeleeCreep: 'ACbk',
  bladestorm: 'AOww',
  blight: 'Abli',
  blightDispelLarge: 'Abdl',
  blightDispelSmall: 'Abds',
  blightedGoldMineAbility: 'Abgm',
  blightGrowth: 'Abli',
  blightGrowthLarge: 'Abgl',
  blightGrowthSmall: 'Abgs',
  blightPlacement: 'Ablp',
  blightRegen: 'Ablr',
  blinkBeastmasterBear: 'ANbl',
  blinkItem: 'AIbk',
  blizzard: 'AHbz',
  blizzard1: 'ACbz',
  bloodlust: 'ACbl',
  bloodlust1: 'Ablo',
  bloodlustCreepHotkeyB: 'ACbb',
  bloodMageFlameStrike: 'AHfs',
  bonusBase: 'ABon',
  bouncingMissileFilter: 'Amgi',
  bounce: 'Abou',
  breathofFireCreep: 'ACbc',
  breathofFrostCreep: 'ACbf',
  brewmasterBreathofFire: 'ANbf',
  brewmasterDrunkenBrawler: 'ANdb',
  brewmasterDrunkenHaze: 'ANdh',
  brewmasterStormEarthandFire: 'ANef',
  brillianceAura: 'AHab',
  brillianceAura1: 'ACba',
  build: 'ABld',
  buildInProgress: 'ABnP',
  buildQueue: 'ABqu',
  buildTinyAltar: 'AIbh',
  buildTinyBarracks: 'AIbs',
  buildTinyBlacksmith: 'AIbb',
  buildTinyCastle: 'AIbl',
  buildTinyFarm: 'AIbf',
  buildTinyGreatHall: 'AIbg',
  buildTinyLumberMill: 'AIbr',
  buildTinyScoutTower: 'AIbt',
  burrow: 'Abur',
  burrowBarbedArachnathid: 'Abu5',
  burrowDetectionFlyers: 'Abdt',
  burrowscarablvl2: 'Abu2',
  burrowscarablvl3: 'Abu3',
  buttonAbility: 'AAbt',
  cairneEnduranceAura: 'AOr2',
  cairneReincarnation: 'AOr3',
  cairneShockWave: 'AOs2',
  cairneWarStomp: 'AOw2',
  callToArms: 'Amic',
  calltoArms: 'Amil',
  callToArmsBase: 'Acal',
  cannibalize: 'Acan',
  cannibalizecreep: 'ACcn',
  cannibalizeAbomination: 'Acn2',
  cargo: 'Acrg',
  cargoHold: 'Abun',
  cargoHold1: 'Acar',
  cargoHold2: 'Amtc',
  cargoHoldDeath: 'Achd',
  cargoHoldMeatWagon: 'Sch2',
  cargoHoldShip: 'Sch5',
  cargoHoldTank: 'Sch4',
  cargoHoldTransport: 'Sch3',
  carrionSwarm: 'ACca',
  carrionSwarm1: 'AUcs',
  chainLightning: 'ACcl',
  chainLightning1: 'AOcl',
  chainLightningItem: 'AIcl',
  channel: 'ANcl',
  chaos: 'Acha',
  chaosBase: 'Achb',
  chaosCargoLoad: 'Achl',
  chaosGrom: 'Sca6',
  chaosGrunt: 'Sca1',
  chaosKodo: 'Sca4',
  chaosPeon: 'Sca5',
  chaosRaider: 'Sca2',
  chaosShaman: 'Sca3',
  charm: 'ACch',
  chenBreathOfFire: 'ANcf',
  chenDrunkenBrawler: 'Acdb',
  chenDrunkenHaze: 'Acdh',
  chenStormEarthAndFire: 'Acef',
  cleavingAttack: 'ACce',
  closestTargetSpell: 'AAcs',
  cloudofFog: 'Aclf',
  cloudofFogItem: 'AIfg',
  coldArrows: 'AHca',
  coldArrows1: 'ACcw',
  commandAura: 'AOac',
  controlMagic: 'Acmg',
  controlMagicItem: 'AIcm',
  corporealForm: 'Acpf',
  corrosiveBreath: 'Acor',
  couple: 'Acou',
  coupleInstant: 'Acoi',
  coupleInstantArcher: 'Aco2',
  coupleInstantHippogryph: 'Aco3',
  createCorpse: 'Agyd',
  cripple: 'Acri',
  cripple1: 'Scri',
  cripplecreep: 'ACcr',
  criticalStrike: 'ACct',
  criticalStrike1: 'AOcr',
  criticalStrikeItem: 'AIcs',
  crowForm: 'Amrf',
  crownofKingsAllPlus5: 'AIx5',
  crushingWave: 'ACcv',
  crushingWaveDragonTurtle: 'ACc2',
  crushingWaveLesser: 'ACc3',
  cryptLordCarrionScarabs: 'AUcb',
  cryptLordImpale: 'AUim',
  cryptLordLocustSwarm: 'AUls',
  cryptLordSpikedCarapace: 'AUts',
  curse: 'Acrs',
  cursecreep: 'ACcs',
  cyclone: 'SCc1',
  cyclone1: 'Acyc',
  cycloneAIcy: 'AIcy',
  cyclonecreep: 'ACcy',
  cycloneNaga: 'Acny',
  darkConversion: 'ANdc',
  darkConversionFast: 'SNdc',
  darkPortal: 'ANdp',
  darkRangerBlackArrow: 'ANba',
  darkRangerCharm: 'ANch',
  darkRangerDrain: 'ANdr',
  darkRitual: 'AUdr',
  darkSummoning: 'AUmd',
  darkSummoning1: 'AUds',
  deathAndDecay: 'SNdd',
  deathAndDecay1: 'AUdd',
  deathCoil: 'ACdc',
  deathCoil1: 'AUdc',
  deathDamageAOEmine: 'Amnx',
  deathDamageAOEmineBIG: 'Amnz',
  deathPact: 'AUdp',
  deathPactItem: 'AIdp',
  decouple: 'Adec',
  defend: 'Adef',
  defendItem: 'AIdd',
  defenseBonusPlus1: 'AId1',
  defenseBonusPlus2: 'AId2',
  defenseBonusPlus3: 'AId3',
  defenseBonusPlus4: 'AId4',
  defenseBonusPlus5: 'AId5',
  defenseBonusPlus7: 'AId7',
  defenseBonusPlus8: 'AId8',
  defenseBonusPlus10: 'AId0',
  detectSentryWard: 'Adt1',
  detectWarEagle: 'ANtr',
  detector: 'Adet',
  detonate: 'Adtn',
  devotionAura: 'AHad',
  devotionAura1: 'ACav',
  devour: 'ACdv',
  devour1: 'Adev',
  devourCargo: 'Advc',
  devourMagic: 'Advm',
  devourMagiccreep: 'ACde',
  disenchantNew: 'Adcn',
  disenchantold: 'Adch',
  diseaseCloud: 'Aap2',
  diseaseCloud1: 'Aapl',
  diseaseCloud2: 'Apts',
  dispelMagic: 'Adis',
  dispelMagic1: 'Adsm',
  divineShield: 'AHds',
  divineShield1: 'ACds',
  divineShieldItem: 'AIdv',
  drainLifeCreep: 'ACdr',
  drop1: 'Sdro',
  dropCorpse: 'Amed',
  dropPilot: 'Atdp',
  dustofAppearance: 'AItb',
  earthquake: 'SNeq',
  earthquake1: 'AOeq',
  eatTree: 'Aeat',
  elunesGrace: 'Aegr',
  enduranceAura: 'SCae',
  enduranceAura1: 'AOae',
  ensnare: 'ACen',
  ensnare1: 'Aens',
  ensnareNaga: 'ANen',
  entangleGoldMine: 'Aent',
  entangledGoldMineAbility: 'Aegm',
  entanglingRoots: 'Aenr',
  entanglingRoots1: 'AEer',
  entanglingSeaweed: 'Aenw',
  envenomedSpears: 'Aven',
  envenomedWeapons: 'ACvs',
  ethereal: 'Aetl',
  etherealForm: 'Aetf',
  evasion: 'ACev',
  evasion1: 'ACes',
  evasion2: 'AEev',
  evasion3: 'AIev',
  evilIllidanMetamorphosis: 'AEvi',
  exchangeGoldforLumber: 'ANgl',
  exchangeLumberforGold: 'ANlg',
  exhume: 'Aexh',
  experienceModgreater: 'AIe2',
  factory: 'ANfy',
  faerieFire: 'Afae',
  faerieFireAfa2: 'Afa2',
  faerieFirecreep: 'ACff',
  farSight: 'AOfs',
  feedback: 'Afbk',
  feedbackArcaneTower: 'Afbt',
  feedbackSpiritBeast: 'Afbb',
  feralSpirit: 'ACsf',
  feralSpirit1: 'ACs9',
  feralSpirit2: 'AOsf',
  feralSpiritAkama: 'ACs7',
  feralSpiritSpiritBeast: 'ACs8',
  figurineBlueDrake: 'AIbd',
  figurineDragonspawnOverseer: 'AIes',
  figurineFurbolgTracker: 'AIut',
  figurineIceRevenant: 'AIir',
  figurineUrsaWarrior: 'AIuw',
  fingerofDeath: 'ANfd',
  fingerOfDeath1: 'Afod',
  fingerOfDeathItem: 'AIfz',
  fingerOfPain: 'ACfd',
  fingerOfPain21Button: 'ACf3',
  firebolt: 'ANfb',
  firebolt1: 'ACfb',
  firebolt2: 'Awfb',
  firelordIncinerate: 'ANic',
  firelordIncinerate1: 'ANia',
  flakCannon: 'Aflk',
  flameStrikeCreep: 'ACfs',
  flameStrikeImprovedCreep: 'ANfs',
  flare: 'Afla',
  flareGun: 'AIfa',
  flagOrcBattleStandard: 'AIfx',
  forceofNature: 'ACfr',
  forceofNature1: 'AEfn',
  forkedLightningCreep: 'ACfl',
  fortificationGlyph: 'AIgf',
  fragShards: 'Afsh',
  freezingBreath: 'Afrz',
  frenzy: 'Afzy',
  frostArmor: 'ACfa',
  frostArmor1: 'AUfa',
  frostArmorAutocastNaga: 'ACfu',
  frostArmorCreepAutocast: 'ACf2',
  frostAttack: 'Afra',
  frostAttack12: 'Afr2',
  frostBolt: 'ACcb',
  frostBreath: 'Afrb',
  frostBreathNewHasIcon: 'Afrc',
  frostguardFrostMelee: 'AIft',
  frostNova: 'ACfn',
  frostNova1: 'AUfn',
  gather: 'Awha',
  gather1: 'Awh2',
  gather2: 'Aaha',
  garithosShockWave: 'ANsh',
  getCorpse: 'Amel',
  ghost: 'Agho',
  ghostVisible: 'Aeth',
  giveGold: 'AIgo',
  giveLumber: 'AIlu',
  glyph: 'AIgl',
  goldMineability: 'Agld',
  goldMineBase: 'Agmb',
  grabTree: 'Agra',
  graveyardCorpse: 'Agyc',
  gyrocopterBombs: 'Agyb',
  hardenedSkin: 'Assk',
  hardenedSkinNagaTurtle: 'Ansk',
  harvest: 'Ahar',
  harvest1: 'Ahrl',
  harvest2: 'Ahr3',
  harvestBase: 'Ahrb',
  harvestLumberArchimondeghouls: 'Ahr2',
  harvestNaga: 'ANha',
  harvestReturn: 'Ahrr',
  heal: 'Ahea',
  heal1: 'Anhe',
  heal2: 'Awhe',
  healCreepHigh: 'Anh2',
  healCreepNormal: 'Anh1',
  healingWard: 'AChw',
  healingWard1: 'Ahwd',
  healingWardAIhw: 'AIhw',
  healingWardAura: 'Aoar',
  healingWaveCreep: 'AChv',
  hero: 'AHer',
  hexCreep: 'AChx',
  holyLight: 'AHhb',
  holyLightItem: 'AIhl',
  howlOfTerror: 'Acht',
  humanBuild: 'AHbu',
  hurlBoulder: 'ACtb',
  immolation: 'ACim',
  immolation1: 'AEim',
  impaleCreep: 'ACmp',
  impalingBolt: 'Aimp',
  inciteUnholyFrenzy: 'Auuf',
  inferno: 'SNin',
  inferno1: 'ANin',
  inferno2: 'AUin',
  innerFire: 'Ainf',
  innerFireCreep: 'ACif',
  inProgress: 'AInP',
  intelligenceBonusPlus1: 'AIi1',
  intelligenceBonusPlus2: 'AIi2',
  intelligenceBonusPlus3: 'AIi3',
  intelligenceBonusPlus4: 'AIi4',
  intelligenceBonusPlus5: 'AIi5',
  intelligenceBonusPlus6: 'AIi6',
  intelligenceModPlus2: 'AItm',
  interfaced: 'AAin',
  inventory: 'AInv',
  inventory2slotunitUndead: 'Aiun',
  inventory2SlotUnitHuman: 'Aihn',
  inventory2SlotUnitNightElf: 'Aien',
  inventory2SlotUnitOrc: 'Aion',
  inventoryPackMule: 'Apak',
  invisibility: 'Aivs',
  invulnerable: 'Avul',
  itemAgilityGain: 'AIam',
  itemAnimateDead: 'AIan',
  itemAntiMagicShell: 'Aami',
  itemAreaDetection: 'AIta',
  itemAreaHealManaRegain: 'AIra',
  itemAreaHealing: 'AIha',
  itemAreaManaRegain: 'AImr',
  itemAreatreewalldamage: 'AIdm',
  itemArmorBonus: 'AId1',
  itemAttackDamageGain: 'AIaa',
  itemAttackFireBonus: 'AIfb',
  itemAttackHealReduction: 'AIf2',
  itemAttackFrostBonus: 'AIob',
  itemAttackLightningBonus: 'AIlb',
  itemAttackSpeedBonus: 'AIas',
  itemAuraBrilliance: 'AIba',
  itemAuraCommand: 'AIcd',
  itemAuraDevotion: 'AIad',
  itemAuraEndurance: 'AIae',
  itemAuraTrueshot: 'AIar',
  itemAuraUnholy: 'AIau',
  itemAuraVampiric: 'AIav',
  itemAuraWarDrums: 'AIwd',
  itemCaptureTheFlag: 'AIfl',
  itemCaptureTheFlag1: 'AIfm',
  itemCaptureTheFlag2: 'AIfn',
  itemCaptureTheFlag3: 'AIfo',
  itemCaptureTheFlag4: 'AIfe',
  itemChangeTOD: 'AIct',
  itemCommand: 'AIco',
  itemCureAoe: 'AIca',
  itemDamageBonus: 'AIat',
  itemDefenseAoePlusHealing: 'AIdb',
  itemDispel: 'AIdi',
  itemDispelAoeWithCooldown: 'AIds',
  itemDispelChain: 'AIdc',
  itemDoomGuardSummon: 'AIfu',
  itemExperienceGain: 'AIem',
  itemFelhoundSummon: 'AIfh',
  itemFlyingCarpet: 'AIfc',
  itemFirebolt: 'AIfi',
  itemFreezeDamageBonus: 'AIzb',
  itemFurbolgSummon: 'AIff',
  itemHealAoeGreater: 'AIhb',
  itemHealGreater: 'AIh2',
  itemHealLeast: 'AIh3',
  itemHealLeastest: 'AIhx',
  itemHealLesser: 'AIh1',
  itemHealManaRegain: 'AIre',
  itemHealing: 'AIhe',
  itemHeroStatBonus: 'AIab',
  itemIllusions: 'AIil',
  itemImmolation: 'AIcf',
  itemInferno: 'AIin',
  itemIntAgiStrgain: 'AIxm',
  itemIntelligenceGain: 'AIim',
  itemInvisGreater: 'AIv2',
  itemInvisLesser: 'AIv1',
  itemInvulDivinity: 'AIvg',
  itemInvulLesser: 'AIvl',
  itemLevelGain: 'AIlm',
  itemLifeBonus: 'AIml',
  itemLifeGain: 'AImi',
  itemLifeRegeneration: 'Arel',
  itemLifeSteal: 'AIva',
  itemManaBonus: 'AImm',
  itemManaRegain: 'AIma',
  itemManaRegeneration: 'AIrm',
  itemManaRestoreGreater: 'AIm2',
  itemManaRestoreLesser: 'AIm1',
  itemMonsterLure: 'AImo',
  itemMoveSpeedBonus: 'AIms',
  itemOrbOfVenom: 'AIno',
  itemPermInvis: 'AIpi',
  itemPlaceGoblinLandMine: 'AIpm',
  itemPotionVampirism: 'AIpv',
  itemPurge: 'AIlp',
  itemRandomItem: 'AIri',
  itemRecall: 'AIrt',
  itemRedDrakeSummon: 'AIfd',
  itemRegenManalesser: 'AIrn',
  itemReincarnation: 'AIrc',
  itemResurrection: 'AIrs',
  itemRevealMap: 'AIrv',
  itemRockGolemSummon: 'AIfr',
  itemShadowMeld: 'AIhm',
  itemSightRangeBonus: 'AIsi',
  itemSkeletonSummon: 'AIfs',
  itemSoulPossession: 'Asou',
  itemSoulTheft: 'AIso',
  itemSpeedAoe: 'AIsa',
  itemStrengthGain: 'AIsm',
  itemTeleport: 'AIte',
  itemTemporaryAreaArmorBonus: 'AIda',
  itemTemporaryInvisibility: 'AIvi',
  itemTemporaryInvulnerability: 'AIvu',
  itemTemporarySpeedBonus: 'AIsp',
  itemTownPortal: 'AItp',
  itemTransmute: 'AIts',
  itemUltravision: 'AIuv',
  itemWeb: 'AIwb',
  kaboom: 'Asds',
  leash: 'Alea',
  lichFrostArmorAutocast: 'AUfu',
  lifeRegeneration: 'ANrl',
  lifeRegenerationAura: 'ACnr',
  lightningAttack: 'Alit',
  lightningShield: 'Alsh',
  lightningShieldAIls: 'AIls',
  lightningShieldcreep: 'ACls',
  liquidFire: 'Aliq',
  load: 'Aloa',
  load1: 'Aenc',
  loadBurrow: 'Sloa',
  loadNavies: 'Slo3',
  loadPilot: 'Atlp',
  loadWisp: 'Slo2',
  locust: 'Aloc',
  magicDefense: 'Amdf',
  magicImmunityAImx: 'AImx',
  magicImmunityCreep: 'ACmi',
  magicSentry: 'Adts',
  makeItem: 'Amai',
  manaBatteryObsidianStatue: 'Amb2',
  manaBonus200: 'AI2m',
  manaBurn: 'Ambd',
  manaBurn1: 'AEmb',
  manaBurndemon: 'Amnb',
  manaBurnHotkeyB: 'Ambb',
  manaFlare: 'Amfl',
  manaRegeneration: 'ANre',
  manaRegenerationAura: 'Aarm',
  manaShieldCreep: 'ACmf',
  manaSteal: 'Aste',
  massTeleport: 'AHmt',
  maxLifeBonusGreater: 'AIl2',
  maxLifeBonusLeast: 'AIlf',
  maxLifeBonusLeastest: 'AIlz',
  maxLifeBonusLesser: 'AIl1',
  maxManaBonusLeast: 'AImb',
  maxManaBonusLeastest: 'AImz',
  maxManaBonusLeastestReally: 'AImv',
  maxManaBonusMost: 'AIbm',
  maxManaMod: 'AImn',
  mechanicalCritter: 'Amec',
  metamorphosis: 'AEme',
  metamorphosis1: 'AEIl',
  mindRot: 'ANmr',
  mineexploding: 'Amin',
  mirrorImage: 'AOmi',
  monsoon: 'ANmo',
  monsooncreep: 'ACmo',
  moonsoonDrain: 'ANmd',
  moonGlaive: 'Amgl',
  moonGlaiveNoResearch: 'Amgr',
  morph: 'Amor',
  mount: 'Amou',
  mountHippogryph: 'Acoa',
  move: 'Amov',
  nagaBuild: 'AGbu',
  neutralBuild: 'ANbu',
  neutralBuildinganyunit: 'Ane2',
  neutralInteract: 'Anei',
  neutralRegenMana: 'ANrm',
  neutralSpell: 'AAns',
  neutralSpies: 'Ansp',
  neutralSpiesFixed: 'ANsp',
  nightElfBuild: 'AEbu',
  notifyDamage: 'Admg',
  nullroarsummoner: 'Ahnl',
  onFire: 'Afir',
  onFireHuman: 'Afih',
  onFireNightElf: 'Afin',
  onFireOrc: 'Afio',
  onFireUndead: 'Afiu',
  orbofAnnihilation: 'Afak',
  orbofCorruption: 'AIcb',
  orbofDarkness: 'AIdf',
  orbofDarknessBlackArrow: 'ANbs',
  orbofGuldan: 'AIgd',
  orbofLightning: 'AIll',
  orbofSpells: 'AIsb',
  orbofVenom: 'AIpb',
  orbofVenomPoisonAttack: 'Apo2',
  orcBuild: 'AObu',
  parasiteEredar: 'ACpa',
  parasite: 'ANpa',
  passive: 'APas',
  passiveGhostIconOnlyUndeadAgho: 'Augh',
  passiveHumanAnimalBreedingRhan: 'Ahan',
  passiveHumanLumberHarvestingRhlh: 'Ahlh',
  passiveHumanRiflemanPlusRangeRhri: 'Ahri',
  passiveNightelfImprovedBowsReib: 'Aeib',
  passiveNightelfMarksmanshipRemk: 'Aemk',
  passiveNightelfWellSpringRews: 'Aews',
  passiveOrcBerserkersRobk: 'Aobk',
  passiveOrcGhostIconOnlyOrcAethUnused: 'Aoth',
  passiveOrcGruntBerserkRobs: 'Aobs',
  passiveOrcReinforcedDefenseRorb: 'Aorb',
  passiveOrcSpikedBarricadeRosp: 'Aosp',
  passiveOrcTrollRegenerationRotr: 'Aotr',
  passivePhoenixFireAndEgg: 'Ahpe',
  passiveSimple: 'APai',
  passiveUndeadGhoulFrenzyRugf: 'Augf',
  passiveUndeadSkeletalMasteryRusm: 'Ausm',
  penguinSqueek: 'AIpz',
  permanentHitpointBonusfromchargeditem: 'AImh',
  permanentHitPointBonusSmall: 'AIpx',
  permanentImmolation: 'ANpi',
  permanentImmolationflying: 'Apmf',
  permanentImmolationgraphic: 'Apig',
  permanentInvisibility: 'Apiv',
  persistentBonus: 'APbo',
  phaseShift: 'Apsh',
  phoenix: 'AHpx',
  phoenix2: 'Aphx',
  phoenixFire: 'Apxf',
  pickupArcher: 'Acoh',
  pIlotTankRifleman: 'Stpr',
  pillage: 'Asal',
  pilotTank: 'Atpi',
  pilotTankMortarTeam: 'Stpm',
  pitLordCleavingAttack: 'ANca',
  pitLordDoom: 'ANdo',
  pitLordHowlofTerror: 'ANht',
  poisonArrows: 'AEpa',
  poisonSting: 'Apoi',
  polymorph: 'Aply',
  polymorphcreep: 'ACpy',
  possessedGoldMine: 'Apgm',
  possession: 'Apos',
  possessionChanneling: 'Aps2',
  possessioncreep: 'ACps',
  potionofLifeRegen: 'AIrl',
  potionofManaRegengreater: 'AIpr',
  potionofManaRegenlesser: 'AIpl',
  potionofRejuvI: 'AIp1',
  potionofRejuvII: 'AIp2',
  potionofRejuvIII: 'AIp3',
  potionofRejuvIV: 'AIp4',
  power: 'powr',
  powerupDispelAoe: 'APdi',
  powerupHealAoe: 'APh2',
  powerupHealAoeGreater: 'APh3',
  powerupHealAoeLesser: 'APh1',
  preservation: 'ANpr',
  pulverize: 'Awar',
  pulverize1: 'ACpv',
  purge: 'Aprg',
  purgeApg2: 'Apg2',
  purgeCreep: 'ACpu',
  purgeorb: 'AIpg',
  purgeTotemSP: 'AIps',
  purgeWandOfNegation: 'AIpw',
  queue: 'Aque',
  quillSpray: 'ANak',
  rainofChaos: 'ANrc',
  rainOfChaosButton02: 'ANr3',
  rainofFire: 'ANrf',
  rainofFire1: 'ACrf',
  rainOfFireCreepGreater: 'ACrg',
  raiseDead: 'Arai',
  raiseDeadCreep: 'ACrd',
  raiseDeadItem: 'AIrd',
  rallyPoint: 'ARal',
  rangerArrow: 'AHRa',
  rayofDisruption: 'Ache',
  reassignableAttributeBonusPlus1: 'AIvm',
  regenBase: 'AREB',
  regenLifeArll: 'Arll',
  regenMana: 'Arem',
  regeneration: 'AIrg',
  reincarnation: 'ANrn',
  reincarnation1: 'ACrn',
  reincarnation2: 'AOre',
  reincarnationGeneric: 'ANr2',
  reincarnationItem: 'AIrx',
  reinforcedBurrows: 'Arbr',
  rejuvenation: 'ACr2',
  rejuvenation1: 'Arej',
  rejuvinationcreep: 'ACrj',
  renew: 'Aren',
  repair: 'Arep',
  repairHuman: 'Ahrp',
  replenishLife: 'Arpl',
  replenishLifeMana: 'Arpb',
  replenishMana: 'Arpm',
  replenishManaandLife: 'Ambt',
  rescuable: 'Arsc',
  research: 'ARes',
  resistantSkin: 'ACrk',
  resistantSkin31PosCreep: 'ACsk',
  restore: 'Arst',
  resurrection: 'AHre',
  resurrectionItem: 'AIrs',
  retrain: 'Aret',
  return111: 'Artn',
  returnGold: 'Argd',
  returnGoldLumber: 'Argl',
  returnLumber: 'Arlm',
  reveal: 'Adta',
  reveal1: 'Andt',
  revealArcaneTower: 'AHta',
  revenge: 'Arng',
  reviveHero: 'Arev',
  rexxarStampede: 'Arsp',
  rexxarStormBolt: 'ANsb',
  rexxarSummonBear: 'Arsg',
  rexxarSummonQuilbeast: 'Arsq',
  ritualDaggerInstantHeal: 'AIdg',
  ritualDaggerRegenerate: 'AIg2',
  roar: 'Aroa',
  roarAIrr: 'AIrr',
  roarAra2: 'Ara2',
  roarcreep: 'ACro',
  roarcreepSkeletalOrc: 'ACr1',
  rocketAttack: 'Aroc',
  rokhanHealingWave: 'ANhw',
  rokhanHex: 'ANhx',
  rokhanSerpentWard: 'Arsw',
  rokhanVoodooSpirits: 'AOls',
  root: 'Aroo',
  rootAncientProtector: 'Aro2',
  rootAncients: 'Aro1',
  runedBracers: 'AIsr',
  runeofGreaterResurrection: 'APrr',
  runeofLesserResurrection: 'APrl',
  runeofSpiritLink: 'Aspp',
  runeManaRestoreAoe: 'APmr',
  runeManaRestoreGreaterAoe: 'APmg',
  runeOfRebirth: 'AIrb',
  runeRestoreAoe: 'APra',
  runeSpeedAoe: 'APsa',
  runeOfTheWatcher: 'APwt',
  sacrifice: 'Alam',
  sacrifice1: 'Asac',
  sacrificeInProgress: 'ASnP',
  sanctuary: 'ANsa',
  scout: 'AEst',
  scrollofLifeRegen: 'AIsl',
  scrollofRejuvI: 'AIp5',
  scrollofRejuvII: 'AIp6',
  seaWitchForkedLightning: 'ANfl',
  seaWitchFrostArrows: 'ANfa',
  seaWitchManaShield: 'ANms',
  searingArrows: 'ACsa',
  searingArrows1: 'AHfa',
  searingBladeFireMelee: 'AIfw',
  selectHero: 'Aneu',
  selfDestruct2ClockwerkGoblins: 'Asd2',
  selfDestruct3ClockwerkGoblins: 'Asd3',
  selfDestructClockwerkGoblins: 'Asdg',
  sellItems: 'Asid',
  sellUnit: 'Asel',
  sellUnitDynamic: 'Asud',
  sentinel: 'Aesn',
  sentinelNoResearch: 'Aesr',
  sentryWard: 'Aeye',
  sentryWardAIsw: 'AIsw',
  serpentWardtentacleForgottenone: 'ACtn',
  shadowHunterHealingWave: 'AOhw',
  shadowHunterHex: 'AOhx',
  shadowHunterSerpentWard: 'AOsw',
  shadowHunterSerpentWard2: 'AOwd',
  shadowMeld: 'Ashm',
  shadowMeldAkama: 'Ahid',
  shadowMeldInstant: 'Sshm',
  shadowOrbAbility: 'AIdn',
  shadowSight: 'Ashs',
  shadowStrike: 'AEsh',
  shadowStrikeCreep: 'ACss',
  shamanClawsLightningMelee: 'AIlx',
  shockwave: 'ACsh',
  shockwave1: 'ACst',
  shockwave2: 'AOsh',
  shopPurchaseItem: 'Apit',
  shopSharingAlliedBldg: 'Aall',
  silence: 'ANsi',
  silenceCreep: 'ACsi',
  silenceItem: 'AIse',
  simpleSpell: 'AAsm',
  siphonMana: 'AHdr',
  siphonManaCreep: 'ACsm',
  slam: 'ACtc',
  slam1: 'ACt2',
  sleep: 'ACsp',
  sleep1: 'ACsl',
  sleep2: 'AUsl',
  sleepAlways: 'Asla',
  slow: 'Aslo',
  slow1: 'ACsw',
  slowAIos: 'AIos',
  slowAura: 'Aasl',
  slowPoison: 'Aspo',
  slowPoisonItem: 'AIsz',
  soulBurn: 'ANso',
  soulPreservation: 'ANsl',
  spawnHydra: 'Aspy',
  spawnHydraHatchling: 'Aspt',
  spawnOnDeathskeleton: 'Asod',
  spawnSpiderlings: 'Assp',
  spawnSpiders: 'Aspd',
  spell: 'AAsp',
  spellBook: 'Aspb',
  spellImmunity: 'ACm2',
  spellImmunity1: 'ACm3',
  spellImmunity2: 'Amim',
  spellShield: 'ANss',
  spellShieldAOE: 'ANse',
  spellSteal: 'Asps',
  sphere: 'Asph',
  sphereSoVLevel1: 'Asp1',
  sphereSoVLevel2: 'Asp2',
  sphereSoVLevel3: 'Asp3',
  sphereSoVLevel4: 'Asp4',
  sphereSoVLevel5: 'Asp5',
  sphereSoVLevel6: 'Asp6',
  spiderAttack: 'Aspa',
  spikedBarricades: 'Aspi',
  spiritLink: 'Aspl',
  spy: 'ANsp',
  staffoTeleportation: 'AImt',
  standDown: 'Astd',
  starfall: 'AEsf',
  starfall1: 'AEsb',
  starfallDrain: 'AEsd',
  stasisTrap: 'Asta',
  stoneForm: 'Astn',
  stormBolt: 'AHtb',
  stormCrowForm: 'Arav',
  stormHammers: 'Asth',
  strengthBonusPlus1: 'AIs1',
  strengthBonusPlus3: 'AIs3',
  strengthBonusPlus4: 'AIs4',
  strengthBonusPlus5: 'AIs5',
  strengthBonusPlus6: 'AIs6',
  strengthModPlus2: 'AInm',
  submerge: 'ANsu',
  submergeMyrmidon: 'Asb1',
  submergeRoyalGuard: 'Asb2',
  submergeSnapDragon: 'Asb3',
  summonHeadhunteritem: 'AIsh',
  summonLavaSpawn: 'ANlm',
  summonLobstrokPrawns: 'Aslp',
  summonSeaElemental: 'ACwe',
  summonWaterElemental: 'AHwe',
  sunderingBlades: 'Ahsb',
  tankUpgrade: 'Srtt',
  target: 'Atrg',
  taunt: 'Atau',
  taunt1: 'ANta',
  thornsAura: 'ACah',
  thornsAura1: 'AEah',
  thornyShieldCreep: 'ANth',
  thornyShieldDragonTurtle: 'ANt2',
  thunderClap: 'AHtc',
  tinkererClusterRocketsLevel0: 'ANcs',
  tinkererClusterRocketsLevel1: 'ANc1',
  tinkererClusterRocketsLevel2: 'ANc2',
  tinkererClusterRocketsLevel3: 'ANc3',
  tinkererDemolishLevel0: 'ANde',
  tinkererDemolishLevel1: 'ANd1',
  tinkererDemolishLevel2: 'ANd2',
  tinkererDemolishLevel3: 'ANd3',
  tinkererEngineeringUpgrade: 'ANeg',
  tinkererRoboGoblinLevel0: 'ANrg',
  tinkererRoboGoblinLevel1: 'ANg1',
  tinkererRoboGoblinLevel2: 'ANg2',
  tinkererRoboGoblinLevel3: 'ANg3',
  tinkererSummonFactoryLevel0: 'ANsy',
  tinkererSummonFactoryLevel1: 'ANs1',
  tinkererSummonFactoryLevel2: 'ANs2',
  tinkererSummonFactoryLevel3: 'ANs3',
  tornado: 'ANto',
  tornadoDamage: 'Atdg',
  tornadoSpin: 'Atsp',
  tornadoWander: 'Atwa',
  tracking: 'Anit',
  train: 'ATrn',
  tranquility: 'AEtq',
  tranquilityRegen: 'AEtr',
  transmute: 'ANtm',
  treeofLifeupgradeability: 'Atol',
  trueSight: 'Agyv',
  trueSight1: 'Adtg',
  trueSight2: 'Atru',
  trueshotAura: 'ACat',
  trueshotAura1: 'AEar',
  ultraVisionGlyph: 'AIgu',
  ultravision: 'Ault',
  undeadBuild: 'AUbu',
  unholyAura: 'ACua',
  unholyAura1: 'AUau',
  unholyFrenzy: 'Auhf',
  unholyFrenzy1: 'Suhf',
  unholyFrenzycreep: 'ACuf',
  unholyFrenzyItem: 'AIuf',
  unload: 'Adro',
  unloadInstant: 'Adri',
  unsummon: 'Buns',
  unsummonBuilding: 'Auns',
  unstableConcoction: 'Auco',
  upgrade: 'Aupg',
  upgradeInProgress: 'AUnP',
  vampiricAura: 'ACvp',
  vampiricAura1: 'AUav',
  vampiricattack: 'SCva',
  vengeance: 'Avng',
  volcano: 'ANvc',
  wander: 'Awan',
  warDrums: 'Aakb',
  warStomp: 'Awrs',
  warStomp1: 'AOws',
  warStomphydra: 'Awrh',
  warStompseagiant: 'Awrg',
  wardenBlink: 'AEbl',
  wardenFanofKnives: 'AEfk',
  wardenSpiritofVengeance: 'AEsv',
  wateryMinion: 'ANwm',
  wateryMinionItem: 'AIwm',
  waygateability: 'Awrp',
  web: 'Aweb',
  webcreep: 'ACwb',
  windWalk: 'AOwk',
  windWalk1: 'ANwk',
}

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

export interface ItemData {
  gold: number
  lumber: number
  icon: string
}

export const ITEMS: Record<string, ItemData> = {
  // ── Permanent ─────────────────────────────────────────────────────────────
  // Level 1
  'Cloak of Shadows': { gold: 100, lumber: 0, icon: 'clsd' },
  'Gauntlets of Ogre Strength +3': { gold: 100, lumber: 0, icon: 'rst1' },
  'Mantle of Intelligence +3': { gold: 100, lumber: 0, icon: 'rin1' },
  'Ring of Superiority': { gold: 100, lumber: 0, icon: 'rnsp' },
  'Slippers of Agility +3': { gold: 100, lumber: 0, icon: 'rag1' },
  // Level 2
  'Bracer of Agility': { gold: 150, lumber: 0, icon: 'brag' },
  'Claws of Attack +3': { gold: 150, lumber: 0, icon: 'rat3' },
  'Gloves of Haste': { gold: 150, lumber: 0, icon: 'gcel' },
  'Ring of Protection +2': { gold: 150, lumber: 0, icon: 'rde1' },
  // Level 3
  'Circlet of Nobility': { gold: 200, lumber: 0, icon: 'cnob' },
  'Claws of Attack +6': { gold: 250, lumber: 0, icon: 'rat6' },
  'Pendant of Energy': { gold: 300, lumber: 0, icon: 'penr' },
  'Periapt of Vitality': { gold: 300, lumber: 0, icon: 'prvt' },
  'Ring of Protection +4': { gold: 300, lumber: 0, icon: 'rde3' },
  'Ring of Regeneration': { gold: 300, lumber: 0, icon: 'rlif' },
  'Talisman of Evasion': { gold: 300, lumber: 0, icon: 'evtl' },
  // Level 4
  "Alleria's Flute of Accuracy": { gold: 400, lumber: 0, icon: 'afac' },
  'Belt of Giant Strength +6': { gold: 400, lumber: 0, icon: 'bgst' },
  "Boots of Quel'Thalas +6": { gold: 400, lumber: 0, icon: 'belv' },
  'Ring of the Archmagi': { gold: 300, lumber: 0, icon: 'ram1' },
  'Robe of the Magi +6': { gold: 400, lumber: 0, icon: 'ciri' },
  'Runed Bracers': { gold: 400, lumber: 0, icon: 'brac' },
  'Scourge Bone Chimes': { gold: 400, lumber: 0, icon: 'sbch' },
  'Sobi Mask': { gold: 400, lumber: 0, icon: 'rwiz' },
  'The Lion Horn of Stormwind': { gold: 400, lumber: 0, icon: 'lhst' },
  // Level 5
  'Ancient Janggo of Endurance': { gold: 500, lumber: 0, icon: 'ajen' },
  'Claws of Attack +9': { gold: 400, lumber: 0, icon: 'rat9' },
  'Cloak of Flames': { gold: 500, lumber: 0, icon: 'clfm' },
  'Helm of Valor': { gold: 500, lumber: 0, icon: 'hval' },
  'Hood of Cunning': { gold: 500, lumber: 0, icon: 'hcun' },
  "Khadgar's Pipe of Insight": { gold: 500, lumber: 0, icon: 'kpin' },
  'Legion Doom-Horn': { gold: 500, lumber: 0, icon: 'lgdh' },
  'Medallion of Courage': { gold: 500, lumber: 0, icon: 'mcou' },
  'Warsong Battle Drums': { gold: 500, lumber: 0, icon: 'ward' },
  // Level 6
  'Amulet of Spell Shield': { gold: 600, lumber: 0, icon: 'spsh' },
  'Orb of Darkness': { gold: 600, lumber: 0, icon: 'odef' },
  'Pendant of Mana': { gold: 600, lumber: 0, icon: 'pmna' },
  'Staff of Silence': { gold: 600, lumber: 0, icon: 'ssil' },

  // ── Charged ───────────────────────────────────────────────────────────────
  // Level 2
  'Crystal Ball': { gold: 150, lumber: 0, icon: 'crys' },
  'Replenishment Potion': { gold: 150, lumber: 0, icon: 'rej3' },
  'Sentry Wards': { gold: 150, lumber: 0, icon: 'wswd' },
  'Wand of Illusion': { gold: 150, lumber: 0, icon: 'will' },
  // Level 3
  'Potion of Greater Healing': { gold: 400, lumber: 0, icon: 'pghe' },
  'Potion of Greater Mana': { gold: 400, lumber: 0, icon: 'pgma' },
  'Potion of Invulnerability': { gold: 400, lumber: 0, icon: 'pnvu' },
  'Scroll of the Beast': { gold: 400, lumber: 0, icon: 'sror' },
  'Wand of Mana Stealing': { gold: 400, lumber: 0, icon: 'woms' },
  // Level 4
  'Ankh of Reincarnation': { gold: 450, lumber: 0, icon: 'ankh' },
  'Book of the Dead': { gold: 450, lumber: 0, icon: 'fgsk' },
  'Healing Wards': { gold: 450, lumber: 0, icon: 'whwd' },
  'Health Stone': { gold: 450, lumber: 0, icon: 'hlst' },
  'Mana Stone': { gold: 450, lumber: 0, icon: 'mnst' },
  'Wand of the Wind': { gold: 450, lumber: 0, icon: 'wcyc' },
  // Level 5
  'Amulet of the Wild': { gold: 550, lumber: 0, icon: 'wild' },
  'Potion of Divinity': { gold: 550, lumber: 0, icon: 'pdiv' },
  'Potion of Restoration': { gold: 550, lumber: 0, icon: 'pres' },
  'Red Drake Egg': { gold: 550, lumber: 0, icon: 'fgrd' },
  'Scroll of Restoration': { gold: 550, lumber: 0, icon: 'sres' },
  'Spiked Collar': { gold: 550, lumber: 0, icon: 'fgfh' },
  'Stone Token': { gold: 550, lumber: 0, icon: 'fgrg' },
  'Talisman of the Wild': { gold: 550, lumber: 0, icon: 'totw' },
  // Level 6
  'Demonic Figurine': { gold: 700, lumber: 0, icon: 'fgdg' },
  'Ice Shard': { gold: 700, lumber: 0, icon: 'shar' },
  'Scepter of Mastery': { gold: 700, lumber: 0, icon: 'ccmd' },
  'Scepter of the Sea': { gold: 700, lumber: 0, icon: 'rots' },

  // ── Artifact ──────────────────────────────────────────────────────────────
  // Level 7
  'Claws of Attack +12': { gold: 550, lumber: 0, icon: 'ratc' },
  'Claws of Attack +15': { gold: 800, lumber: 0, icon: 'ratf' },
  'Inferno Stone': { gold: 700, lumber: 0, icon: 'infs' },
  "Kelen's Dagger of Escape": { gold: 800, lumber: 0, icon: 'desc' },
  'Orb of Frost': { gold: 800, lumber: 0, icon: 'ofro' },
  // Level 8
  'Crown of Kings +5': { gold: 1000, lumber: 0, icon: 'ckng' },
  'Mask of Death': { gold: 1000, lumber: 0, icon: 'modt' },
  'Necklace of Spell Immunity': { gold: 1000, lumber: 0, icon: 'nspi' },
  'Tome of Power': { gold: 1250, lumber: 0, icon: 'tkno' },

  // ── Power-Up ──────────────────────────────────────────────────────────────
  // Runes
  'Rune of Dispel Magic': { gold: 50, lumber: 0, icon: 'rdis' },
  'Rune of Greater Healing': { gold: 300, lumber: 0, icon: 'rhe3' },
  'Rune of Greater Mana': { gold: 300, lumber: 0, icon: 'rma2' },
  'Rune of Greater Resurrection': { gold: 350, lumber: 0, icon: 'rre2' },
  'Rune of Healing': { gold: 200, lumber: 0, icon: 'rhe2' },
  'Rune of Lesser Healing': { gold: 100, lumber: 0, icon: 'rhe1' },
  'Rune of Lesser Resurrection': { gold: 200, lumber: 0, icon: 'rre1' },
  'Rune of Mana': { gold: 100, lumber: 0, icon: 'rman' },
  'Rune of Rebirth': { gold: 250, lumber: 0, icon: 'rreb' },
  'Rune of Restoration': { gold: 300, lumber: 0, icon: 'rres' },
  'Rune of Shielding': { gold: 100, lumber: 0, icon: 'rsps' },
  'Rune of Speed': { gold: 200, lumber: 0, icon: 'rspd' },
  'Rune of Spirit Link': { gold: 200, lumber: 0, icon: 'rspl' },
  'Rune of the Watcher': { gold: 75, lumber: 0, icon: 'rwat' },
  // Tomes
  'Manual of Health': { gold: 100, lumber: 0, icon: 'manh' },
  'Tome of Agility': { gold: 150, lumber: 0, icon: 'tdex' },
  'Tome of Agility +2': { gold: 200, lumber: 0, icon: 'tdx2' },
  'Tome of Experience': { gold: 500, lumber: 0, icon: 'texp' },
  'Tome of Greater Experience': { gold: 1000, lumber: 0, icon: 'tgxp' },
  'Tome of Intelligence': { gold: 150, lumber: 0, icon: 'tint' },
  'Tome of Intelligence +2': { gold: 200, lumber: 0, icon: 'tin2' },
  'Tome of Knowledge': { gold: 200, lumber: 0, icon: 'tpow' },
  'Tome of Strength': { gold: 150, lumber: 0, icon: 'tstr' },
  'Tome of Strength +2': { gold: 200, lumber: 0, icon: 'tst2' },
  // Gold
  'Gold Coins': { gold: 150, lumber: 0, icon: 'gold' },

  // ── Purchasable — Goblin Merchant ─────────────────────────────────────────
  'Boots of Speed': { gold: 250, lumber: 0, icon: 'bspd' },
  'Dust of Appearance': { gold: 75, lumber: 0, icon: 'dust' },
  'Goblin Land Mines': { gold: 225, lumber: 0, icon: 'gobm' },
  'Goblin Night Scope': { gold: 200, lumber: 0, icon: 'tels' },
  'Potion of Invisibility': { gold: 100, lumber: 0, icon: 'pinv' },
  'Potion of Lesser Invulnerability': { gold: 150, lumber: 0, icon: 'pnvl' },
  'Scroll of Healing': { gold: 250, lumber: 0, icon: 'shea' },
  'Scroll of Protection': { gold: 150, lumber: 0, icon: 'spro' },
  'Scroll of Town Portal': { gold: 325, lumber: 0, icon: 'stwp' },
  'Staff of Teleportation': { gold: 150, lumber: 0, icon: 'stel' },
  'Tome of Retraining': { gold: 200, lumber: 0, icon: 'tret' },

  // ── Purchasable — Race Shops ──────────────────────────────────────────────
  // (Arcane Vault, Voodoo Lounge, Ancient of Wonders, Tomb of Relics)
  'Anti-magic Potion': { gold: 100, lumber: 0, icon: 'pams' },
  'Healing Salve': { gold: 100, lumber: 0, icon: 'hslv' },
  'Ivory Tower': { gold: 40, lumber: 25, icon: 'tsct' },
  'Lesser Clarity Potion': { gold: 70, lumber: 0, icon: 'plcl' },
  'Mechanical Critter': { gold: 50, lumber: 0, icon: 'mcri' },
  Moonstone: { gold: 50, lumber: 0, icon: 'moon' },
  'Orb of Corruption': { gold: 375, lumber: 0, icon: 'ocor' },
  'Orb of Fire': { gold: 250, lumber: 0, icon: 'ofir' },
  'Orb of Lightning': { gold: 375, lumber: 0, icon: 'olig' },
  'Orb of Slow': { gold: 325, lumber: 0, icon: 'oslo' },
  'Orb of Venom': { gold: 325, lumber: 0, icon: 'oven' },
  'Potion of Healing': { gold: 150, lumber: 0, icon: 'phea' },
  'Potion of Mana': { gold: 150, lumber: 0, icon: 'pman' },
  'Potion of Speed': { gold: 150, lumber: 0, icon: 'pspd' },
  'Ring of Protection +1': { gold: 75, lumber: 0, icon: 'rde0' },
  'Ring of Protection +3': { gold: 150, lumber: 0, icon: 'rde2' },
  'Ring of Protection +5': { gold: 300, lumber: 0, icon: 'rde4' },
  'Ritual Dagger': { gold: 75, lumber: 0, icon: 'ritd' },
  'Rod of Necromancy': { gold: 150, lumber: 0, icon: 'rnec' },
  'Sacrificial Skull': { gold: 50, lumber: 0, icon: 'skul' },
  'Scroll of Animate Dead': { gold: 700, lumber: 0, icon: 'sand' },
  'Scroll of Mana': { gold: 200, lumber: 0, icon: 'sman' },
  'Scroll of Regeneration': { gold: 100, lumber: 0, icon: 'sreg' },
  'Scroll of Resurrection': { gold: 700, lumber: 0, icon: 'srrc' },
  'Scroll of Speed': { gold: 70, lumber: 0, icon: 'shas' },
  'Staff of Preservation': { gold: 150, lumber: 0, icon: 'spre' },
  'Staff of Sanctuary': { gold: 200, lumber: 0, icon: 'ssan' },
  'Tiny Great Hall': { gold: 600, lumber: 185, icon: 'tgrh' },
  'Vampiric Potion': { gold: 200, lumber: 0, icon: 'vamp' },
  'Wand of Negation': { gold: 120, lumber: 0, icon: 'wneg' },
  'Wand of Neutralization': { gold: 150, lumber: 0, icon: 'wneu' },
}
